### PR TITLE
 Mapping to Exodus-global node-IDs and splitting the bface map to chunks.

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits has two purposes:
1) Get the global node-IDs instead of the local node-IDs, so the the
node-IDs from the code match the ones in the Exodus mesh file.
2) Split the bface map, which associates each boundary face to a side
set, to maps for each mesh-chunk, for parallel computing.

A note for the first point above:
There are three sets of node-IDs in Quinoa. The Exodus-global, Exodus-local, and local-renumbered node IDs. This commit ensures that this mapping from the Exodus-global to local-renumbered and vice-versa is done correctly; since it is required for DG.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/204)

### CODE REVIEW

**Comment by jbakosi** [comment]
Nice work! Minor suggestions in comments + a potentially unintended behavior passing a copy instead of a reference to the map `bface` in `genNbfacTet`. (Please correct me if I misunderstand it).

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Inciter/FaceData.C, line 28 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GQwgdAmjC5cVo7LOv:-L5GQwgdAmjC5cVo7LOw:bgra3m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/FaceData.C#L28)):*
> ```
>   const std::map< int, std::vector< std::size_t > >& bface_complete,
>   const std::vector< std::size_t >& triinpoel_complete,
>   const std::vector< std::size_t >& nodemap )// : m_bface( bface )
> ```

If `m_bface` get initialized in the ctor body, let's remove the comment from here.

---

*[src/Inciter/Partitioner.C, line 84 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GRkbe9tDUuOGY8gfT:-L5GRkbe9tDUuOGY8gfU:b-p2aib) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.C#L84)):*
> ```
> //! \param[in] scheme Discretization scheme
> //! \param[in] nbfac Total number of boundary faces
> //! \param[out] bface Face lists mapped to side set ids
> ```

`bface` is not `out`, but `in`.

---

*[src/Inciter/Partitioner.C, line 85 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GRvKz-md_oFmz1C4C:-L5GRvKz-md_oFmz1C4D:bldn13x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.C#L85)):*
> ```
> //! \param[in] nbfac Total number of boundary faces
> //! \param[out] bface Face lists mapped to side set ids
> // *****************************************************************************
> ```

Let's add doxygen comments for `triinpoel` and `nodemap`

---

*[src/Inciter/Partitioner.h, line 335 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GS4k_9XcmHa0s1h90:-L5GS4k_9XcmHa0s1h91:bjyf0if) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.h#L335)):*
> ```objc
>     //! \brief Boundary face-node connectivity.
>     std::vector< std::size_t > m_triinpoel;
>     //! \brief Local-global node-ID map.
> ```

Maybe here it would be good to add a more detailed comment on what IDs this `nodemap` maps from and to, using doxygen's `\details` keyword.

---

*[src/IO/ExodusIIMeshReader.C, line 418 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GSdc6ArwfA0ynMkay:-L5GSdc6ArwfA0ynMkaz:blox54m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/IO/ExodusIIMeshReader.C#L418)):*
> ```
> // *****************************************************************************
> //  Read local to global node-ID map from ExodusII file
> //! \return node_map Vector mapping the local Exodus node-IDs to global node-IDs
> ```

Also, here, e.g., using `\details`, we could give a little more explanation and background as to why this nodemap is read in and how it is used later. (The same could be just copied to `Partitioner.h`.

---

*[src/Mesh/DerivedData.C, line 814 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GUBjN2KxyAmKubLot:-L5GUBjN2KxyAmKubLou:bxgna4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Mesh/DerivedData.C#L814)):*
> ```
>              const std::map< int, std::vector< std::size_t > >& bface_complete,
>              std::vector< std::size_t >& triinpoel,
>              std::map< int, std::vector< std::size_t > > bface )
> ```

As `bface` is not a reference (but a copy of the argument passed by whoever uses this function) and we modify it below, this seems like it will leave `bface` whatever it was before (as was passed). This does not seem like what we want here, but probably a non-const reference:
```
std::map< int, std::vector< std::size_t > >& bface
```

---

*[src/Mesh/DerivedData.h, line 90 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-L5GUmNlD1dBbZ5zDm0_:-L5GUmNlD1dBbZ5zDm0a:b1cz9jz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Mesh/DerivedData.h#L90)):*
> ```objc
>              const std::map< int, std::vector< std::size_t > >& bface_complete,
>              std::vector< std::size_t >& triinpoel,
>              std::map< int, std::vector< std::size_t > > bface );
> ```

Take `bface` by non-const ref?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/204#-:-L5GVfGcBMqEu1n8tk-r:bx4g0eg)*

**Comment by adityakpandare** [comment]
Yeah you're right, it should have an '&'. Thanks!

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/Inciter/FaceData.C, line 28 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GQwgdAmjC5cVo7LOv:-L5GqTy5QkYHrd-E7wQu:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/FaceData.C#L28)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If `m_bface` get initialized in the ctor body, let's remove the comment from here.
</blockquote></details>

Done.

---

*[src/Inciter/Partitioner.C, line 84 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GRkbe9tDUuOGY8gfT:-L5Gqcs0_opMlF5K_WFH:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.C#L84)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`bface` is not `out`, but `in`.
</blockquote></details>

Done.

---

*[src/Inciter/Partitioner.C, line 85 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GRvKz-md_oFmz1C4C:-L5GrALEW5GhSv24v5c-:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.C#L85)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's add doxygen comments for `triinpoel` and `nodemap`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-:-L5GsCuwmnn3c7s4LncY:b1e0kxw)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/Mesh/DerivedData.C, line 814 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GUBjN2KxyAmKubLot:-L5H7ojOYjSLb9f8kkSR:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Mesh/DerivedData.C#L814)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

As `bface` is not a reference (but a copy of the argument passed by whoever uses this function) and we modify it below, this seems like it will leave `bface` whatever it was before (as was passed). This does not seem like what we want here, but probably a non-const reference:
```
std::map< int, std::vector< std::size_t > >& bface
```
</blockquote></details>

Done.

---

*[src/Mesh/DerivedData.h, line 90 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GUmNlD1dBbZ5zDm0_:-L5H7oA5BHPOpd2S9hbu:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Mesh/DerivedData.h#L90)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Take `bface` by non-const ref?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Inciter/Partitioner.h, line 335 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GS4k_9XcmHa0s1h90:-L5H9fv0aNo0lQLeKiwm:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/Inciter/Partitioner.h#L335)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Maybe here it would be good to add a more detailed comment on what IDs this `nodemap` maps from and to, using doxygen's `\details` keyword.
</blockquote></details>

Done.

---

*[src/IO/ExodusIIMeshReader.C, line 418 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-L5GSdc6ArwfA0ynMkay:-L5H9N45i6hmgHnAmK4q:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/80827f95a303d48f89167a1cefa495123d5e1928/src/IO/ExodusIIMeshReader.C#L418)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Also, here, e.g., using `\details`, we could give a little more explanation and background as to why this nodemap is read in and how it is used later. (The same could be just copied to `Partitioner.h`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204)*

**Comment by jbakosi** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204#-:-L5HAp8PaNTqkgTmcQ3J:bnfp4nl)*

**Comment by adityakpandare** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204)*

**Comment by jbakosi** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/204)*

**Pull request merged**
