### PR TITLE
Thinc with p1

### PR DESCRIPTION
**Pull request by adityakpandare**
Initial progress towards THINC with DGP1. Not stable yet.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
Just FYI: the volume fraction equations now only solve the FV equations, if THINC reconstruction is being used. This reduces costs (1 vs 4 DOFs for the `nmat` volfrac eqns) and leads to same interface sharpness (if not more).

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVHW72O76uifJzKFi2g:b-qjxqy2)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @jbakosi and @WeizhaoLi2018)

**Comment by jbakosi** [comment]
I don't like how `m_numEqDof` contaminates the PDE classes as you wrote it. It can already be sized in `DG::DG()`, and its contents could also be initialized by doing a `brigand::for_each` over all PDE types. Instead of passing it as non-const ref to initialize(), I would create a new virtual member function for all PDE types which return `numEqDof` sized and initialized and  would call it within an outer loop over all PDE types.

**Review by adityakpandare — COMMENTED** [review]
A few questions about this:
1. Doesn't a PDE-class member returning numEqDof also "contaminate" the PDE classes; just like the way I'm doing it currently?
2. Would something like the following in `DG::DG()` be okay?
```
for (const auto& eq: g_dgpde) {
  eq.numEqDof(m_numEqDof);
}
```
Returning the `m_numEqDof` would be tricky, if we're dealing with multiple PDE-systems, hence this solution. Also, I would like to keep code simple and not resort to `brigand::for_each`. :-)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVHlRMb9sUwA93ezJ2u:bvuysyf)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @jbakosi and @WeizhaoLi2018)

**Comment by jbakosi** [comment]
> A few questions about this:
> 
> 1. Doesn't a PDE-class member returning numEqDof also "contaminate" the PDE classes; just like the way I'm doing it currently?

It would have its own function to deal with only that, instead of adding it into `initialize()`. I agree, not ideal, but still a little cleaner, I think.

> 2. Would something like the following in `DG::DG()` be okay?
> 
> ```
> for (const auto& eq: g_dgpde) {
>   eq.numEqDof(m_numEqDof);
> }
> ```

I think so.

> Returning the `m_numEqDof` would be tricky, if we're dealing with multiple PDE-systems, hence this solution. Also, I would like to keep code simple and not resort to `brigand::for_each`. :-)

`brigand::for_each` was my initial thought. I think a for loop over `g_dgpde` should suffice.

**Review by adityakpandare — COMMENTED** [review]
Agreed. Pushing changes soon.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVHnWIm9ji8eGkp_vAd:bqvphe7)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @jbakosi and @WeizhaoLi2018)

**Review by jbakosi — APPROVED** [review]
> Reviewed 10 of 16 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by WeizhaoLi2018 — COMMENTED** [review]
Hey @adityakpandare just wonder how you checked the sharpness between this DGP1 with THINC and P0P1 with THINC. Did you run a testcase like interface advection and compare the diagnostic files for that? 

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVIE6kTAYUBBlYqpNqP:bw9ktxz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Yes, I compared interface sharpness for a couple of problems, such as water-air shocktube, interface advection. I compared the interface profile in 1D, and the number of cells marked as interface cells. The result was both (THINC with DGP1 and P0P1) gave same interface sharpness. Only difference was when I tried using DGP1 for volume fraction with THINC reconstructions: THINC+DGP1 for volume fractions led to slightly smeared interfaces as compared to THINC+P0P1 for volume fractions. This is one of the reasons why the DGP1-multimat uses THINC+P0P1 for volume fraction equations, and DGP1 for all other equations. About comparing diagnostic files, I haven't gotten to that yet; because this is just an initial commit. THINC with DGP1 is not completely working yet. When it does, I will be adding regression tests.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVIWE_LEoGQd_6S78-X:b-ff16jh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by WeizhaoLi2018 — APPROVED** [review]
Sounds good!

> Reviewed 10 of 16 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVId7QP74hjNzcOgT71:brxp9sd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Thanks for the quick review guys!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477#-:-MVIuVrh-won3vraxyop:bxgw13w)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jbakosi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
