### PR TITLE
Add sponge parameter to symbc in compflow

### PR DESCRIPTION
**Pull request by jbakosi**
This extends symmetry BCs in `CompFlow` to configure an optional "sponge" parameter, to enable a boundary to absorb some kinetic energy. Example:
```
    bc_sym
      sideset 1 2 3 end
      sponge 0.98 1.0 1.0 end    # absorb some kinetic energy on side set 1 (tube wall)
    end
```

The above will absorb 2% of the kinetic energy along side set 1 and leave the other two symmetry BCs unmodified. The number of entries in the `sponge ... end` block must equal that of the number of symmetry BC side sets configured. The sponge parameters must be between 0.0 and 1.0 inclusive, basic error checking is added.

Still thinking about a good regression test for this. Tried with a larger problem, but we should _not_ merge this without a regression test.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
I have only a couple of comments, otherwise looks good.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-:-Ma0F47nDIGLIs4Slw1K:b-le3qj3)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[src/Control/Keywords.hpp, line 5366 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0BFLn-QxTNs7uaJVO:-Ma0BFLo035tMcj6VkVv:buyqsik) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/Control/Keywords.hpp#L5366)):*
> ```cpp
>     absorption coefficient for each symmetry BC sideset configured. The
>     coefficient must be between 0.0 and 1.0, expressing the percentage of kinetic
>     energy kept at the boundary: 0.0 - fully absorbed, 1.0 - fully kept.)";
> ```

Would it be better to invert this definition? Since it's a "sponge", we could say "fraction of kinetic energy absorbed by the sponge", i.e. if the input is 0.0, no KE is absorbed by the spongy symmetry-bc, and if it's 1.0, all the KE is absorbed.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 783 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0EVHb78GpKQyUTWz-:-Ma0EVHcBIs5cFsaPAsd:b-pbxf9a) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/PDE/CompFlow/CGCompFlow.hpp#L783)):*
> ```cpp
>                   U(p,1,m_offset) *= sp[s];
>                   U(p,2,m_offset) *= sp[s];
>                   U(p,3,m_offset) *= sp[s];
> ```

Another option is to only remove `s*v_dot_n` from the velocity vector; so that the sponge "absorbs" some part of the normal component of velocity, rather than reflecting it entirely. This would effectively make the symmetry-bc less "rigid" by allowing some material to pass through it, i.e. sponging action.

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/Keywords.hpp, line 5366 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0BFLn-QxTNs7uaJVO:-MaeLNFG41tEMU38bHgl:b-584tig) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/Control/Keywords.hpp#L5366)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Would it be better to invert this definition? Since it's a "sponge", we could say "fraction of kinetic energy absorbed by the sponge", i.e. if the input is 0.0, no KE is absorbed by the spongy symmetry-bc, and if it's 1.0, all the KE is absorbed.
</blockquote></details>

Yeah, you are right. I have changed this.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 783 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0EVHb78GpKQyUTWz-:-MaeLU5Z7yTb04HPKlJu:b-xrks9t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/PDE/CompFlow/CGCompFlow.hpp#L783)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Another option is to only remove `s*v_dot_n` from the velocity vector; so that the sponge "absorbs" some part of the normal component of velocity, rather than reflecting it entirely. This would effectively make the symmetry-bc less "rigid" by allowing some material to pass through it, i.e. sponging action.
</blockquote></details>

After discussing this further, I will keep the current version of removing a percentage from the tangential momentum, but will also experiment with removing a percentage of the normal pressure gradient. But I wan to do that in another PR. Okay?

**Review by adityakpandare — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-:-MaeWyJt2UjCDRW49H-A:bnfp4nl)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/Control/Keywords.hpp, line 5366 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0BFLn-QxTNs7uaJVO:-MaeX01C5sskgVvWzXxU:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/Control/Keywords.hpp#L5366)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, you are right. I have changed this.
</blockquote></details>

Thanks!
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 783 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0EVHb78GpKQyUTWz-:-MaeX6h7ElwkOa_Um2mu:b-h4njhx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/PDE/CompFlow/CGCompFlow.hpp#L783)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

After discussing this further, I will keep the current version of removing a percentage from the tangential momentum, but will also experiment with removing a percentage of the normal pressure gradient. But I wan to do that in another PR. Okay?
</blockquote></details>

That's alright with me. Thanks!

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 783 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0EVHb78GpKQyUTWz-:-MaedcbV6Tk4fj6z2Smu:b-7nrsdo) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/PDE/CompFlow/CGCompFlow.hpp#L783)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

That's alright with me. Thanks!
</blockquote></details>

Okay. But can you remind me what we agreed on regarding the normal momentum as you are suggesting? Would that be also useful? Should I try that too?

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/492)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 783 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/492#-Ma0EVHb78GpKQyUTWz-:-Maf75_KB870ruUN7N9O:buhc1kz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f39fe57a133b2c7da8f3a0a0edc89421384473d7/src/PDE/CompFlow/CGCompFlow.hpp#L783)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Okay. But can you remind me what we agreed on regarding the normal momentum as you are suggesting? Would that be also useful? Should I try that too?
</blockquote></details>

We (with Jacob) agreed that we should not be removing from normal momentum, because that would be a "porous" wall, and that's not what we're trying to mimic. I think scaling down the normal pressure would be a better approach.

**Pull request merged**
