### PR TITLE
Add ALE to ALECG

### PR DESCRIPTION
**Pull request by jbakosi**
This adds basic mesh motion to `ALECG` and exercises it with a test problem to verify the satisfaction of the geometric conservation law.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Awesome! I have a few questions, but otherwise, looks good!

> Reviewed 25 of 47 files at r1, 5 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-:-MZYXfDT-cWZwej24pC_:b-q1ae57)* status: 28 of 50 files reviewed, 8 unresolved discussions (waiting on @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 917 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYTeuF90JHRHYAYap-:-MZYTeuF90JHRHYAYap0:bgd0d1t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L917)):*
> ```cpp
> ALECG::solve()
> // *****************************************************************************
> //  Solve linear systems
> ```

I would say "evolve/advance system of equations", because "solve linear system" sounds as if we're doing a matrix solve.
___
*[src/Inciter/ALECG.cpp, line 925 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYTy6z6wWDlEbtRTYn:-MZYTy6z6wWDlEbtRTYo:b-vi167l) ([raw file](https://github.com/quinoacomputing/quinoa/blob/198e127ce20bf6e9188dfe57e3e4106ae61faceb/src/Inciter/ALECG.cpp#L925)):*
> ```cpp
>         m_lhs(b,c,0) = 1.0;
>         auto deltat = steady ? m_dtp[b] : d->Dt();
>         m_rhs(b,c,0) = bc[c].second / deltat / rkcoef[m_stage];
> ```

Where are the BCs applied to `m_rhs` now?
___
*[src/Inciter/ALECG.cpp, line 939 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYVVnUEc3vMwr5BClW:-MZYVVnUEc3vMwr5BClX:b-cjrs2h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L939)):*
> ```cpp
>   // Solve the sytem
>   if (g_inputdeck.get< tag::discr, tag::steady_state >()) {
> ```

Should we put a check somewhere that the ALE scheme should not be used with Steady-state local time stepping?
___
*[src/Inciter/ALECG.cpp, line 1232 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYWR7lDMXcRk2wcmbL:-MZYWR7lDMXcRk2wcmbM:b-4jhble) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L1232)):*
> ```cpp
> 
>     // Collect node block and surface field solution
>     auto u = m_u;
> ```

Is there a way to get rid of this copy? I know this is not part of this PR, but just curious.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 1322 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYUbqDEB08Xsrc_w6t:-MZYUbqDEB08Xsrc_w6u:bh74pac) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/PDE/CompFlow/CGCompFlow.hpp#L1322)):*
> ```cpp
>         int sym = symbctri[e];
>         p = eos_pressure< eq >( m_system, rA, ruA/rA, rvA/rA, rwA/rA, reA );
>         vn = sym ? (nx*(-w1A) + ny*(-w2A) + nz*(-w3A))
> ```

I believe the mesh should have a zero component of velocity normal to a symmetry boundary. This is basically so that the mesh motion follows the fluid behavior; i.e. there is no interaction of fluids on two sides of the symmetry boundary, making them "independent" of sorts.
___
*[src/PDE/Riemann/Rusanov.hpp, line 48 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZEIj7L9lkSY2ptAaEn:-MZEIj7L9lkSY2ptAaEo:b-odj2b5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/63a42c607f61b8a72117ab674dbde81a75d98c4e/src/PDE/Riemann/Rusanov.hpp#L48)):*
> ```cpp
>   //! \param[in] rwL Left Z momentum
>   //! \param[in] reL Left total specific energy
>   //! \param[in] rL Right density
> ```

This should probably be `rR`?
___
*[tests/regression/inciter/ale/CMakeLists.txt, line 27 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYXUPdApFWBS2zgH26:-MZYXUPdApFWBS2zgH27:bj8ppju) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/tests/regression/inciter/ale/CMakeLists.txt#L27)):*
> ```CMake
>                     BIN_RESULT out.e-s.0.1.0 out.e-s.10.1.0
>                     BIN_DIFF_PROG_CONF exodiff.cfg
>                     TEXT_BASELINE diag.std
> ```

How do both GCL and Sod use the same diagnostic file as a baseline?
___
*[tests/regression/inciter/ale/gcl.q, line 43 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYWwwt3Qq7imX43V_n:-MZYWwwt3Qq7imX43V_o:brkzpi1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/tests/regression/inciter/ale/gcl.q#L43)):*
> ```q
> 
>   amr
>     #t0ref true
> ```

should we remove this commented line?

**Review by adityakpandare — COMMENTED** [review]
> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489)* status: 29 of 52 files reviewed, 3 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 925 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYTy6z6wWDlEbtRTYn:-MZZK2cv3zXnSgr_uGzU:b-5hynew) ([raw file](https://github.com/quinoacomputing/quinoa/blob/198e127ce20bf6e9188dfe57e3e4106ae61faceb/src/Inciter/ALECG.cpp#L925)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

In `ALECG::BC()`, after the solve.
</blockquote></details>

Ah, thanks!
___
*[src/Inciter/ALECG.cpp, line 1232 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYWR7lDMXcRk2wcmbL:-MZZK8ksCCbscnz6BEwd:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L1232)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yes, good point. This is leftover code from when the solution vector was passed in as a non-const and it was modified, but this is no longer the case so I fixed it up.
</blockquote></details>

Thanks!

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489)* status: 29 of 52 files reviewed, 3 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 939 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYVVnUEc3vMwr5BClW:-MZoAofd0D0DuORoRQ3j:b-3laqas) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L939)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, I agree that's good idea. I will put in an error triggered for user input if that is configured.
</blockquote></details>

Done in 6a32d1160.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 1322 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYUbqDEB08Xsrc_w6t:-MZnyaF76OXMZ_ygPt12:byr955f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/PDE/CompFlow/CGCompFlow.hpp#L1322)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I believe the mesh should have a zero component of velocity normal to a symmetry boundary. This is basically so that the mesh motion follows the fluid behavior; i.e. there is no interaction of fluids on two sides of the symmetry boundary, making them "independent" of sorts.
</blockquote></details>

Alright, updated.
___
*[tests/regression/inciter/ale/CMakeLists.txt, line 27 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYXUPdApFWBS2zgH26:-MZo76L34vxvR3H879Cq:bf5pzre) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/tests/regression/inciter/ale/CMakeLists.txt#L27)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Oh. Good eye! It seems like I totally screwed up the numdiff input file and it is accepting large diffs as pass. I need to look a this closer.
</blockquote></details>

I think I fixed it. Please take a look at 0b9c20655.

**Review by adityakpandare — APPROVED** [review]
Looks good!

> Reviewed 1 of 47 files at r1, 1 of 9 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-:-MZoGS7l4Xqj1w0uGX3n:b-vs1prh)* status: 37 of 56 files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 726 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZoGL6DD-rCx3Flui_l:-MZoGL6DD-rCx3Flui_m:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a32d1160caab870e8ea9d8f60171cb7ca2bc76c/src/Control/Inciter/InputDeck/Grammar.hpp#L726)):*
> ```cpp
>       if (steady && ale) {
>         Message< Stack, ERROR, MsgKey::STEADYALE >( stack, in );
>       }
> ```

Thanks!
___
*[src/Inciter/ALECG.cpp, line 939 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYVVnUEc3vMwr5BClW:-MZoGQR764kouNRkcD3e:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/src/Inciter/ALECG.cpp#L939)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Done in 6a32d1160.
</blockquote></details>

Thanks!
___
*[tests/regression/inciter/ale/CMakeLists.txt, line 27 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZYXUPdApFWBS2zgH26:-MZoFv89ElhipwqOW8NI:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/777469a3f4ca08f5a547251edd30b2e7662a1c30/tests/regression/inciter/ale/CMakeLists.txt#L27)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I think I fixed it. Please take a look at 0b9c20655.
</blockquote></details>

Thanks!

**Review by jbakosi — COMMENTED** [review]
Thanks for the quick review.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-:-MZoNan_94azeY7SwOQn:b-ncgzbp)* status: 37 of 56 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 726 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/489#-MZoGL6DD-rCx3Flui_l:-MZoNe_-CQCtbeD5Cllu:b-80tlqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a32d1160caab870e8ea9d8f60171cb7ca2bc76c/src/Control/Inciter/InputDeck/Grammar.hpp#L726)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Sure.

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/489)* status: 37 of 56 files reviewed, all discussions resolved (waiting on @jbakosi)

**Pull request merged**
