### PR TITLE
Viscous terms in the FV scheme

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits adds the viscous terms to the FV scheme, and the no-slip wall BC. Viscous terms are triggered by specifying `mu` for the stiffened-gas EOS. It is not considered a separate 'physics' policy anymore, which allows it to be selected with other physics policies. It is currently untested.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624)

### CODE REVIEW

**Review by g-rydquist — CHANGES_REQUESTED** [review]
Nice work Aditya, looks good. It makes sense to me for the most part. I also see that you just pushed a new commit with the parsing for the nosllip BC right as I was finishing up.

> Reviewed 23 of 23 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-:-O3Z82Qn7mWG_rA9yg6o:b-o4r36m)* status: all files reviewed, 4 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Control/Inciter/InputDeck/LuaParser.cpp` line 426 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Y_7Gk9Wgvt-UKWwth:-O3Y_7Gk9Wgvt-UKWwti:b3p5ehe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/Control/Inciter/InputDeck/LuaParser.cpp#L426)):*
> ```cpp
>           sol_mat[i+1]["mu"] = std::vector< tk::real >(ntype, 0.0);
>         else gideck.get< tag::multimat, tag::viscous >() = true;
>         checkStoreMatProp(sol_mat[i+1], "mu", ntype, mati_deck.get< tag::mu >());
> ```

I noticed that information about the no slip BC is not stored in a similar way. I tried running a simulation with some no slip BCs and ending up getting a leaky boundary error, and I'm wondering if this is why.

Edit: Nevermind, I see this has been changed, and the leaky boundary has been fixed.
___
*[`src/Control/Inciter/InputDeck/LuaParser.cpp` line 1066 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3ZA0YV3NGI-3UTNpuX:-O3ZA0YV3NGI-3UTNpuY:b-jhowf7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c993b216ae65a2d3025aca7d1934618982914966/src/Control/Inciter/InputDeck/LuaParser.cpp#L1066)):*
> ```cpp
> 
>       storeVecIfSpecd< uint64_t >(sol_bc[i+1], "noslipwall",
>         bc_deck[i].get< tag::extrapolate >(), {});
> ```

Should this tag be "tag::noslipwall"?
___
*[`src/PDE/Integrate/Boundary.cpp` line 537 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3YflUi9Ki3H4JUgqHP:-O3YflUi9Ki3H4JUgqHQ:brqxnod) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Boundary.cpp#L537)):*
> ```cpp
>           std::sqrt(tk::dot(fn,fn));
>         for (std::size_t i=0; i<3; ++i)
>           centroids[1][i] = centroids[0][i] + 2.0*d*fn[i];
> ```

Can you explain what is happening in this line? I am following the rest of this function but I'm not exactly sure why the ghost cell centroid is calculated in this way.
___
*[`src/PDE/Integrate/Surface.cpp` line 708 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3YiZP04XWxUOH4QI4Q:-O3YiZP04XWxUOH4QI4R:bqujpb6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L708)):*
> ```cpp
>   for (std::size_t i=0; i<3; ++i)
>     for (std::size_t j=0; j<3; ++j)
>       dudx_m[i][j] -= ( tk::dot(dudx_m[i], r_f) -
> ```

Can you explain why the gradient is modified in this way?
___
*[`src/PDE/Integrate/Surface.cpp` line 723 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Yk27Z3Hh0BEqbx52u:-O3Yk27Z3Hh0BEqbx52v:b-rgile7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L723)):*
> ```cpp
>   tau[0] = mu * ( 4.0 * dudx_m[0][0] - 2.0*(dudx_m[1][1] + dudx_m[2][2]) ) / 3.0;
>   tau[1] = mu * ( 4.0 * dudx_m[0][0] - 2.0*(dudx_m[1][1] + dudx_m[2][2]) ) / 3.0;
>   tau[2] = mu * ( 4.0 * dudx_m[0][0] - 2.0*(dudx_m[1][1] + dudx_m[2][2]) ) / 3.0;
> ```

I assume the viscous stresses are written in this way as a result of how the velocity gradient is modified?
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 260 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Z-s3B6rKM9ORgh09i:-O3Z-s3B6rKM9ORgh09j:b4itsnj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/MultiMat/BCFunctions.hpp#L260)):*
> ```cpp
>       ur[densityIdx(nmat, k)] = ul[densityIdx(nmat, k)];
>       ur[energyIdx(nmat, k)] = ul[energyIdx(nmat, k)];
>       if (solidx[k] > 0) {
> ```

I'm not exactly following the solid parts, so I will just assume they're correct.

**Review by adityakpandare — COMMENTED** [review]
Thank you for reviewing the code! I'm still testing this with the lid-driven cavity. Will wait to merge until I have confidence (and after we complete this code review).

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-:-O3ZLF9k7rAo-hkHOKQO:b-trx01h)* status: all files reviewed, 4 unresolved discussions (waiting on @g-rydquist)

___
*[`src/Control/Inciter/InputDeck/LuaParser.cpp` line 1066 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3ZA0YV3NGI-3UTNpuX:-O3ZC_Yi80GZhCgIIhgU:bla85og) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c993b216ae65a2d3025aca7d1934618982914966/src/Control/Inciter/InputDeck/LuaParser.cpp#L1066)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Should this tag be "tag::noslipwall"?
</blockquote></details>

Good catch!  Fixed this.
___
*[`src/PDE/Integrate/Boundary.cpp` line 537 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3YflUi9Ki3H4JUgqHP:-O3ZLSmh5U6cD8NG9VlR:bvkkfr5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Boundary.cpp#L537)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Can you explain what is happening in this line? I am following the rest of this function but I'm not exactly sure why the ghost cell centroid is calculated in this way.
</blockquote></details>

The ghost-cell is supposed to be a 'reflection' of the boundary cell. This reflection is about the boundary-face. This means, that the vector pointing from the internal-cell centroid to the ghost-cell centroid is normal to the face (aligned to face-normal), and has length `2*d`. Here, `d` is the distance between the internal-cell centroid and the boundary-face. Based on this information, the centroid of the ghost-cell can be computed using vector algebra. Added this to the comments.
___
*[`src/PDE/Integrate/Surface.cpp` line 708 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3YiZP04XWxUOH4QI4Q:-O3ZG7AL9yUAM8VfFcwc:b9rykbi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L708)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Can you explain why the gradient is modified in this way?
</blockquote></details>

A central difference approximation of the gradient results from taking the averages of the left and right cell gradients. Central difference results in and unstable dispersive scheme, leading to odd-even decoupling. This modification is the way to stabilize the central-difference gradient. See https://arc.aiaa.org/doi/abs/10.2514/2.871 for a more detailed explanation. I have now added a reference to one of the paper using this discretization.
___
*[`src/PDE/Integrate/Surface.cpp` line 723 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Yk27Z3Hh0BEqbx52u:-O3ZCti8989be_oKUAa1:bpzsy3d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L723)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

I assume the viscous stresses are written in this way as a result of how the velocity gradient is modified?
</blockquote></details>

This is the shear stress tensor (https://en.wikipedia.org/wiki/Newtonian_fluid#General_compressible_case) evaluated using the modified velocity gradient.
___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 260 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Z-s3B6rKM9ORgh09i:-O3ZHpOw-Rbmi6CndxUd:b-qub5xd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/MultiMat/BCFunctions.hpp#L260)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

I'm not exactly following the solid parts, so I will just assume they're correct.
</blockquote></details>

I'm not sure about how this needs to handle solids. Hence, leaving it as is.

**Review by g-rydquist — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[`src/PDE/Integrate/Surface.cpp` line 723 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Yk27Z3Hh0BEqbx52u:-O3ZVJus2iOCX_NwOw2a:b-4lerd9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L723)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is the shear stress tensor (https://en.wikipedia.org/wiki/Newtonian_fluid#General_compressible_case) evaluated using the modified velocity gradient.
</blockquote></details>

Ah, you know I somehow missed the parentheses surrounding `dudx_m[1][1] + dudx_m[2][2]` ! Still, why are all the diagonal components equivalent? Shouldn't it be:



_Code snippet:_
```cpp
tau[0] = mu * ( 4.0 * dudx_m[0][0] - 2.0*(dudx_m[1][1] + dudx_m[2][2]) ) / 3.0;
tau[1] = mu * ( 4.0 * dudx_m[1][1] - 2.0*(dudx_m[0][0] + dudx_m[2][2]) ) / 3.0;
tau[2] = mu * ( 4.0 * dudx_m[2][2] - 2.0*(dudx_m[1][1] + dudx_m[0][0]) ) / 3.0;
```

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624)* status: all files reviewed, 1 unresolved discussion (waiting on @g-rydquist)

___
*[`src/PDE/Integrate/Surface.cpp` line 723 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3Yk27Z3Hh0BEqbx52u:-O3Zel-2-H-AEj-ENTWk:b-4naukp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/3fd304da0811b2764f7c80cd7a3845b980f915e3/src/PDE/Integrate/Surface.cpp#L723)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Ah, you know I somehow missed the parentheses surrounding `dudx_m[1][1] + dudx_m[2][2]` ! Still, why are all the diagonal components equivalent? Shouldn't it be:
</blockquote></details>

You're absolutely right! Thank you!

**Review by g-rydquist — CHANGES_REQUESTED** [review]
Looks good, just one question. Also, I had also been setting up a lid driven flow case. I do not have numerical comparisons with some of the benchmarks, but things look pretty good just from the eye test, with momentum diffusing through as you'd expect. I attached a plot of some streamlines.


> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-:-O3ch52E4HDPwvTlFC0S:b7xqxai)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 216 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3cgqDd6RUIvUkg6W5r:-O3cgqDd6RUIvUkg6W5s:begpxte) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7d1cf0dc72b696e8b8ec2da9525cfddbd90097b1/src/PDE/MultiMat/BCFunctions.hpp#L216)):*
> ```cpp
>           ur[volfracIdx(nmat,k)] = alphamin;
>         auto p = ul[ncomp+pressureIdx(nmat,k)] / ul[volfracIdx(nmat,k)];
>         auto rhok = mat_blk[k].compute< EOS::density >(p, ft);
> ```

Why is the far-field temperature used to calculate the density for both the subsonic inflow and outflow conditions? Should this density be calculated with the temperature of the internal cell?

**Review by adityakpandare — COMMENTED** [review]
Yes, I'm seeing the same. It's just not converging even after a very long run time. I'm working on polishing the viscous-flux BC's a bit more to see if that helps convergence. Stay tuned...

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-:-O3cjdRP2QVpDN3ZFHhI:bns97yd)* status: all files reviewed, 1 unresolved discussion (waiting on @g-rydquist)

___
*[`src/PDE/MultiMat/BCFunctions.hpp` line 216 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-O3cgqDd6RUIvUkg6W5r:-O3cjFIQ3rbAKtAygHTA:b-tjus5b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7d1cf0dc72b696e8b8ec2da9525cfddbd90097b1/src/PDE/MultiMat/BCFunctions.hpp#L216)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Why is the far-field temperature used to calculate the density for both the subsonic inflow and outflow conditions? Should this density be calculated with the temperature of the internal cell?
</blockquote></details>

For subsonic inflow, the temperature from the farfield (but the pressure from the internal cell) are typically used. This is because of the comment about characteristic above. However, you're right for the subsonic outflow, that the temperature from the internal cell should be used. That's a bug. I'll fix it soon.

**Review by g-rydquist — APPROVED** [review]
Nice work! :lgtm:

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/624#-:-O3hORYuBpTp3Z3P41Ga:b-8ewgme)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
