### PR TITLE
Trilinos update

### PR DESCRIPTION
**Pull request by adityakpandare**
See https://github.com/quinoacomputing/quinoa/issues/565

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
:lgtm:

> Reviewed 288 of 288 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-:-NQRoCxj7wqQ51rm_woQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by jbakosi — APPROVED** [review]
Just to be sure, I would recommend testing this out at large scales before merging. E.g., run the 700M-cell mesh a few time steps on  about 5K cores both non-SMP and SMP.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-:-NQRq31x8Kg_JXDL8NII:bjvoctc)* status: all files reviewed, 4 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Inciter/Partitioner.cpp` line 94 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRoDWhCUaQmdU9Xq3E:-NQRoDWhCUaQmdU9Xq3F:b-j59r4k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/Inciter/Partitioner.cpp#L94)):*
> ```cpp
> // *****************************************************************************
> {
>   Kokkos::initialize();
> ```

This is very ugly and error-prone. I know you agree. Frankly , https://github.com/trilinos/Trilinos/issues/11197#issuecomment-1301325163 is not very convincing to me. I think they ought to be able hide this from client code. Their explanation sounds like a punt to me.
___
*[`src/LoadBalance/ZoltanInterOp.hpp` line 35 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRp5c822gEMle11mxb:-NQRp5c822gEMle11mxc:b-qsioxt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/LoadBalance/ZoltanInterOp.hpp#L35)):*
> ```cpp
> geomPartMesh( tk::ctr::PartitioningAlgorithmType algorithm,
>               const std::array< std::vector< tk::real >, 3 >& elemcoord,
>               const std::vector< long long >& elemid,
> ```

That was also necessary? Why? Will that now use twice the size for integers? How did this work so far. I have tested this with 1.5B-cell meshes.
___
*[`src/NoWarning/kokkos_cr.hpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpQeG07VUSlClAfr8:-NQRpQeG07VUSlClAfr9:b-atcyq4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/NoWarning/kokkos_cr.hpp#L84)):*
> ```cpp
> #elif defined(__INTEL_COMPILER)
>   #pragma warning( pop )
> #endif
> ```

... and the size of this file tells you that this is including crufty code.
___
*[`tests/regression/inciter/compflow/Euler/VorticalFlow/CMakeLists.txt` line 255 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpnkk4sJDQuYd3hnK:-NQRpnkk4sJDQuYd3hnL:bicm46t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/57b193477ee28389fca39479120a8711f0bfdc32/tests/regression/inciter/compflow/Euler/VorticalFlow/CMakeLists.txt#L255)):*
> ```CMake
>                     TEXT_RESULT diag
>                     TEXT_DIFF_PROG_CONF vortical_flow_diag.ndiff.cfg
>                     LABELS diagcg)
> ```

Why remove? They don't test anything new?

**Review by adityakpandare — COMMENTED** [review]
I agree. I will test this on larger scales. Thanks for taking a look!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-:-NQRtsKv4b8Ot6g8bnZ3:b-rqrut3)* status: all files reviewed, 4 unresolved discussions (waiting on @jbakosi)

___
*[`src/Inciter/Partitioner.cpp` line 94 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRoDWhCUaQmdU9Xq3E:-NQRu3bWA6gQioHRZAku:b8npefy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/Inciter/Partitioner.cpp#L94)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This is very ugly and error-prone. I know you agree. Frankly , https://github.com/trilinos/Trilinos/issues/11197#issuecomment-1301325163 is not very convincing to me. I think they ought to be able hide this from client code. Their explanation sounds like a punt to me.
</blockquote></details>

I agree- I wasn't too happy with this either. I will put in a comment for this, to avoid future confusion/bugs.
___
*[`src/LoadBalance/ZoltanInterOp.hpp` line 35 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRp5c822gEMle11mxb:-NQRuTYH6nLRG-GoPpng:b259oia) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/LoadBalance/ZoltanInterOp.hpp#L35)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

That was also necessary? Why? Will that now use twice the size for integers? How did this work so far. I have tested this with 1.5B-cell meshes.
</blockquote></details>

For some reason TPetra (used by Zoltan) does not take `long`'s after Trilinos 13.0.1. These have to be `int`'s or `long long`'s. My first solution to this was using `int`'s, but that would have severely limited mesh sizes. `long long` will let us use large meshes, with the disadvantage that, this will now use twice the size. This can be investigated further as a separate issue if you'd like.
___
*[`src/NoWarning/kokkos_cr.hpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpQeG07VUSlClAfr8:-NQRwskqEKlJUK-XwYQL:b-fu571k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/NoWarning/kokkos_cr.hpp#L84)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

... and the size of this file tells you that this is including crufty code.
</blockquote></details>

I don't understand. Do you say that because it's a tiny file??
___
*[`tests/regression/inciter/compflow/Euler/VorticalFlow/CMakeLists.txt` line 255 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpnkk4sJDQuYd3hnK:-NQRtNWv5G158uXp0AbK:bnwxmdb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/57b193477ee28389fca39479120a8711f0bfdc32/tests/regression/inciter/compflow/Euler/VorticalFlow/CMakeLists.txt#L255)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why remove? They don't test anything new?
</blockquote></details>

These are repeat tests, since `vortical_flow_diagcg` already tests this. I think the naming confused us, and we added another test for diagcg, not remembering that there is one already tests diagcg. Hence removing these.

**Review by jbakosi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577)* status: 287 of 288 files reviewed, 4 unresolved discussions (waiting on @adityakpandare)

___
*[`src/NoWarning/kokkos_cr.hpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpQeG07VUSlClAfr8:-NQSDIglCcEigZQXHEsl:bc3xp0p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/NoWarning/kokkos_cr.hpp#L84)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I don't understand. Do you say that because it's a tiny file??
</blockquote></details>

No, the size is big, there are many warnings to ignore -> crufty code within Kokkos_Core.hpp that the compiler does not like. Not a nice behavior from a library. For example, you never get such warnings from STL, but that's the STL...

**Review by adityakpandare — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/577)* status: all files reviewed, 4 unresolved discussions (waiting on @jbakosi)

___
*[`src/NoWarning/kokkos_cr.hpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/577#-NQRpQeG07VUSlClAfr8:-NQSETZSDJX25ZggAD5Z:bdaadl9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ade484ec02054194ea5ea6eea16f154905cd7448/src/NoWarning/kokkos_cr.hpp#L84)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

No, the size is big, there are many warnings to ignore -> crufty code within Kokkos_Core.hpp that the compiler does not like. Not a nice behavior from a library. For example, you never get such warnings from STL, but that's the STL...
</blockquote></details>

Ah, I see. Yeah...

**Pull request merged**
