### PR TITLE
 First attempt to get a scalar output into exodus2 mesh via the DG class.

### PR DESCRIPTION
**Pull request by adityakpandare**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/203)

### CODE REVIEW

**Comment by jbakosi** [comment]
Thanks, this is a good first step. Let's not yet commit the stuff going into the `regression` folder.

I have thought a little bit more about how we can use the `PDE` classes with `DG`. Let's discuss that tomorrow.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[regression/inciter/linear_adv_dg.q, line 32 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sagx3g_3C-rcnvwju:-L4sagx3g_3C-rcnvwjv:b-h44712) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/regression/inciter/linear_adv_dg.q#L32)):*
> ```
>   end
> 
> end
> ```

Let's not commit this yet.

---

*[regression/inciter/unitcube_01_31k.exo, line 0 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4saZ87PdDb_gEv378n:-L4saZ87PdDb_gEv378o:b-ccd2gz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/regression/inciter/unitcube_01_31k.exo#L0)):*
Let's not commit this just yet, either.

---

*[src/Inciter/Discretization.h, line 146 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sbmpNxTP9Xkfren9Q:-L4sbmpNxTP9Xkfren9R:bm80jpu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/src/Inciter/Discretization.h#L146)):*
> ```objc
> 
>     //! Output mesh-based fields metadata to file
>     void writeMeta() const;
> ```

Shall we rename this to `writeNodeMeta()`?

---

*[src/Inciter/Discretization.h, line 158 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sc0roFHv7QYguGkxc:-L4sc0roFHv7QYguGkxd:b-f22jub) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/src/Inciter/Discretization.h#L158)):*
> ```objc
>     void writeSolution( const tk::RootMeshWriter& rmw,
>                         uint64_t it,
>                         const std::vector< std::vector< tk::real > >& u ) const;
> ```

And these overloads to `writeNodeSolution()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-:-L4sc6kcCH4ygw1LIkyh:b-eanu4p)*

**Comment by adityakpandare** [comment]
Alright. Got rid of those.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[regression/inciter/linear_adv_dg.q, line 32 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sagx3g_3C-rcnvwju:-L4shQifJ9FiUujBExe-:b2nhktp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/regression/inciter/linear_adv_dg.q#L32)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's not commit this yet.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-:-L4shJ236BTqB5HjC6jL:b-nvhqe3)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[regression/inciter/unitcube_01_31k.exo, line  at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4saZ87PdDb_gEv378n:-L4shTJ_iIS-3de5YNcs:b2nhktp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/regression/inciter/unitcube_01_31k.exo#L)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's not commit this just yet, either.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/Inciter/Discretization.h, line 146 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sbmpNxTP9Xkfren9Q:-L4sidaUEt3TgA4ZLDgw:b32w0x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/src/Inciter/Discretization.h#L146)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Shall we rename this to `writeNodeMeta()`?
</blockquote></details>

OK

---

*[src/Inciter/Discretization.h, line 158 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-L4sc0roFHv7QYguGkxc:-L4sic4fqXemV60ZsP-G:b32w0x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/059e4a7075c42e96b72d5e5407525e2c65191cd6/src/Inciter/Discretization.h#L158)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

And these overloads to `writeNodeSolution()`?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203)*

**Comment by jbakosi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/203#-:-L4slpue9khOIAmnIk0_:bnfp4nl)*

**Comment by jbakosi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/203#-:-L4soOdFGwKzzQIvWVl6:bnfp4nl)*

**Pull request merged**
