### PR TITLE
Eos variant implementation

### PR DESCRIPTION
**Pull request by adityakpandare**
Replacing the runtime-polymorphic EOS implementation to one using std::variant

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Nice work! I only have some minor suggestions. :lgtm: 

> Reviewed 101 of 101 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-:-NGNBdw2AfLbKh-PfpIw:b675w4h)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/EosVariant.hpp` line 3 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7UbyAb965KzJs6JR:-NGN7UbyAb965KzJs6JS:b-5rj7gz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L3)):*
> ```cpp
> // *****************************************************************************
> /*!
>   \file      src/PDE/EoS/EosVariant.hpp
> ```

I would probably just call this file `EOS.hpp`. That way the filename and the class defined are the same.
___
*[`src/PDE/EoS/EosVariant.hpp` line 31 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN8EwT1Kpj_0oFA88_:-NGN8EwT1Kpj_0oFA88a:bu2g6g5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L31)):*
> ```cpp
>     std::variant< StiffenedGas
>                 , JWL
>                 > material;
> ```

Maybe `m_material`, to make it consistent with the rest of the code? (Yeah: `Scheme` does not conform either.)
___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGN7dX5DRFavMxuqSIS:bw2jfo4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
> ```cpp
>     //!   EOS vector and is thus equivalent to mat_blk[imat].Fn(...).
>     template< typename Fn, typename... Args >
>     tk::real eosCall( Args&&... args ) const {
> ```

I think call-sites would be even more readable if this was named `get()`.
___
*[`src/PDE/EoS/EosVariant.cpp` line 33 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN8obO9_kG0DQigGVY:-NGN8obO9_kG0DQigGVZ:b-6tuoeb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.cpp#L33)):*
> ```cpp
>     // query input deck to get gamma, p_c, cv
>     tk::real g, ps, c_v;
>     if (eqtype == 0) {
> ```

It is hard to know what the magic number `0` means here. An enum could make it more readable.
___
*[`src/PDE/EoS/JWL.hpp` line 29 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN9VSh20OGRf0YnX0U:-NGN9VSh20OGRf0YnX0V:b-8657ze) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/JWL.hpp#L29)):*
> ```cpp
> 
> 
>     tk::real intEnergy( tk::real rho, tk::real pr ) const
> ```

Why are these definitions in the header file? This will be slower to compile. Plus the doxygen comment conforms to being in the cpp, as it looks like it should be. Same for the other member functions below.
___
*[`src/PDE/EoS/JWL.hpp` line 127 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN90lrCXqA_ZgC_e2G:-NGN90lrCXqA_ZgC_e2H:btyeicw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/JWL.hpp#L127)):*
> ```cpp
>     //  Default constructor
>     // *************************************************************************
>     JWL(){}
> ```

```
JWL() = default;
```
is better.
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 31 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN9Bvf-7khUw3t_KL_:-NGN9Bvf-7khUw3t_KLa:b-o4t8nc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/StiffenedGas.hpp#L31)):*
> ```cpp
>     //  Default constructor
>     // *************************************************************************
>     StiffenedGas(){}
> ```

```
StiffenedGas() = default;
```
is better.
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGNA2Be40tfqeIUjEjn:-NGNA2Be40tfqeIUjEjo:bdbdcbf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/StiffenedGas.hpp#L46)):*
> ```cpp
> 
>     tk::real density( tk::real pr,
>                       tk::real temp ) const
> ```

Should be in the cpp, together with its doxy and all other member functions.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 40 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGNAS4j930f-xpU5oab:-NGNAS4j930f-xpU5oac:bjd9rm1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/MultiMat/MiscMultiMatFns.cpp#L40)):*
> ```cpp
>   for (std::size_t k=0; k<nmat; ++k) {
>     auto mateos = matprop[matidxmap.get< tag::eosidx >()[k]].get<tag::eos>();
>     mat_blk.emplace_back(mateos, 1, system, k);
> ```

Ah! Here is that magic number! But what does it mean? ;-)
___
*[`src/PDE/MultiMat/Problem/BoxInitialization.hpp` line 63 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGNAwDD9QY9VnCh1i1k:-NGNAwDD9QY9VnCh1i1l:bak5py1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/MultiMat/Problem/BoxInitialization.hpp#L63)):*
> ```cpp
> 
>   // get material id in box (offset by 1, since input deck uses 1-based ids)
>   std::size_t boxmatid = b.template get< tag::materialid >() - 1;
> ```

Good idea to subtract it here instead.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGNKykIBU9hmv47_gja:bckys3o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I think call-sites would be even more readable if this was named `get()`.
</blockquote></details>

Agreed. However, I would like to explicitly have 'eos' in the name, so that programmers realize that this is an eos-call. What about `getEos()`?

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGNTK90Bz8NpRyG9z4i:b-rclt5b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Agreed. However, I would like to explicitly have 'eos' in the name, so that programmers realize that this is an eos-call. What about `getEos()`?
</blockquote></details>

EOS is also in the (mandatory) template argument (as a prefix for what you are requesting).

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGNWp7z1MOzbSl7o4SD:b-wv6nkm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

EOS is also in the (mandatory) template argument (as a prefix for what you are requesting).
</blockquote></details>

That's true about 'eos'. But also, I don't want it to seem like just an accessor to an already computed quantity. So how about `compute()` instead of `get()`?

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGNtNGG77ZIqUNG6iZS:b-lartc8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

That's true about 'eos'. But also, I don't want it to seem like just an accessor to an already computed quantity. So how about `compute()` instead of `get()`?
</blockquote></details>

I agree. I like `compute` even better than `get`. :+1:

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: all files reviewed, 8 unresolved discussions (waiting on @jbakosi)

___
*[`src/PDE/EoS/EosVariant.hpp` line 3 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7UbyAb965KzJs6JR:-NGNs--fA04NGgu24pxj:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L3)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I would probably just call this file `EOS.hpp`. That way the filename and the class defined are the same.
</blockquote></details>

Done.
___
*[`src/PDE/EoS/EosVariant.hpp` line 31 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN8EwT1Kpj_0oFA88_:-NGNs-fD8ek7wCALnXPe:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L31)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Maybe `m_material`, to make it consistent with the rest of the code? (Yeah: `Scheme` does not conform either.)
</blockquote></details>

Done.
___
*[`src/PDE/EoS/EosVariant.cpp` line 33 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN8obO9_kG0DQigGVY:-NGO3EWZ9tqsFuRcdKSp:b-qu6n94) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.cpp#L33)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

It is hard to know what the magic number `0` means here. An enum could make it more readable.
</blockquote></details>

Good point. Done.
___
*[`src/PDE/EoS/JWL.hpp` line 29 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN9VSh20OGRf0YnX0U:-NGO-W9f3SWoEn5eEA-T:boj1qgt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/JWL.hpp#L29)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why are these definitions in the header file? This will be slower to compile. Plus the doxygen comment conforms to being in the cpp, as it looks like it should be. Same for the other member functions below.
</blockquote></details>

Good catch. Done.
___
*[`src/PDE/EoS/JWL.hpp` line 127 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN90lrCXqA_ZgC_e2G:-NGO-_518fYOLNYhk8r4:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/JWL.hpp#L127)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

```
JWL() = default;
```
is better.
</blockquote></details>

Done.
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 31 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN9Bvf-7khUw3t_KL_:-NGNvWrc7cduLK7wvvpn:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/StiffenedGas.hpp#L31)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

```
StiffenedGas() = default;
```
is better.
</blockquote></details>

Done.
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGNA2Be40tfqeIUjEjn:-NGNvZjoA00MjxIQ482G:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/StiffenedGas.hpp#L46)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Should be in the cpp, together with its doxy and all other member functions.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 40 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGNAS4j930f-xpU5oab:-NGO37wx3jpO34dDhRov:b-dmpl73) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/MultiMat/MiscMultiMatFns.cpp#L40)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Ah! Here is that magic number! But what does it mean? ;-)
</blockquote></details>

Yep, changed this.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567)* status: 48 of 106 files reviewed, 8 unresolved discussions (waiting on @jbakosi)

___
*[`src/PDE/EoS/EosVariant.hpp` line 57 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-NGN7dX5DRFavMxuqSIR:-NGNw7zP9jbTTw1GsJ_r:b-g70hwh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/fa33e28e264575db84c36752ec51a1c58ce08ea2/src/PDE/EoS/EosVariant.hpp#L57)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I agree. I like `compute` even better than `get`. :+1: 
</blockquote></details>

Cool! Done.

**Review by adityakpandare — COMMENTED** [review]
@tannernielsen, this pull-request refactors the runtime-polymorphic EOS to a `std::variant` based implementation 

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/567#-:-NGSSkeH2Zl2mVKJED6U:b-r1bva9)* status: 24 of 106 files reviewed, 8 unresolved discussions (waiting on @jbakosi)

**Pull request merged**
