### PR TITLE
Only read side sets if DG, hide error handling

### PR DESCRIPTION
**Pull request by jbakosi**
This avoids reading the side set face connectivity unless `DG` is configured by the user. Also hide error handling inside reader, simplifying client code (tested by new unit test).

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/202)

### CODE REVIEW

**Comment by adityakpandare** [comment]
It seems that if DG is being used, there are 2 calls to readSidesetFaces(). Is that intentional?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Inciter/Transporter.C, line 221 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-L4peanexrDseinPk2LU:-L4peanexrDseinPk2LV:b2yfvhz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/713f4375e653a815eb48eb132806f1cc479b6025/src/Inciter/Transporter.C#L221)):*
> ```
>   if (scheme == ctr::SchemeType::DG) {
>     m_print.diag( "Reading side set faces" );
>     nbfac = er.readSidesetFaces( bface );
> ```

It seems that if DG is being used, there are 2 calls to readSidesetFaces(). Is that intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-:-L4pf9xavzD-oSsMg0Sz:b2yfvhz)*

**Comment by adityakpandare** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202)*

**Comment by jbakosi** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Inciter/Transporter.C, line 221 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/202#-L4peanexrDseinPk2LU:-L4pj7iyD12HepNCmFLT:b-fqn1ew) ([raw file](https://github.com/quinoacomputing/quinoa/blob/713f4375e653a815eb48eb132806f1cc479b6025/src/Inciter/Transporter.C#L221)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

It seems that if DG is being used, there are 2 calls to readSidesetFaces(). Is that intentional?
</blockquote></details>

Not at all! Nice catch. See a47d6d0f for a fix.
(This was a result of doing this originally on a different computer than on the one I usually develop and I did not move the changes correctly.) Thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/202)*

**Comment by jbakosi** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Inciter/Transporter.C, line 221 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/202#-L4peanexrDseinPk2LU:-L4pjeoVEvmqjbIQJ8fL:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/713f4375e653a815eb48eb132806f1cc479b6025/src/Inciter/Transporter.C#L221)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Not at all! Nice catch. See a47d6d0f for a fix.
(This was a result of doing this originally on a different computer than on the one I usually develop and I did not move the changes correctly.) Thanks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/202)*

**Comment by adityakpandare** [comment]
Cool. Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Inciter/Transporter.C, line 221 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-L4peanexrDseinPk2LU:-L4pn7NtjIIWqM-D3crn:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/713f4375e653a815eb48eb132806f1cc479b6025/src/Inciter/Transporter.C#L221)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-:-L4pn0s7-8ny8rguxEbr:b-mnr3k8)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Inciter/Transporter.C, line 221 at r1](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-L4peanexrDseinPk2LU:-L4pqnWSl1p9TpS0Vj_n:b-7iov7c) ([raw file](https://github.com/quinoacomputing/quinoa/blob/713f4375e653a815eb48eb132806f1cc479b6025/src/Inciter/Transporter.C#L221)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

OK. It seems I've to respond in certain keywords to approve the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202)*

**Comment by jbakosi** [comment]
Yeah, reviewable.io wants you to at least "acknowledge" my comments. Sounds fair. Thanks for the review. As always it is worth it. I will merge when green from travis.

**Comment by adityakpandare** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/202#-:-L4qJ2zMeAggADIx-xDo:bnfp4nl)*

**Pull request merged**
