### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by jbakosi**
Added some tests

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476)

### CODE REVIEW

**Review by adityakpandare — APPROVED** [review]
Is this for detecting which function/DAG causes quiescence?

> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476#-:-MUsheVVBpC2KvJnjVkO:b-96z30x)* status: 4 of 14 files reviewed, all discussions resolved

**Review by adityakpandare — APPROVED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476)* status: 5 of 14 files reviewed, all discussions resolved

**Review by jbakosi — COMMENTED** [review]
No. These are some tests added. I also added code (to DG) to test the ChareStateCollector, which can be used for debugging hard asynclogic problems by collecting detailed info what happens on each PE/chare. Also to run chare state collection as a test, see `-S` added to an existing regression test.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476#-:-MUsicY68AYqAe4dE-B5:b-6s2nj2)* status: 5 of 14 files reviewed, all discussions resolved

**Review by adityakpandare — APPROVED** [review]
Thanks for the explanation. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476#-:-MUst46qEYkUQSZaBioQ:b-fnnbtt)* status: 5 of 14 files reviewed, all discussions resolved

**Review by jbakosi — COMMENTED** [review]
Thanks for review. :-)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476#-:-MUstrmq8IBmK4trrXoY:b-jpm56l)* status: 5 of 14 files reviewed, all discussions resolved

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/476)* status: 4 of 13 files reviewed, all discussions resolved

**Pull request merged**
