### PR TITLE
Energy source term

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits implements an energy source term that propagates at a specified speed along the z-direction, inside the ic-box region. The time-step size is determined by taking this propagation speed into consideration, in addition to the speed of sound.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Nice work! Ready to go! Thanks a lot for adding this. Should we add a regression test, perhaps using a coarse version of the mesh you have been testing this with? If for nothing else, to have an example that exercises and shows how the input file is configured to use this type of setting the ICs.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-:-MKkawcy3m-7u9e-oVnu:b-4fnpuv)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 1527 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkaFMRAqE_qc2pnUVB:-MKkaFMRAqE_qc2pnUVC:bqnb7wf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/CGCompFlow.hpp#L1527)):*
> ```cpp
>         auto z1 = z0 + std::copysign(wFront, iv[0]);
>         tk::real s0(z0), s1(z1);
>         if (iv[0] < 0.0) {
> ```

If I'm not mistaken, this is what switches the direction if the velocity is negative in the input file. Can we add a comment that notes that?
___
*[src/PDE/CompFlow/Problem/UserDefined.cpp, line 74 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkasPLEhjNtYNl2cID:-MKkasPLEhjNtYNl2cIE:b-5fm7te) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/Problem/UserDefined.cpp#L74)):*
> ```cpp
>   if (bgpreic.size() > system && !bgpreic[system].empty()) {
>     u[4] = eos_totalenergy< eq >( system, u[0], u[1]/u[0], u[2]/u[0], u[3]/u[0],
>                                   bgpreic.at(system).at(0) );
> ```

Ugh! This was screwed up?

**Review by adityakpandare — COMMENTED** [review]
That's a good idea. Let me generate such a mesh and commit it. Let's merge https://github.com/quinoacomputing/quinoa/pull/452 in the meantime.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-:-MKkcJ7b-dqpHei0MNWG:b-o46ptr)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 1527 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkaFMRAqE_qc2pnUVB:-MKkc_8oBZJd52UycEhF:b-yu0q5e) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/CGCompFlow.hpp#L1527)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If I'm not mistaken, this is what switches the direction if the velocity is negative in the input file. Can we add a comment that notes that?
</blockquote></details>

Yes, I'll do that.
___
*[src/PDE/CompFlow/Problem/UserDefined.cpp, line 74 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkasPLEhjNtYNl2cID:-MKkczioEmqWPGkxXojw:b-7g567q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/Problem/UserDefined.cpp#L74)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Ugh! This was screwed up?
</blockquote></details>

Yeah, lucky catch!

**Review by jbakosi — APPROVED** [review]
Thanks.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-:-MKkdA6W0csFpN9XKSx2:b-ucfkn4)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 1527 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkaFMRAqE_qc2pnUVB:-MKkdBmEAWcC-Afu1uzT:b-ucfkn4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/CGCompFlow.hpp#L1527)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yes, I'll do that.
</blockquote></details>

Thanks.
___
*[src/PDE/CompFlow/Problem/UserDefined.cpp, line 74 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKkasPLEhjNtYNl2cID:-MKkdE0eCTPcsEsaV-UT:b-unnn23) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c60b18099b79450bbbc1272d4e94cc4c1ba5ef74/src/PDE/CompFlow/Problem/UserDefined.cpp#L74)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yeah, lucky catch!
</blockquote></details>

Nice! I remember having to fix a similar thing before, I guess I missed this one.

**Comment by jbakosi** [comment]
@adityakpandare please go ahead and merge this until I fix the issue with static builds on #452.

**Review by jbakosi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 249 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKpEBrX-mSJ5HmjO8hy:-MKpEBrYAM98aQSAbbD6:b-a09w3i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/293ea72ad6c9121558735f78b87a535aedc69319/src/PDE/CompFlow/CGCompFlow.hpp#L249)):*
> ```cpp
>           // background material. If such a box has to be initialized based
>           // on temperature, the Cv of the box will have to be specified
>           // separately. This is not currently supported.
> ```

Thanks for the comments.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 256 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-MKpEG9k8J76oWQKyYvj:-MKpEG9k8J76oWQKyYvk:b-8fx2u7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/293ea72ad6c9121558735f78b87a535aedc69319/src/PDE/CompFlow/CGCompFlow.hpp#L256)):*
> ```cpp
>           }
>           else Throw("Background pressure must be specified for box-IC with "
>                      "linear propagating source");
> ```

:+1:

**Review by jbakosi — APPROVED** [review]
Thanks for adding the test!

> Reviewed 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/453#-:-MKuxP1oEAMU_YCNDi55:b-hx7j1y)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
