### PR TITLE
Enable specifying BCs on meshes

### PR DESCRIPTION
**Pull request by jbakosi**
Usage:
```
    bc_dirichlet
      mesh 1 2 end
      sideset 1 2 3 4 5 6 end
    end
```
Client code:
```cpp
  const auto& bcmesh = g_inputdeck.get< tag::param, tag::compflow, tag::mesh >();
  if (bcmesh.get< tag::bcdir >()[ d->MeshId() ]) {
     Apply BCs ...
  }
```

See also `oversetFE::BC()`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks, @jbakosi. I have a couple of questions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-:-NeeWe9DAE2FYC5HFJqh:b2hvw4z)* status: all files reviewed, 3 unresolved discussions (waiting on @jbakosi)

___
*[`src/Control/Inciter/InputDeck/Grammar.hpp` line 333 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeVfqHD-fbv2vPsQY8:-NeeVfqHD-fbv2vPsQY9:bm696z4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Control/Inciter/InputDeck/Grammar.hpp#L333)):*
> ```cpp
>         bc.clear();
>         auto n = stack.template get< tag::couple, tag::transfer >().size() + 1;
>         bc.resize( n, 1 );
> ```

Does this set defaults for when a `mesh...end` block is not specified within a `bc...end` block?
___
*[`src/Inciter/OversetFE.cpp` line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeUrLm9QlsWrfazfF2:-NeeUrLm9QlsWrfazfF3:bv0udam) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Inciter/OversetFE.cpp#L162)):*
> ```cpp
>                    m_tp, m_dtp, d->Coord(), d->Lid(), m_bnode,
>                    /* increment = */ false );
>   if (steady) for (auto& deltat : m_dtp) deltat /= rkcoef[m_stage];
> ```

Why was the above code necessary to be repeated (it is already in `BC()`)?
___
*[`src/Inciter/OversetFE.cpp` line 777 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeV0yx5Q8n6upuuVpa:-NeeV0yx5Q8n6upuuVpb:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Inciter/OversetFE.cpp#L777)):*
> ```cpp
> 
>   // Query and match user-specified Dirichlet boundary conditions to side sets
>   if (bcmesh.get< tag::bcdir >()[ d->MeshId() ]) {
> ```

Nice!
___
*[`tests/regression/inciter/compflow/Euler/Mesh2Mesh/m2m.q` line 44 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeV38u13LBET85hj0X:-NeeV38u13LBET85hj0Y:bxmpdfu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/tests/regression/inciter/compflow/Euler/Mesh2Mesh/m2m.q#L44)):*
> ```q
>     end
>     bc_dirichlet
>       mesh 1 end
> ```

What would happen if there was a bc_dirichlet (or any other bc-type) block, without a `mesh ... end` block within? Are there defaults that set it to mesh 1?

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594)* status: all files reviewed, 3 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Control/Inciter/InputDeck/Grammar.hpp` line 333 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeVfqHD-fbv2vPsQY8:-Neg5oil1mHLC41R-jSP:b-kcjk7j) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Control/Inciter/InputDeck/Grammar.hpp#L333)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Does this set defaults for when a `mesh...end` block is not specified within a `bc...end` block?
</blockquote></details>

Yes:
```
bc.resize( n, 1 );
if (b.empty()) return;
```
___
*[`src/Inciter/OversetFE.cpp` line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeUrLm9QlsWrfazfF2:-Neg6H-W0hZaUKhJtSg-:b-soe84h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Inciter/OversetFE.cpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why was the above code necessary to be repeated (it is already in `BC()`)?
</blockquote></details>

Ah, I see it now. Why did you move it to getBCNodes() to be only called from the ctor? That piece of code evaluates Dirichlet BCs at a given time. It is wrong if not called from BC() in every timestep.
___
*[`tests/regression/inciter/compflow/Euler/Mesh2Mesh/m2m.q` line 44 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeV38u13LBET85hj0X:-Neg6yHQAsXY8WosrrXM:bl8k5o4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/tests/regression/inciter/compflow/Euler/Mesh2Mesh/m2m.q#L44)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

What would happen if there was a bc_dirichlet (or any other bc-type) block, without a `mesh ... end` block within? Are there defaults that set it to mesh 1?
</blockquote></details>

Yes, see above.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[`src/Control/Inciter/InputDeck/Grammar.hpp` line 333 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeVfqHD-fbv2vPsQY8:-NehejLDDAYGyy3ePWXn:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Control/Inciter/InputDeck/Grammar.hpp#L333)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yes:
```
bc.resize( n, 1 );
if (b.empty()) return;
```
</blockquote></details>

Thanks!
___
*[`src/Inciter/OversetFE.cpp` line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeUrLm9QlsWrfazfF2:-Nehen2s2sHqG5BNN4WP:b2jmgu3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Inciter/OversetFE.cpp#L162)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Ah, I see it now. Why did you move it to getBCNodes() to be only called from the ctor? That piece of code evaluates Dirichlet BCs at a given time. It is wrong if not called from BC() in every timestep.
</blockquote></details>

The above code *is* in `BC()` so that it is called every time step stage (see develop). It wasn't in `getBCNodes()`. Hence I was not sure why it was copied to `getBCNodes()` in this set of commits...

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-:-Nej9cZ-5BUe5C97id3d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[`src/Inciter/OversetFE.cpp` line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NeeUrLm9QlsWrfazfF2:-Nej9LS00i475VaO-5JN:b1b7bz3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/02f282a11ed7a2e3c721383a7203b499c0d11c88/src/Inciter/OversetFE.cpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The above code *is* in `BC()` so that it is called every time step stage (see develop). It wasn't in `getBCNodes()`. Hence I was not sure why it was copied to `getBCNodes()` in this set of commits...
</blockquote></details>

Fixed this.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
@jbakosi, asynclogic tests on OversetFE fail for this branch. They fail because OversetFE attempts to index into `g_inputdeck.get< tag::param, tag::compflow, tag::mesh >()` which is likely not allocated for `tag::transport`; and our asynclogic tests use transport. Could you take a look at this?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-:-NejO0v38JQIMA0XYOXx:b-m3gml8)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[`src/Inciter/OversetFE.cpp` line 908 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/594#-NejOcr_By89vFPJKfrx:-NejOcr_By89vFPJKfry:b-8eocje) ([raw file](https://github.com/quinoacomputing/quinoa/blob/023b009b4ea32a6fcf9da68253305f58c3a25dbb/src/Inciter/OversetFE.cpp#L908)):*
> ```cpp
> 
>   // Query and match user-specified Dirichlet boundary conditions to side sets
>   if (bcmesh.get< tag::bcdir >()[ d->MeshId() ]) {
> ```

The above access attempt causes a seg-fault in the asynclogic tests (which are for transport).

**Pull request merged**
