### PR TITLE
IC box initialization for multimat

### PR DESCRIPTION
**Pull request by adityakpandare**
Added the ic-box initialization for multimat, which allows setting up problems with simple box-like initial conditions easily thru the control file.
Got rid of triple point and gas impact problem classes since these can now be set up using ic boxes and user-defined problem class.
Added documentation (example set up) on how ic boxes are used in multimat.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
Looks great! Excellent work! I like the large chunk of code removed due to removing `Problem`-related code. Couple of minor suggestions, otherwise looks good.

> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-:-MZDlpZ3CXoZn5N5Rvat:b-o96t36)* status: all files reviewed, 4 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[doc/examples/inciter/gasimpact_4mat.dox, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDbaUY-bV1jGfayQtx:-MZDbaUZ-0pnCDkCl23z:b-1svpah) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L46)):*
> ```
> 
>     intsharp 1
>     intsharp_param 2.5
> ```

I think that it would be a little more useful for the casual browser to put in some more simple comments explaining what some of the input file commands and config options mean. Just like the below section for the `material ... end` block.
___
*[doc/examples/inciter/gasimpact_4mat.dox, line 115 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcBMCEl9XLm0MKH0F:-MZDcBMCEl9XLm0MKH0G:bx8owf2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L115)):*
> ```
>       x-velocity "x-velocity_numerical"
>       y-velocity "y-velocity_numerical"
>       z-velocity "z-velocity_numerical"
> ```

Since we don't have analytical solution for this problem, you could simply leave out the output variable aliases, those in quotes, to make the input file simpler.
___
*[src/Control/Keywords.hpp, line 2642 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDdEND0W2WmhS-99NP:-MZDdEND0W2WmhS-99NQ:b491max) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/src/Control/Keywords.hpp#L2642)):*
> ```cpp
>   static std::string shortDescription() { return "Specify material id"; }
>   static std::string longDescription() { return
>     R"(This keyword is used to configure the material within a box.)";
> ```

Maybe:

_the material id within a box as part of the initialization_

You can make this as long as you want. ;-)
___
*[src/Control/Keywords.hpp, line 2647 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcsn4Cqr41NU8uDNg:-MZDcsn4Cqr41NU8uDNh:brnro1p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/src/Control/Keywords.hpp#L2647)):*
> ```cpp
>     using type = std::size_t;
>     static constexpr type lower = 1;
>     static std::string description() { return "uint"; }
> ```

Let's be kind to those users who are not programmers and spell out what `uint` means, since this is part of the help on the executable command line when you want more info on this keyword.

**Review by adityakpandare — COMMENTED** [review]
Thanks for your help! I've made the changes you suggested.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-:-MZDppnN6L00JIl3y7dp:b-jog8zw)* status: all files reviewed, 4 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[doc/examples/inciter/gasimpact_4mat.dox, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDbaUY-bV1jGfayQtx:-MZDpE6gAnrPskqc23XO:b-qu6n94) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L46)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I think that it would be a little more useful for the casual browser to put in some more simple comments explaining what some of the input file commands and config options mean. Just like the below section for the `material ... end` block.
</blockquote></details>

Good point. Done.
___
*[doc/examples/inciter/gasimpact_4mat.dox, line 115 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcBMCEl9XLm0MKH0F:-MZDpC3j1qOP5Y-cFKmH:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L115)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Since we don't have analytical solution for this problem, you could simply leave out the output variable aliases, those in quotes, to make the input file simpler.
</blockquote></details>

Done.
___
*[src/Control/Keywords.hpp, line 2642 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDdEND0W2WmhS-99NP:-MZDpWDV3fKH4S_DVABW:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/src/Control/Keywords.hpp#L2642)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Maybe:

_the material id within a box as part of the initialization_

You can make this as long as you want. ;-)
</blockquote></details>

Done.
___
*[src/Control/Keywords.hpp, line 2647 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcsn4Cqr41NU8uDNg:-MZDpXGHD_yrkc4WzcEs:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/src/Control/Keywords.hpp#L2647)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's be kind to those users who are not programmers and spell out what `uint` means, since this is part of the help on the executable command line when you want more info on this keyword.
</blockquote></details>

Done.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488)* status: 28 of 30 files reviewed, 4 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[doc/examples/inciter/gasimpact_4mat.dox, line 11 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDsosmEQxrxqSgtXIh:-MZDsosmEQxrxqSgtXIi:bajk9xd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/198e127ce20bf6e9188dfe57e3e4106ae61faceb/doc/examples/inciter/gasimpact_4mat.dox#L11)):*
> ```
> initial conditions, and symmetric boundary conditions on all domain boundaries.
> For further details about the numerical method see @ref papers_inciter
> "Pandare et al. (Comp. Fluids 2021)"
> ```

Made these changes so that the reader can find the relevant paper from the publications page.

**Review by jbakosi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-:-MZE-eHqB5WvVcbIXdk-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

___
*[doc/examples/inciter/gasimpact_4mat.dox, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDbaUY-bV1jGfayQtx:-MZE-Hi65r6Ns42pznhH:bcardoc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L46)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Good point. Done.
</blockquote></details>

Yeah, anything that helps users and fellow researchers who would want to reproduce the work and take it to their own direction.
___
*[doc/examples/inciter/gasimpact_4mat.dox, line 115 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcBMCEl9XLm0MKH0F:-MZE-VZSBzSV1SItaMvx:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/doc/examples/inciter/gasimpact_4mat.dox#L115)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
___
*[doc/examples/inciter/gasimpact_4mat.dox, line 11 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDsosmEQxrxqSgtXIh:-MZE-CtABBtZVxdORCCC:btojbfd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/198e127ce20bf6e9188dfe57e3e4106ae61faceb/doc/examples/inciter/gasimpact_4mat.dox#L11)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Made these changes so that the reader can find the relevant paper from the publications page.
</blockquote></details>

Great!
___
*[src/Control/Keywords.hpp, line 2647 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/488#-MZDcsn4Cqr41NU8uDNg:-MZE-_WuBTuJRSg6Ipdd:b-ucfkn4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/567f7dcbc21fb7f750003ab609d406036c5d75e3/src/Control/Keywords.hpp#L2647)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.

**Review by WeizhaoLi2018 — APPROVED** [review]
> Reviewed 21 of 30 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/488)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
