### PR TITLE
System3

### PR DESCRIPTION
**Pull request by jbakosi**
Following #591 and branch 'system2'. This removes systems from inputdeck. Let me know if you find something I missed.

There should be only one test failing, 'inciter:multimat_solidfluid_adv_p0p1_pe4', which I would need some help with regarding error handling of material properties.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/592)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Wow! What a relief to see those vectors go away! I have one major question below.

> Reviewed 56 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-:-NdgfXaKAQmEZtKa9XMQ:b10hz4i)* status: 56 of 58 files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[`src/Control/Inciter/Types.hpp` line 516 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-NdgbjTM6CbTVNCRq_Hg:-NdgbjTM6CbTVNCRq_Hh:by00f6k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9534c1169d3cdec6ba82196f4bd951418381e5d9/src/Control/Inciter/Types.hpp#L516)):*
> ```cpp
>     //! Flux function type
>   , tag::flux,          std::vector< FluxType >
> > >;
> ```

Such a relief that this is going away!
___
*[`src/Control/Inciter/InputDeck/Grammar.hpp` line 681 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-NdgdfYd80fDyoOupbtM:-NdgdfYd80fDyoOupbtN:b-z36y7g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/df95c55951f0078c28160ef585264312c36802ed/src/Control/Inciter/InputDeck/Grammar.hpp#L681)):*
> ```cpp
>       if (intsharp_p.empty() || intsharp_p.size() != neq.get< eq >())
>         intsharp_p.push_back( 1.8 );
> ```

Is there a way to keep these above default settings? These are needed since our users do not know (and don't need to either) about these settings.
___
*[`tests/regression/inciter/multimat/EnergyPill/energy_pill_fv.q` line 23 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-Ndgdw2k4WdbsJHstqly:-Ndgdw2k4WdbsJHstqlz:b-qko379) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9534c1169d3cdec6ba82196f4bd951418381e5d9/tests/regression/inciter/multimat/EnergyPill/energy_pill_fv.q#L23)):*
> ```q
>     physics energy_pill
>     prelax 1
>     prelax_timescale 0.25
> ```

This is a good example about why the defaults are needed. Users do not necessarily know about what this time-scale is, and that `prelax` is even needed. This control file intentionally left out these parameters, so that inciter defaults to the correct values.

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/592)* status: 51 of 58 files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Control/Inciter/InputDeck/Grammar.hpp` line 681 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-NdgdfYd80fDyoOupbtM:-NdjRxIy0cPOJP0hVCjK:b-51vt3m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/df95c55951f0078c28160ef585264312c36802ed/src/Control/Inciter/InputDeck/Grammar.hpp#L681)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is there a way to keep these above default settings? These are needed since our users do not know (and don't need to either) about these settings.
</blockquote></details>

Sure, this can still be done, but now simpler. See 81268a5e5.
___
*[`tests/regression/inciter/multimat/EnergyPill/energy_pill_fv.q` line 23 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-Ndgdw2k4WdbsJHstqly:-NdjSDuZE6ISGxuusTWB:bl8k5o4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9534c1169d3cdec6ba82196f4bd951418381e5d9/tests/regression/inciter/multimat/EnergyPill/energy_pill_fv.q#L23)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is a good example about why the defaults are needed. Users do not necessarily know about what this time-scale is, and that `prelax` is even needed. This control file intentionally left out these parameters, so that inciter defaults to the correct values.
</blockquote></details>

Yes, see above.

**Review by adityakpandare — APPROVED** [review]
:lgtm: I'm still making a couple of changes in this one for the solidfluid test.

> Reviewed 1 of 58 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/592#-:-Ndke_peEVoctaAX6bIR:b-lfqry4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Review by adityakpandare — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/592)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Pull request merged**
