### PR TITLE
single-material test in multi-material solver

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
This PR allows for single-material test for multi-material solver.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543)

### CODE REVIEW

**Review by WeizhaoLi2018 — COMMENTED** [review]
This PR only allows for single-material test in solver part. When it comes to specific testcase, we need to make sure the initialization is fit in the single-material case.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-:-MySxW0W2lNPh6JH0l89:b-rm7670)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543)* status: all files reviewed, 1 unresolved discussion (waiting on @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 1072 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MygusSx5AN4fhaJuogQ:-MygusSx5AN4fhaJuogR:bd7o9ge) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d97c8e65dde30a24cebfa3dba6877e3f0cd38fa0/src/PDE/Reconstruction.cpp#L1072)):*
> ```cpp
> 
>   // physical constraints
>   if (nmat > nmat) {
> ```

I don't understand this change. The previous condition `nmat > 1` looks correct to me. Besides, this condition will never be true, so that code inside the if-test will never run.

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/Reconstruction.cpp, line 1072 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MygusSx5AN4fhaJuogQ:-MyhPd4M4EBJVFtw1CtJ:bwnfv93) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d97c8e65dde30a24cebfa3dba6877e3f0cd38fa0/src/PDE/Reconstruction.cpp#L1072)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I don't understand this change. The previous condition `nmat > 1` looks correct to me. Besides, this condition will never be true, so that code inside the if-test will never run.
</blockquote></details>

I put the wrong condition here. Just fixed this.
Thanks for pointing out!

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/PDE/Reconstruction.cpp, line 1072 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MygusSx5AN4fhaJuogQ:-MyhSFShEMqYayIJEvY2:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d97c8e65dde30a24cebfa3dba6877e3f0cd38fa0/src/PDE/Reconstruction.cpp#L1072)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I put the wrong condition here. Just fixed this.
Thanks for pointing out!
</blockquote></details>

Thanks!
___
*[src/PDE/MultiMat/Problem/ShockDensityWave.cpp, line 50 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MyhRwcl761UBhLjijP6:-MyhRwcl761UBhLjijP7:b-ubifwk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/53300c250a6621fe6dc213e69ce233987fa6d80c/src/PDE/MultiMat/Problem/ShockDensityWave.cpp#L50)):*
> ```cpp
> {
>   // see also Control/Inciter/InputDeck/Grammar.hpp
>   //Assert( ncomp == 9, "Number of scalar components must be 9" );
> ```

We should keep this assert, with `ncomp == 3*nmat+3`, and a generic comment "Incorrect number of components in system".
___
*[src/PDE/MultiMat/Problem/ShockDensityWave.cpp, line 69 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MyhRV4pBn_onw_iujuH:-MyhRV4pBn_onw_iujuI:bjgp3yr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/53300c250a6621fe6dc213e69ce233987fa6d80c/src/PDE/MultiMat/Problem/ShockDensityWave.cpp#L69)):*
> ```cpp
>   } else if(nmat == 1){           // If this is a single-material test
>       s[volfracIdx(nmat, 0)] = 1.0;
>   }
> ```

Nice! This way we can run this test using nmat 1 or 2, based on what the user specifies in the control file. Can we have a final `else` branch that throws an error (use `Throw()`) saying that this test is not configured for nmat > 2.

**Review by WeizhaoLi2018 — COMMENTED** [review]
Just tested this on ARC and it could give us 1-material result by just giving nmat = 1 in the control file.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-:-MyhVHCJ4Iu2bbd49UrF:bkph0hh)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/MultiMat/Problem/ShockDensityWave.cpp, line 50 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MyhRwcl761UBhLjijP6:-MyhVlHf-9Ytn_aOB9ca:b-vx534o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/53300c250a6621fe6dc213e69ce233987fa6d80c/src/PDE/MultiMat/Problem/ShockDensityWave.cpp#L50)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We should keep this assert, with `ncomp == 3*nmat+3`, and a generic comment "Incorrect number of components in system".
</blockquote></details>

Done!
Thank you!
___
*[src/PDE/MultiMat/Problem/ShockDensityWave.cpp, line 69 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-MyhRV4pBn_onw_iujuH:-MyhVoHc2FaCMgp0eXjb:b-vx534o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/53300c250a6621fe6dc213e69ce233987fa6d80c/src/PDE/MultiMat/Problem/ShockDensityWave.cpp#L69)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice! This way we can run this test using nmat 1 or 2, based on what the user specifies in the control file. Can we have a final `else` branch that throws an error (use `Throw()`) saying that this test is not configured for nmat > 2.
</blockquote></details>

Done!
Thank you!

**Review by adityakpandare — APPROVED** [review]
Thanks @weizhaoli2018! :lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-:-MyhW1675kx1d4Ie6gZv:b3tuaie)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by adityakpandare — APPROVED** [review]
All tests passing on my side. This is good to merge.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/543#-:-MyhmwKSBHIqKlQBIwDY:b-uu7p7q)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Pull request merged**
