### PR TITLE
Update roadmap

### PR DESCRIPTION
**Pull request by jbakosi**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)

### CODE REVIEW

**Review by adityakpandare — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adityakpandare — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[doc/pages/roadmap.dox, line 92 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/466#-MQmgsym2qukCJouN_iv:-MQmgsym2qukCJouN_iw:b-5327q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/960319a0b87254d29fa0f0103398e5389881c4df/doc/pages/roadmap.dox#L92)):*
> ```
> We have two kinds of CG algorithms implemented for unstructured 3D meshes: (1)
> `DiagCG`, is a node-centered method, combining flux-corrected transport with
> Lax-Wendroff time stepping, and (2) `ALECG`, is also a node-centered method,
> ```

Should we mention that ALECG is equivalent to a node-centered finite volume used commonly in industry?

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[doc/pages/roadmap.dox, line 92 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/466#-MQmgsym2qukCJouN_iv:-MQmia6jAjEFvm4KT1B-:bocesu7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/960319a0b87254d29fa0f0103398e5389881c4df/doc/pages/roadmap.dox#L92)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Should we mention that ALECG is equivalent to a node-centered finite volume used commonly in industry?
</blockquote></details>

Yeah, good idea. See 853c7b7fc.

**Review by adityakpandare — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[doc/pages/roadmap.dox, line 92 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/466#-MQmgsym2qukCJouN_iv:-MQmkpVu7d0gndS_7xos:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/960319a0b87254d29fa0f0103398e5389881c4df/doc/pages/roadmap.dox#L92)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, good idea. See 853c7b7fc.
</blockquote></details>

Thanks!

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466#-:-MQmktTM-5qVyZrAwSI5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/466)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[doc/pages/roadmap.dox, line 92 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/466#-MQmgsym2qukCJouN_iv:-MQmlBcN9avq_p3-wkKC:b-h5rv17) ([raw file](https://github.com/quinoacomputing/quinoa/blob/960319a0b87254d29fa0f0103398e5389881c4df/doc/pages/roadmap.dox#L92)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Thanks for the suggestion!

**Pull request merged**
