### PR TITLE
Updates to doc

### PR DESCRIPTION
**Pull request by jbakosi**
There are some larger updates to the following pages:
*  `doc/pages/inciter_newscheme.dox                                        |  408 ++++++++++++++++++++-------------------------`
* `doc/pages/inciter_performance.dox                                      |  145 ++++++++++++++--`
* `doc/pages/papers.dox                                                   |   22 ++-`

 You can browse the doc rendered from this branch, via VPN and portal, at http://euler.lanl.gov/doc/html.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/504)

### CODE REVIEW

**Comment by jbakosi** [comment]
Also added a new example page on F16 with ALECG in https://github.com/quinoacomputing/quinoa/pull/504/commits/c043296550ff318811bfde23b7ab008cbf0ef9e5.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Looks good. Just a few questions and comments.

> Reviewed 72 of 82 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-:-Mf-sgsa1pW0JfnZglBH:bjfuvb7)* status: 72 of 82 files reviewed, 10 unresolved discussions (waiting on @jbakosi)

___
*[doc/examples/inciter/f16.dox, line 5 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-pzXyAB91UBSgBxNZ:-Mf-pzXyAB91UBSgBxN_:bp36o87) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L5)):*
> ```
> 
> This example runs the @ref inciter_alecg algorithm marching the solution to
> steady state. The problem is initialized with a free-stream Mach number of
> ```

"...solution to steady state, *using a local time stepping procedure*" ?
___
*[doc/examples/inciter/f16.dox, line 26 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qFqx5EWWAl1QTyES:-Mf-qFqx5EWWAl1QTyET:brwqos) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L26)):*
> ```
> 
>   #nstep 1     # Max number of time steps
>   #term 10.0   # Max physical time, s
> ```

Should we remove the above commented lines in the included input file to avoid confusion?
___
*[doc/examples/inciter/f16.dox, line 35 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qNeI9XtqPINuHgJA:-Mf-qNeJ6Z6SYuyntCfw:b8eka3s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L35)):*
> ```
> 
>   scheme alecg
>   #operator_reorder true
> ```

This too?
___
*[doc/examples/inciter/f16.dox, line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qQXz9J2HDDTlZK0f:-Mf-qQXz9J2HDDTlZK0g:bj3kl3y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L76)):*
> ```
>   #  t0ref true
>   #  initial uniform
>   #end
> ```

Let's remove this too.
___
*[doc/pages/inciter_newscheme.dox, line 442 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qqbb4oCubwhEYH-Q:-Mf-qqbb4oCubwhEYH-R:b-fh2id9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L442)):*
> ```
> chares must finish resizing and/or constructing their communication maps before
> their `setup()` member function can be invoked. This is because `setup()` is
> assumed  to be allowed to start using those communication maps that have been
> ```

Why "*assumed to be* allowed to start"?
___
*[doc/pages/inciter_newscheme.dox, line 449 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qyq36vW9t7udIMGY:-Mf-qyq36vW9t7udIMGZ:b-p099zf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L449)):*
> ```
> @snippet Inciter/ALECG.cpp setup
> 
> In the ALECG::setup() code snippet above the various setup setup are started. What they are may change as we develop this further, so we don't go into detail here, the current listing is above. 
> ```

"various setup *steps*"?
___
*[doc/pages/inciter_newscheme.dox, line 464 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-rA2E2KSZ-_hw-ZCN:-Mf-rA2E2KSZ-_hw-ZCO:b-nu4ibc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L464)):*
> ```
> The above code snippet shows a `for` loop that calls the the `dt()` member
> function of all types of PDEs configured by the user and finds the minimum size
> of the time step to be taken next.
> ```

"finds the minimum size of the *next time step*"?
___
*[doc/pages/inciter_newscheme.dox, line 479 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-rOxc7VLhK1znFzVa:-Mf-rOxc7VLhK1znFzVb:b-gfvg4i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L479)):*
> ```
> When both the own and communicated contributions are complete on a chare, the
> runtime system continues as described in the DAG in alecg.ci. ALECG::solve(),
> first combines the own and received contributions then advances all equations.
> ```

"advances all equations *using a Runge-Kutta method*"?
___
*[doc/pages/inciter_newscheme.dox, line 542 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-s2Lk5Lyybhgu15dN:-Mf-s2Lk5Lyybhgu15dO:b-5ox8uh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L542)):*
> ```
> LHS, it would change if the mesh moved or the topology changed.) These two
> tasks are independent and so they happen on indepent execution threads. Both
> threads of execution progresses through a series of steps also involving
> ```

"both threads of execution *progress*"
___
*[doc/pages/inciter_newscheme.dox, line 565 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-sHvH24yFLuMa8QDo:-Mf-sHvH24yFLuMa8QDp:b-ixyus6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L565)):*
> ```
> @snippet Inciter/ALECG.cpp stage
> 
> If it is the last one, we optionally output results to file then continue to
> ```

"If it is the last *Runge-Kutta stage*"? because it's a new section, and it's better to spell out what "last one" is

**Review by jbakosi — COMMENTED** [review]
Thanks for extra pair of eyes!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-:-Mf3rBLHCzD0TSZeBSrP:b4dn0gz)* status: 72 of 82 files reviewed, 6 unresolved discussions (waiting on @adityakpandare)

___
*[doc/examples/inciter/f16.dox, line 5 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-pzXyAB91UBSgBxNZ:-Mf3orSl8ImkgRp-SXXk:b-80tlqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L5)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"...solution to steady state, *using a local time stepping procedure*" ?
</blockquote></details>

Sure.
___
*[doc/examples/inciter/f16.dox, line 26 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qFqx5EWWAl1QTyES:-Mf3ozyc17oQDdsvZUxy:b-80tlqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L26)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Should we remove the above commented lines in the included input file to avoid confusion?
</blockquote></details>

Sure.
___
*[doc/examples/inciter/f16.dox, line 35 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qNeI9XtqPINuHgJA:-Mf3p3hXCQXkscooSeSU:b-80tlqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L35)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This too?
</blockquote></details>

Sure.
___
*[doc/examples/inciter/f16.dox, line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qQXz9J2HDDTlZK0f:-Mf3p4yoAZIvDiVxFDGW:bd6vdqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/examples/inciter/f16.dox#L76)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's remove this too.
</blockquote></details>

Sure, simplicity is good.
___
*[doc/pages/inciter_newscheme.dox, line 442 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qqbb4oCubwhEYH-Q:-Mf3pYlp08RsbeQt-djQ:b-s0o9yh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L442)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why "*assumed to be* allowed to start"?
</blockquote></details>

I don't remember. The point is that `setup()` is allowed to start using the commaps. I guess this is the same: _This is because `setup()` is allowed to start using those communication maps that have been constructed before calling `setup()`._
___
*[doc/pages/inciter_newscheme.dox, line 449 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-qyq36vW9t7udIMGY:-Mf3qQwC1RzMm3HNES0p:b-teu7hm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L449)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"various setup *steps*"?
</blockquote></details>

Yeah...
___
*[doc/pages/inciter_newscheme.dox, line 464 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-rA2E2KSZ-_hw-ZCN:-Mf3qaFt9EDYcj53xM9W:b-7xtei2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L464)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"finds the minimum size of the *next time step*"?
</blockquote></details>

Yeah.
___
*[doc/pages/inciter_newscheme.dox, line 479 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-rOxc7VLhK1znFzVa:-Mf3qip40-XZAT7SlriJ:b-80tlqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L479)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"advances all equations *using a Runge-Kutta method*"?
</blockquote></details>

Sure.
___
*[doc/pages/inciter_newscheme.dox, line 542 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-s2Lk5Lyybhgu15dN:-Mf3qpDb9VpELEGec6B1:bo6apac) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L542)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"both threads of execution *progress*"
</blockquote></details>

Indeed.
___
*[doc/pages/inciter_newscheme.dox, line 565 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-Mf-sHvH24yFLuMa8QDo:-Mf3r5cm7BwysQAYjb5e:bb77ufg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c043296550ff318811bfde23b7ab008cbf0ef9e5/doc/pages/inciter_newscheme.dox#L565)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

"If it is the last *Runge-Kutta stage*"? because it's a new section, and it's better to spell out what "last one" is
</blockquote></details>

Yes.

**Review by adityakpandare — APPROVED** [review]
Sure! :lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/504#-:-Mf3z7jU6Rzzphqo13oK:b-paoxcr)* status: 72 of 82 files reviewed, all discussions resolved (waiting on @jbakosi)

**Pull request merged**
