### PR TITLE
doc dg

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
This PR includes the doc pages of dg solvers for single material flow.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/467)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
Thanks for putting this in, @weizhaoli2018 !

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/467#-:-MQmkH0P38-XLtkMPb92:b-engewn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — APPROVED** [review]
Great! Thanks @weizhaoli2018!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/467#-:-MQml1UG2rjJxPfJEfCj:b-fu3l4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by WeizhaoLi2018 — COMMENTED** [review]
Thanks for the quick review. I will merge this once it passes the Azure.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/467#-:-MQmlFWJBGa4rH7Ia2cI:bj4nco1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jbakosi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/467)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
