### PR TITLE
Update to PEGTL 2.0

### PR DESCRIPTION
**Pull request by jbakosi**
In conjunction with https://github.com/quinoacomputing/quinoa-tpl/pull/10.

May also require updates to the docker images: ubuntu, ubuntu-verde, and gentoo.

### CODE REVIEW

**Comment by jbakosi** [comment]
@junghans: The gentoo docker image needs a rebuild (I believe without any change to the docker config file), but I'm having problems with rsync proxy at this time:
```
!!! getaddrinfo failed for 'rsync.gentoo.org': [Errno -3] Temporary failure in name resolution
```

**Comment by jbakosi** [comment]
Gentoo installs exodus but does it install exodiff? See https://travis-ci.org/quinoacomputing/quinoa/jobs/236363849

**Comment by junghans** [comment]
I guess that is due to gentoo/sci@a8ec95d3c4789c41491d775365b9a4cdbb6bf511!

**Comment by junghans** [comment]
Gentoo builds, alpine docker image needs an update though.

**Comment by jbakosi** [comment]
I think alpine will require a merge to master on the tpl and the cmake repos because it uses master.

**Pull request closed without merging**
