### PR TITLE
Use rho0

### PR DESCRIPTION
**Pull request by airaudofacundo**
Printed the density constrained rho/(rho0*det(g)) as a field output to verify that it is near 1.
Cleaned up SolidTerms so only the density constrained term is present.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/616)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
A couple of comments, but otherwise looks good.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-:-O1OC6Am6Sl2YRPaCJmi:bc9e0g5)* status: all files reviewed, 5 unresolved discussions (waiting on @airaudofacundo)

___
*[`src/Inciter/DG.cpp` line 1790 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1O4mULBS-Xljv43T84:-O1O4mULBS-Xljv43T85:b-hhdtga) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/Inciter/DG.cpp#L1790)):*
> ```cpp
>   elemfieldnames.push_back( "shock_marker" );
> 
>   elemfieldnames.push_back( "densityConstr" );
> ```

This should be within an if-test that tests if `densityConstr.size() > 0`. Otherwise, for other eqs, like compflow, there is nothing in densityConstr, but it has a name, and that will result in errors from Paraview.
___
*[`src/PDE/CompFlow/DGCompFlow.hpp` line 231 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OAuG_3jewtbihSaRr:-O1OAuG_3jewtbihSaRs:bu3y4k4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/CompFlow/DGCompFlow.hpp#L231)):*
> ```cpp
>     //! \param[in] nelem Number of elements
>     //! \param[in] unk Array of unknowns
>     //! \param[in] rho0mat List of initial densities
> ```

Let's comment the above arg-documentation since they are not used.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 351 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OBiOb9DJo_D_E7AtE:-O1OBiOb9DJo_D_E7AtF:b-5cni7y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/MultiMat/DGMultiMat.hpp#L351)):*
> ```cpp
>             tk::real detg = tk::determinant(g);
>             // Compute constraint measure
>             densityConstr[e] += rho/(rho0mat[imat]*detg);
> ```

I would scale this sum by alpha. In that case, just remove the division by alpha when you initialize `rho`.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 356 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OBqYoCNxRf8Np-zrR:-O1OBqYoCNxRf8Np-zrS:b7f4d4h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/MultiMat/DGMultiMat.hpp#L356)):*
> ```cpp
>         }
>       for (std::size_t e=0; e<nelem; ++e)
>         densityConstr[e] /= ksld;
> ```

Once you scale by alpha, you don't require this division. Then you can get rid of `ksld` fully.
___
*[`src/PDE/Transport/DGTransport.hpp` line 171 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OB13f76E6be-VCX1n:-O1OB13f76E6be-VCX1o:bqijgun) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/Transport/DGTransport.hpp#L171)):*
> ```cpp
>     //! \param[in] nelem Number of elements
>     //! \param[in] unk Array of unknowns
>     //! \param[in] rho0mat List of initial densities
> ```

Let's comment the above arg-documentation since it's not used.

**Review by airaudofacundo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/616)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Inciter/DG.cpp` line 1790 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1O4mULBS-Xljv43T84:-O1OCt7x9iKuDaYipYvH:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/Inciter/DG.cpp#L1790)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This should be within an if-test that tests if `densityConstr.size() > 0`. Otherwise, for other eqs, like compflow, there is nothing in densityConstr, but it has a name, and that will result in errors from Paraview.
</blockquote></details>

Done.
___
*[`src/PDE/CompFlow/DGCompFlow.hpp` line 231 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OAuG_3jewtbihSaRr:-O1ODQzJ4fw7z44OhvFZ:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/CompFlow/DGCompFlow.hpp#L231)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's comment the above arg-documentation since they are not used.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 351 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OBiOb9DJo_D_E7AtE:-O1OPFF989ojy0DEG5C8:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/MultiMat/DGMultiMat.hpp#L351)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I would scale this sum by alpha. In that case, just remove the division by alpha when you initialize `rho`.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 356 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OBqYoCNxRf8Np-zrR:-O1OPFty3tl21K3g0_dB:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/MultiMat/DGMultiMat.hpp#L356)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Once you scale by alpha, you don't require this division. Then you can get rid of `ksld` fully.
</blockquote></details>

Done.
___
*[`src/PDE/Transport/DGTransport.hpp` line 171 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-O1OB13f76E6be-VCX1n:-O1ODYtU9eD5IPOCFM3l:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/d09dee734026671d03feab8c2c0f7c2102462f8a/src/PDE/Transport/DGTransport.hpp#L171)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's comment the above arg-documentation since it's not used.
</blockquote></details>

Done.

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/616#-:-O1OROdq2Amn6zSVO73O:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @airaudofacundo)

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/616)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

**Pull request merged**
