### PR TITLE
Add hydro page docs

### PR DESCRIPTION
**Pull request by jbakosi**
This updates the inciter doc page, adds new pages for each hydro scheme, and fills in the new page on ALECG.

It also adds @adityakpandare's newly published paper to the list of papers.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
One suggestion on the inciter main-page. Other than that, looks good!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-:-MQNp39u9deuV7glem5v:bpwrxgm)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[doc/pages/inciter.dox, line 64 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-MQNmI-a8MOWw0iTtf0H:-MQNmI-a8MOWw0iTtf0I:bcoaws9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2e172495d5a22c6afc07f6474283da17e140cffd/doc/pages/inciter.dox#L64)):*
> ```
> - @ref inciter_alecg "ALECG hydrodynamics"
> - @ref inciter_dg "Single-material DG hydrodynamics"
> - @ref inciter_mm "Multi-material DG hydrodynamics"
> ```

How about we move these four (the new additions) to the top of the list? Since this page is about the physics/methods in inciter, these four are more directly related than the others.
___
*[doc/pages/inciter_alecg.dox, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-MQNp1-N7bc3-PDIhwRD:-MQNp1-N7bc3-PDIhwRE:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2e172495d5a22c6afc07f6474283da17e140cffd/doc/pages/inciter_alecg.dox#L162)):*
> ```
> \end{split} \f]
> 
> */
> ```

Nice!

**Review by jbakosi — COMMENTED** [review]
Thanks for the quick review.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-:-MQNpbmz2a7J3_iXUtC8:b-ncgzbp)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[doc/pages/inciter.dox, line 64 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-MQNmI-a8MOWw0iTtf0H:-MQNpOf5CG4OOX2oD_D6:bbei3co) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2e172495d5a22c6afc07f6474283da17e140cffd/doc/pages/inciter.dox#L64)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

How about we move these four (the new additions) to the top of the list? Since this page is about the physics/methods in inciter, these four are more directly related than the others.
</blockquote></details>

Sounds good, I thought about the same but have not moved it so far, but now I will. ;-)

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[doc/pages/inciter.dox, line 64 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-MQNmI-a8MOWw0iTtf0H:-MQOPWwSA25y-ShrjqHI:bz0yrju) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2e172495d5a22c6afc07f6474283da17e140cffd/doc/pages/inciter.dox#L64)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Sounds good, I thought about the same but have not moved it so far, but now I will. ;-)
</blockquote></details>

Done, see a1fef38.

**Review by adityakpandare — COMMENTED** [review]
@jbakosi, I've added details about multimat.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-:-MQTnnlpE0mIdi77i_ZV:binkg4f)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/464#-:-MQXTmTW1fRKHMhnJq0c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
