### PR TITLE
Element diagnostics for DG discretization and parallel regression tests

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits adds element diagnostics to compute L2 norms of the solution and error, and L-infty norms of the error. It also adds parallel regression tests for advection of Gaussian hump using DGP0.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/225)

### CODE REVIEW

**Comment by jbakosi** [comment]
Reviewed 18 of 34 files at r1.
Review status: 18 of 31 files reviewed at latest revision, all discussions resolved.

---

*[regression/inciter/transport/GaussHump/diag.std, line 1 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8u4G6IBOmoI8RyKjvD:-L8u4G6IBOmoI8RyKjvE:b-w9v1mq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7a4ff7540b1cb7d95034848cc7ce5f13ab74f491/regression/inciter/transport/GaussHump/diag.std#L1)):*
> ```
> #     1:it             2:t            3:dt
> ```

7e19b646 adds the correct labels to the error columns based on variable names. You probably have to update this `diag.std` to make the tests pass.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Comment by adityakpandare** [comment]
Review status: 18 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[regression/inciter/transport/GaussHump/diag.std, line 1 at r1](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8u4G6IBOmoI8RyKjvD:-L8w5JkM2FkBjz-DyLin:b-xxs03s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7a4ff7540b1cb7d95034848cc7ce5f13ab74f491/regression/inciter/transport/GaussHump/diag.std#L1)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

7e19b646 adds the correct labels to the error columns based on variable names. You probably have to update this `diag.std` to make the tests pass.
</blockquote></details>

I'm on it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Comment by jbakosi** [comment]
Very nice work! Looks good, please see some minor comments below. I see the parallel DG tests diff differently in travis and also on my laptop for me. I'm getting approximately O(10e-5) diffs for O(10e-9) numbers. This looks about reasoable for me. We might have to raise the floor in `exodiff.cfg` and/or loosen the relative tolerance (or switch to absolute). Otherwise, this is good to merge. Thanks for the excellent work!

---

Reviewed 9 of 34 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 6 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/Inciter/DG.C, line 607 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8yK8o63hsHbal-5Vza:-L8yK8o63hsHbal-5Vzb:b5nu85s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/DG.C#L607)):*
> ```
>   Assert( !leakyAdjacency(), "Face adjacency leaky" );
> 
>   m_nchGhost = m_nunk - m_u.nunk();
> ```

This (the number of ghost elements on a chare) could also (always) be obtained as `m_u.nunk() - m_esuelTet.size()/4`, right? If so, then I would not store it in a variable, but just would pass that to `m_diag.compute()` later.

---

*[src/Inciter/DiagReducer.C, line 14 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8yRTZDAnp3vuTBNXBJ:-L8yRTZDAnp3vuTBNXBK:b-vatp4h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/DiagReducer.C#L14)):*
> ```
> #include "ContainerUtil.h"
> #include "NodeDiagnostics.h"
> #include "ElemDiagnostics.h"
> ```

I have an idea to make this cleaner. See 5a69f75b.

---

*[src/Inciter/ElemDiagnostics.C, line 65 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8ySeT70D2kbXKWBwEG:-L8ySeT70D2kbXKWBwEH:bsyeoq5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/ElemDiagnostics.C#L65)):*
> ```
> //! \return True if diagnostics have been computed
> // *****************************************************************************
> {
> ```

It is amazing how similar this code is to that in `NodeDiagnostics::compute()`. I will think about how we might be able to do a little better code-reuse with this. I know this might change with higher order but still it would be great to reuse it better. But let's not worry about this now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-:-L8yTqLq1tAqQUyjJXLv:bihtytr)*

**Comment by adityakpandare** [comment]
I'm trying to think why there's a difference of O(1e-5) in the DG parallel tests. Is this again a bug?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/Inciter/DG.C, line 607 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8yK8o63hsHbal-5Vza:-L90B2Zg6xuXuDmBR2IU:b-tugqed) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/DG.C#L607)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This (the number of ghost elements on a chare) could also (always) be obtained as `m_u.nunk() - m_esuelTet.size()/4`, right? If so, then I would not store it in a variable, but just would pass that to `m_diag.compute()` later.
</blockquote></details>

Yes, that's correct. I'm making this change.

---

*[src/Inciter/DiagReducer.C, line 14 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8yRTZDAnp3vuTBNXBJ:-L909TjgB9jjvI63VDWi:bh29z1o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/DiagReducer.C#L14)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I have an idea to make this cleaner. See 5a69f75b.
</blockquote></details>

Cool! Now ElemDiagnostics.C doesn't need to include NodeDiagnostics.h :+1:

---

*[src/Inciter/DiagReducer.C, line 80 at r5](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L90ASq0BONSkXucHM5w:-L90ASq0BONSkXucHM5x:beulwv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/911c8e0b30f67688db3c9ee65f0c2bfb9215d30f/src/Inciter/DiagReducer.C#L80)):*
> ```
>     // Max for the Linf norm of the numerical - analytical solution for all comp
>     for (std::size_t i=0; i<v[LINFERR].size(); ++i)
>       if (w[LINFERR][i] > v[LINFERR][i]) v[LINFERR][i] = w[LINFERR][i];
> ```

Where are the values of ```LINFERR```, ```L2ERR``` and ```L2SOL``` set?

---

*[src/Inciter/ElemDiagnostics.C, line 65 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8ySeT70D2kbXKWBwEG:-L909vt579m1uFKOCTBZ:budhw9c) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/ElemDiagnostics.C#L65)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

It is amazing how similar this code is to that in `NodeDiagnostics::compute()`. I will think about how we might be able to do a little better code-reuse with this. I know this might change with higher order but still it would be great to reuse it better. But let's not worry about this now.
</blockquote></details>

I did think of reusing all of NodeDiagnostics (which was only Diagnostics.C earlier); however, the d.Vol() would have needed to be changed somehow. And as you said, it would be different for higher order anyway... But it definitely would be nice if we could reuse it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-:-L90AnE0D_ZssUPQlmh5:bohu7g)*

**Comment by jbakosi** [comment]
I'm not sure. It could be. Usually, whenever there is global computations in parallel, e.g., reductions, required for the computation of the field data itself (not, e.g., the L2, because that is only diagnostics and does not affect the solution), there are differences due to global sums not being commutative in parallel as the order and grouping of the individual sub-sums as it is collected ina tree-fashion acros workers and PEs. But you are right, I don't see this happening for this algorithm at all and thus it should not happen.

I think that the alpine build on travis gives a different result may be due to using a different standard C library, as on alpine we are not using gnu libc, but musl libc, which is a different version and thus might even do rounding of floats different. That could/should even show differences in serial though.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Inciter/DiagReducer.C, line 14 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8yRTZDAnp3vuTBNXBJ:-L90yXCO62Qa7iWuGLvx:byhxoih) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/DiagReducer.C#L14)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Cool! Now ElemDiagnostics.C doesn't need to include NodeDiagnostics.h :+1:
</blockquote></details>

Yep, that's the purpose.

---

*[src/Inciter/DiagReducer.C, line 80 at r5](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L90ASq0BONSkXucHM5w:-L90yavT2DVGeBye-mMs:bbwonjy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/911c8e0b30f67688db3c9ee65f0c2bfb9215d30f/src/Inciter/DiagReducer.C#L80)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Where are the values of ```LINFERR```, ```L2ERR``` and ```L2SOL``` set?
</blockquote></details>

In `Diagnostics.h`, they are members of a C-style enum, which is directly and implicitly convertible to int.

---

*[src/Inciter/ElemDiagnostics.C, line 65 at r2](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L8ySeT70D2kbXKWBwEG:-L90yo5EDjMQIApDEv-4:bydhrjm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5e1390284a89517697c3fa123a95f17e206e844c/src/Inciter/ElemDiagnostics.C#L65)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I did think of reusing all of NodeDiagnostics (which was only Diagnostics.C earlier); however, the d.Vol() would have needed to be changed somehow. And as you said, it would be different for higher order anyway... But it definitely would be nice if we could reuse it.
</blockquote></details>

That's cool. Will think about this later. But even we don't reuse it much, it isn't too bad.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-:-L90x9_o6ts3OjkKcu2v:b-62ff48)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/Inciter/DiagReducer.C, line 80 at r5](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-L90ASq0BONSkXucHM5w:-L91CTuc13Lvj-EGKH98:b-4i113r) ([raw file](https://github.com/quinoacomputing/quinoa/blob/911c8e0b30f67688db3c9ee65f0c2bfb9215d30f/src/Inciter/DiagReducer.C#L80)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

In `Diagnostics.h`, they are members of a C-style enum, which is directly and implicitly convertible to int.
</blockquote></details>

Ah, I remember these C-enums now. Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Comment by jbakosi** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Comment by jbakosi** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Comment by adityakpandare** [comment]
Thanks for fixing this!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225#-:-L9531Yq7vACrPDY_LOG:b-whxd1j)*

**Comment by jbakosi** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/quinoacomputing/quinoa/225)*

**Pull request merged**
