### PR TITLE
Scheme FV

### PR DESCRIPTION
**Pull request by adityakpandare**
Creates a new discretization scheme FV which is equivalent to the DG::p0p1 scheme, but reduces memory requirements, and communication steps, resulting in a computationally faster scheme than the DG::p0p1 scheme (30-35% faster for a 4-material gas-impact problem on 88 cores). Can be used with "scheme fv" in the control file. Currently, only works with the multi-mat PDEs. Working on adding more regression tests.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
Congratulations! You have just graduated from the University of Quinoa. ;-)

There is likely some code to be reused between classes `DG` and `FV`, more than what I commented on, other than that looks good.

> Reviewed 42 of 43 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-Mk2r2jB5Oc_S-CJqayf:b-o25a95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

___
*[src/Inciter/FV.hpp, line 288 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk2nP_765e7IGfGRpZQ:-Mk2nP_8DOTUFivTffHv:b-jh0b4x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/Inciter/FV.hpp#L288)):*
> ```cpp
>         tk::destroy( nodeCommMap );
>       }
>     };
> ```

`FaceMap` and `OutMesh` could be put out to some header that could be reused by by both `FV` and `DG`.
___
*[src/Inciter/FV.cpp, line 161 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk2nx0REhcj1hUd-s8t:-Mk2nx0REhcj1hUd-s8u:b76o06p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/Inciter/FV.cpp#L161)):*
> ```cpp
>   contribute( s, CkReduction::sum_double,
>     CkCallback(CkReductionTarget(Transporter,bndint), Disc()->Tr()) );
> }
> ```

Probably this too, can be reused between `FV` and `DG`.

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
> Reviewed 42 of 43 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/Limiter.cpp, line 639 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk3Ym_nENG8fGE9s_cJ:-Mk3Ym_nENG8fGE9s_cK:b-1lainu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/PDE/Limiter.cpp#L639)):*
> ```cpp
> 
> void
> VertexBasedMultiMat_FV(
> ```

Why do we need this? It seems to me that this works exactly the same for `VertexBasedMultiMat_P1` with p0p1.
___
*[src/PDE/Limiter.cpp, line 1023 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk3ZCYA8AsTIBR0levS:-Mk3ZCYA8AsTIBR0levT:b-70irr3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b8d17afca8587b787f9d125f041cedfeeefe765f/src/PDE/Limiter.cpp#L1023)):*
> ```cpp
>     }
> 
>     // If node p is the chare-boundary node, find min/max by comparing with
> ```

Thanks for cleaning this piece of code!

**Review by jbakosi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[tests/regression/inciter/transport/SlotCyl/asynclogic/slot_cyl_fv.q, line 35 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk7wAb_-utCKmgfpyDZ:-Mk7wAb_-utCKmgfpyD_:b-ttxltw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/4a815af6c0a4f0778d006b461554841ac37763a1/tests/regression/inciter/transport/SlotCyl/asynclogic/slot_cyl_fv.q#L35)):*
> ```q
> 
>   field_output
>     interval 2
> ```

The asynclogic tests run with -b, which skips field output, independent of this.

**Review by jbakosi — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks good. I have a few minor comments.

> Reviewed 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MnarmCoBiPUJ08JbbAz:b7bmy6f)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 778 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnairO97hYVeLhkVJxd:-MnairO97hYVeLhkVJxe:b-7f64qm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Control/Inciter/InputDeck/Grammar.hpp#L778)):*
> ```cpp
>         ndof = rdof = 10;
>         stack.template get< tag::pref, tag::pref >() = true;
>       }
> ```

Let's put an `else`-catch-all here with a throw to generate a compiler error if this is missed next time someone adds a new scheme. (I guess we still need to ignore the node-centered scheme in there, which are okay to skip in there.)
___
*[src/Inciter/DG.cpp, line 368 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnajYWB-1sola_aPnZE:-MnajYWB-1sola_aPnZF:bced1zz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/01b422126b55a4e477e71c67de3746162ff0fdd6/src/Inciter/DG.cpp#L368)):*
> ```cpp
> 
>   return match;
> }
> ```

Nice! All of these now can also become _pure_ functions (from the functional programming viewpoint), which is less error-prone.
___
*[src/Inciter/ElemCommMap.hpp, line 38 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnanLpn6s7Vyn9oDXUs:-MnanLpn6s7Vyn9oDXUt:b-7nrup7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/ElemCommMap.hpp#L38)):*
> ```cpp
>                       tk::UnsMesh::Eq<3> >;
> 
> bool leakyAdjacency(
> ```

I hate to be a stickler, but let's add doxy comment for these functions below. As usual for declarations, only first line is enough here preceded by `//!`, and the rest (args, return value, details) goes to the definition (as they are already done).
___
*[src/Inciter/ElemCommMap.cpp, line 150 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mnao0iE5KY9XED80jEn:-Mnao0iE5KY9XED80jEo:b-ennhrj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/ElemCommMap.cpp#L150)):*
> ```cpp
>   } else {
>     return true;
>   }
> ```

Where do we return false?
___
*[src/Inciter/FV.hpp, line 279 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnaphWe9NZfB37ZNGea:-MnaphWe9NZfB37ZNGeb:bjyjy42) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/FV.hpp#L279)):*
> ```cpp
>         tk::destroy( nodeCommMap );
>       }
>     };
> ```

This could probably also go into some third-party location so both `FV` and `DG` can reuse it. Or rather: do we even need it in FV?

**Review by adityakpandare — COMMENTED** [review]
Hey guys, thanks for taking the time to look at this. I'm yet to implement the bound chare-array for the cell-centered scheme communication maps; I do not want to merge this in before that (too much repeating code). Thank you for your patience.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MnkT_6LBlbslqiBo7v7:b-c2yay)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 639 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk3Ym_nENG8fGE9s_cJ:-Mk3a5lP9TvbE8B0IevR:b-bgrtw0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/PDE/Limiter.cpp#L639)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Why do we need this? It seems to me that this works exactly the same for `VertexBasedMultiMat_P1` with p0p1.
</blockquote></details>

Because FV does not (and should not) need `ndofel`, which is a large vector, while DG needs it; and I would like to keep the FV code as efficient (computationally and memory wise) as possible.
___
*[src/PDE/Limiter.cpp, line 1023 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk3ZCYA8AsTIBR0levS:-Mk3c8aM26_4v2x-MYlQ:b-80tlqx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b8d17afca8587b787f9d125f041cedfeeefe765f/src/PDE/Limiter.cpp#L1023)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Thanks for cleaning this piece of code!
</blockquote></details>

Sure!

**Review by jbakosi — COMMENTED** [review]
Sounds good. That's what I thought, but did a review anyway, because it is better in smaller chunks. Keep up the good work and keep the good stuff coming. ;-)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MnkgSjM5hKJ_IMCEuHi:b5hijjc)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
> Reviewed 5 of 12 files at r6, 5 of 7 files at r7, 20 of 20 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
I did another pass at this and I have no comment. Keep up the good work!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-Mph33_L56d350jX6RPS:bq794au)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
This is finally ready to be reviewed. Still some code reuse possible between FV and DG, but this is already a good chunk of changes.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MqKlW0l3lpgEUfyr1KZ:b-y9e5vk)* status: 43 of 73 files reviewed, 6 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
Something's not right with amr-dtref for DG. Will let you know once I figure out what the issue is.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MqKuNfU7oQV4_ToPUV8:b9z5i05)* status: 43 of 73 files reviewed, 6 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
Fixed a couple of problems with Ghosts and how it works with dtref. This pull-req should be fine now.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-:-MqLMjnn-UA88hQeQTJ3:bgmkh46)* status: 43 of 73 files reviewed, 6 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: 43 of 73 files reviewed, 6 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 778 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnairO97hYVeLhkVJxd:-MqLTJwb51_lPi8zIuBX:bq64vrg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Control/Inciter/InputDeck/Grammar.hpp#L778)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Let's put an `else`-catch-all here with a throw to generate a compiler error if this is missed next time someone adds a new scheme. (I guess we still need to ignore the node-centered scheme in there, which are okay to skip in there.)
</blockquote></details>

I added an else-branch which ignores the nodal schemes with a `Throw` at runtime; but I'm not sure about how we can get a compile-time error from it. Any ideas?
___
*[src/Inciter/FV.hpp, line 288 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk2nP_765e7IGfGRpZQ:-MqLTMOKAqAXAK4RvozD:b-ivo8g4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/Inciter/FV.hpp#L288)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`FaceMap` and `OutMesh` could be put out to some header that could be reused by by both `FV` and `DG`.
</blockquote></details>

Yes, good catch. Moved them to Ghosts.
___
*[src/Inciter/FV.hpp, line 279 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnaphWe9NZfB37ZNGea:-MqLTRgyCB65rXMfMiJg:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/FV.hpp#L279)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This could probably also go into some third-party location so both `FV` and `DG` can reuse it. Or rather: do we even need it in FV?
</blockquote></details>

Done.
___
*[src/Inciter/FV.cpp, line 161 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mk2nx0REhcj1hUd-s8t:-MqLTSvCCcM5vQ1ctTQL:bk5453s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd844a12793bcc2851ef11a0a80841080ad7e531/src/Inciter/FV.cpp#L161)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Probably this too, can be reused between `FV` and `DG`.
</blockquote></details>

We are now reusing all of the ghost-setup between `fv` and `dg`.
___
*[src/Inciter/ElemCommMap.hpp, line 38 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnanLpn6s7Vyn9oDXUs:-MqLNhjHC_CgKzlEDGc-:bgo13wt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/ElemCommMap.hpp#L38)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I hate to be a stickler, but let's add doxy comment for these functions below. As usual for declarations, only first line is enough here preceded by `//!`, and the rest (args, return value, details) goes to the definition (as they are already done).
</blockquote></details>

This file was removed. I've added these comments in `Ghosts.hpp`
___
*[src/Inciter/ElemCommMap.cpp, line 150 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mnao0iE5KY9XED80jEn:-MqLUN9xAbmi2BTWinqh:b96zmsp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Inciter/ElemCommMap.cpp#L150)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Where do we return false?
</blockquote></details>

We don't. We throw if that condition is not satisfied. (this is previous code from `DG`. No change in this pull-req)

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r4, 3 of 12 files at r6, 2 of 7 files at r7, 7 of 20 files at r8, 18 of 30 files at r9, 5 of 9 files at r10, 4 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: 70 of 73 files reviewed, 9 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 778 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnairO97hYVeLhkVJxd:-MqVhPnuDi9X3V5GPTwe:b-3afnd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Control/Inciter/InputDeck/Grammar.hpp#L778)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I added an else-branch which ignores the nodal schemes with a `Throw` at runtime; but I'm not sure about how we can get a compile-time error from it. Any ideas?
</blockquote></details>

Why not just use
```c++
      } else {
        Throw("Scheme type not configured in configure_scheme");
      }
```
___
*[src/Control/Inciter/InputDeck/InputDeck.hpp, line 464 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmqqF61iLqpwAT7j6v:-MqmqqF61iLqpwAT7j6w:brk0ry6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Control/Inciter/InputDeck/InputDeck.hpp#L464)):*
> ```cpp
>     //! Query scheme centering
>     //! \return Scheme centering
>     tk::Centering centering() const
> ```

What does it mean by "scheme centering"?
___
*[src/Inciter/FV.cpp, line 681 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmsNan4Ft9MGKqpv-l:-MqmsNan4Ft9MGKqpv-m:bbcxj3f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Inciter/FV.cpp#L681)):*
> ```cpp
>     Assert( b < m_uc[2].size(), "Indexing out of bounds" );
>     Assert( b < m_pc[2].size(), "Indexing out of bounds" );
>     m_uc[2][b] = u[i];
> ```

I see you only use `m_uc` in `comsol` and `comlim`. Therefore you can size it as 2 and this will just be `m_uc[1]`.
___
*[src/Inciter/fv.ci, line 63 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmuUVfC6YMA0y-g6rE:-MqmuUVfC6YMA0y-g6rF:b-2ne607) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Inciter/fv.ci#L63)):*
> ```
>         when ownsol_complete(), comsol_complete() serial "sol" { reco(); } }
> 
>       entry void wait4lim() {
> ```

The communication system for FV do look much clean!
___
*[src/PDE/Limiter.cpp, line 2063 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mqmv1hVDkokWJrP9kfX:-Mqmv1hVDkokWJrP9kfY:b-2a2ent) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/Limiter.cpp#L2063)):*
> ```cpp
> 
> tk::real
> timeStepSizeMultiMat(
> ```

So time step is here so that DG and FV can share it, is it?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 926 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmwPF-Eya69Bw9OoIv:-MqmwPF-Eya69Bw9OoIw:b9w3us6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/MultiMat/DGMultiMat.hpp#L926)):*
> ```cpp
>         g_inputdeck.get< tag::param, tag::multimat, tag::nmat >()[system];
> 
>       return tk::fluxTerms(ncomp, nmat, ugp);
> ```

Do we need to mention the location of the function fluxTerms is in `Integrate/MultiMatTerms.cpp`?

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: 70 of 73 files reviewed, 9 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 778 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnairO97hYVeLhkVJxd:-MqoewS11tcVmt2-3CTa:bxv1i2e) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Control/Inciter/InputDeck/Grammar.hpp#L778)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Why not just use
```c++
      } else {
        Throw("Scheme type not configured in configure_scheme");
      }
```
</blockquote></details>

Because that will then `Throw` an error for the node-centered schemes (listed in the if-test) that do not need `rdof` and `ndof`. So those must be excluded.
___
*[src/Control/Inciter/InputDeck/InputDeck.hpp, line 464 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmqqF61iLqpwAT7j6v:-Mqof93i2PbvColPgAKM:bb47ltw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Control/Inciter/InputDeck/InputDeck.hpp#L464)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

What does it mean by "scheme centering"?
</blockquote></details>

`centering` stores the location of the unknowns for a particular scheme. FV and DG are cell-centered, while the others are node-centered.
___
*[src/Inciter/FV.cpp, line 681 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmsNan4Ft9MGKqpv-l:-MqohT6G6vMDiyA4CDOx:bln1mvb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Inciter/FV.cpp#L681)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I see you only use `m_uc` in `comsol` and `comlim`. Therefore you can size it as 2 and this will just be `m_uc[1]`.
</blockquote></details>

Nice catch! Fixing this. Same for `m_pc`. Will push changes soon.
___
*[src/Inciter/fv.ci, line 63 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmuUVfC6YMA0y-g6rE:-MqofPbNEglMPIsGa0B_:bdyumgf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Inciter/fv.ci#L63)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

The communication system for FV do look much clean!
</blockquote></details>

Yes, and not just clean, it improves performance significantly too.
___
*[src/PDE/Limiter.cpp, line 2063 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mqmv1hVDkokWJrP9kfX:-MqofUno1yuQiu_2q7hg:b2b2aa8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/Limiter.cpp#L2063)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

So time step is here so that DG and FV can share it, is it?
</blockquote></details>

Exactly. Trying to reuse code.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 926 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmwPF-Eya69Bw9OoIv:-Mqofmf41slPThYu0GJf:b-50q2f1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/MultiMat/DGMultiMat.hpp#L926)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Do we need to mention the location of the function fluxTerms is in `Integrate/MultiMatTerms.cpp`?
</blockquote></details>

The locations of functions do not need to be mentioned. We don't do that usually, unless it is not trivial to locate them. These are pretty easy to locate (using `grep`).

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 30 files at r9, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 778 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MnairO97hYVeLhkVJxd:-MqopyNj9Aauwu-vPXcD:bw1yhdn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/267f949d256045384828546ce64cc0cb43e961a1/src/Control/Inciter/InputDeck/Grammar.hpp#L778)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Because that will then `Throw` an error for the node-centered schemes (listed in the if-test) that do not need `rdof` and `ndof`. So those must be excluded.
</blockquote></details>

Got it! Thank you!
___
*[src/Control/Inciter/InputDeck/InputDeck.hpp, line 464 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmqqF61iLqpwAT7j6v:-Mqoq0nQ3QXc6s4jX_BH:bw1yhdn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/Control/Inciter/InputDeck/InputDeck.hpp#L464)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

`centering` stores the location of the unknowns for a particular scheme. FV and DG are cell-centered, while the others are node-centered.
</blockquote></details>

Got it! Thank you!
___
*[src/PDE/Limiter.cpp, line 2063 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-Mqmv1hVDkokWJrP9kfX:-Mqoq6krCh8kZ_WEePon:bw1yhdn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/Limiter.cpp#L2063)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Exactly. Trying to reuse code.
</blockquote></details>

Got it! Thank you!
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 926 at r12](https://reviewable.io/reviews/quinoacomputing/quinoa/514#-MqmwPF-Eya69Bw9OoIv:-Mqoq9nJ7V6tImELEMSE:bdsaxve) ([raw file](https://github.com/quinoacomputing/quinoa/blob/83277cd1df1c650f09a8ac77ef781a823dc43cde/src/PDE/MultiMat/DGMultiMat.hpp#L926)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The locations of functions do not need to be mentioned. We don't do that usually, unless it is not trivial to locate them. These are pretty easy to locate (using `grep`).
</blockquote></details>

Okay! Make sense.

**Review by WeizhaoLi2018 — APPROVED** [review]
> Reviewed 1 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/514)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

**Pull request merged**
