### PR TITLE
Mmhllc

### PR DESCRIPTION
**Pull request by airaudofacundo**
Implemented HLLCMultiMat which is a version of HLLC which _should_ work on multi-fluid.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @airaudofacundo)

___
*[`src/PDE/Riemann/HLLCMultiMat.hpp` line 109 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-O9z2DMfBxYIAzaU9Wh6:-O9z2DMfBxYIAzaU9Wh7:betrnu6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ddde62960162ad9b7cb0a307b1d42ae6a6d98cd9/src/PDE/Riemann/HLLCMultiMat.hpp#L109)):*
> ```cpp
>     for (std::size_t k=0; k<nmat; ++k) {
>       apStar[k] = 0.5 * (apl[k] + u[0][densityIdx(nmat, k)]*(vnl-Sl)*(vnl-Sm)
>                          + apr[k] + u[1][densityIdx(nmat, k)]*(vnr-Sr)*(vnr-Sm));
> ```

These two pressures that are averaged are equal (can be proven using RH conditions). So replacing the average with either one of those should be equivalent.

**Review by adityakpandare — COMMENTED** [review]
Also replaced the signal speeds with the Davis estimates, since Roe-averages might not make sense for general EOS.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-:-O9z2i6S-gem-HMZoyVc:b-g1h7b1)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @airaudofacundo)

**Comment by airaudofacundo** [comment]
*[`src/PDE/Riemann/HLLCMultiMat.hpp` line 109 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-O9z2DMfBxYIAzaU9Wh6:-OA3xLBE-k_ElfMm1d7C:bf0imza) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ddde62960162ad9b7cb0a307b1d42ae6a6d98cd9/src/PDE/Riemann/HLLCMultiMat.hpp#L109)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

These two pressures that are averaged are equal (can be proven using RH conditions). So replacing the average with either one of those should be equivalent.
</blockquote></details>

Replaced it

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629)* status: all files reviewed, 1 unresolved discussion (waiting on @airaudofacundo)

___
*[`src/PDE/Riemann/HLLCMultiMat.hpp` line 126 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-OA48wTp2lXP-Xmu9MJd:-OA48wTp2lXP-Xmu9MJe:b-hja3at) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a3ec0fc61f900a831cc61eb0fb3c5af8a94f81ca/src/PDE/Riemann/HLLCMultiMat.hpp#L126)):*
> ```cpp
>         (Sl-vnl) * u[0][densityIdx(nmat, k)] / (Sl-Sm);
>       uStar[0][energyIdx(nmat, k)] =
>         ((Sl-vnl) * u[0][energyIdx(nmat, k)] - apl[k]*vnl + apStar[k]*Sm) / (Sl-Sm);
> ```

Could you explain this change from density to apStar?

**Review by airaudofacundo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[`src/PDE/Riemann/HLLCMultiMat.hpp` line 126 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-OA48wTp2lXP-Xmu9MJd:-OA4En2v4bGtJ7UabrSs:b-kiu2id) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a3ec0fc61f900a831cc61eb0fb3c5af8a94f81ca/src/PDE/Riemann/HLLCMultiMat.hpp#L126)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you explain this change from density to apStar?
</blockquote></details>

Yes, I add the relationship below. I only used the previous expression because using the averaged pStar I could not make sure this one would hold. But now that we made sure we can use either the right or left expression I went back to this simpler expression.

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-:-OA4adLZ04mhEIBUu57y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

___
*[`src/PDE/Riemann/HLLCMultiMat.hpp` line 126 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/629#-OA48wTp2lXP-Xmu9MJd:-OA4aayBAFFlZ6HI1A9P:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a3ec0fc61f900a831cc61eb0fb3c5af8a94f81ca/src/PDE/Riemann/HLLCMultiMat.hpp#L126)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Yes, I add the relationship below. I only used the previous expression because using the averaged pStar I could not make sure this one would hold. But now that we made sure we can use either the right or left expression I went back to this simpler expression.


</blockquote></details>

Thanks!

**Pull request merged**
