### PR TITLE
Removing walker and rngtest and related TPLs

### PR DESCRIPTION
**Pull request by adityakpandare**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/530)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks good, couple of questions and a few minor suggestions on things that can also be removed.

> Reviewed 388 of 388 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-:-MpCkaeMEeXYXyxvkty-:b2h99kn)* status: all files reviewed, 11 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[external, line 1 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8kmglDUSFYClEgoy7:-Mp8kmglDUSFYClEgoy8:b-8kr1qu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/external#L1)):*
> ```
> Subproject commit 806e990d0452f2fb2c58a501d4c60ef604549989
> ```

Pstreams is not removed from <tpl>/.gitmodules. We should, no?
___
*[cmake/CodeCoverage.cmake, line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8lZuH1AYP0lpz1osf:-Mp8lZuH1AYP0lpz1osg:bz6hry5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/cmake/CodeCoverage.cmake#L76)):*
> ```CMake
>     COMMAND ${testrunner} ${ARG_TESTRUNNER_ARGS}
>     # Process gcov output for genhtml
>     COMMAND ${FASTCOV} --branch-coverage --exceptional-branch-coverage --lcov -o ${OUTPUT}.info --exclude tests/ c++/ include/ boost/ charm/ decl.h def.h openmpi pstreams Random123 pegtl tut/ highwayhash/ sol2/ moduleinit
> ```

We should not remove sol2.
___
*[cmake/CodeCoverage.cmake, line 174 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8ldQs7M3BIbQ4ynVe:-Mp8ldQs7M3BIbQ4ynVf:bz6hry5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/cmake/CodeCoverage.cmake#L174)):*
> ```CMake
>     COMMAND ${CMAKE_CTEST_COMMAND} -j${PROCESSOR_COUNT}
>     # Process gcov output for genhtml
>     COMMAND ${FASTCOV} --branch-coverage --exceptional-branch-coverage --lcov -o ${OUTPUT}.info --exclude tests/ c++/ include/ boost/ charm/ decl.h def.h openmpi pstreams Random123 pegtl tut/ highwayhash/ sol2/ moduleinit
> ```

We should not remove sol2.
___
*[cmake/ConfigExecutable.cmake, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8m0XX6pPbskEY0Ulc:-Mp8m0XX6pPbskEY0Uld:b-msi48f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/cmake/ConfigExecutable.cmake#L46)):*
> ```CMake
>             LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Runtime
>             ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Development)
>   endif()
> ```

Does this now break for unittest? If so, why?
___
*[src/Main/Inciter.cmake, line 54 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCg8fE-7RVqhQ-FrEf:-MpCg8fE-7RVqhQ-FrEg:b7mueqk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/Inciter.cmake#L54)):*
> ```CMake
>                       ${LUA_LIBRARIES}
>                       ${LIBCXX_LIBRARIES}     # only for static link with libc++
>                       ${LIBCXXABI_LIBRARIES}) # only for static link with libc++
> ```

ROOT, AEC, OMEGA_H probably not needed anymore.
___
*[src/Main/QuinoaBuildConfig.hpp.in, line 32 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCgMTrEi0ps4ItarlE:-MpCgMTrEi0ps4ItarlF:b-6n74zz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/QuinoaBuildConfig.hpp.in#L32)):*
> ```
> #cmakedefine HAS_MKL
> #cmakedefine HAS_TESTU01
> #cmakedefine HAS_ROOT
> ```

Probably no need for ROOT anymore.
___
*[src/Main/UnitTest.cmake, line 85 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiV5hDrHAIq8_xur3:-MpCiV5hDrHAIq8_xur4:bqyvo2q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/UnitTest.cmake#L85)):*
> ```CMake
>                       ${OMEGA_H_LIBRARIES}
>                       ${LIBCXX_LIBRARIES}       # only for static link with libc++
>                       ${LIBCXXABI_LIBRARIES})   # only for static link with libc++
> ```

OMEGAHMESHIO, OMEGA_H_LIBRARIES, AEC_LIBRARIES should no longer bee needed.
___
*[src/NoWarning/testu01.decl.h, line 36 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiuD81nGfA4X_Xsdc:-MpCiuD81nGfA4X_Xsdd:bn7bvc3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01.decl.h#L36)):*
> ```objc
> #endif
> 
> #endif // nowarning_testu01_decl_h
> ```

This whole file should no longer be needed.
___
*[src/NoWarning/testu01.def.h, line 45 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiy_h0Krrrr54ek9h:-MpCiy_iBL6V5DQb-0YP:bn7bvc3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01.def.h#L45)):*
> ```objc
> #elif defined(STRICT_GNUC)
>   #pragma GCC diagnostic pop
> #endif
> ```

This whole file should no longer be needed.
___
*[src/NoWarning/testu01suite.decl.h, line 36 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCj-b57N1wj4zzhNZJ:-MpCj-b57N1wj4zzhNZK:bn7bvc3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01suite.decl.h#L36)):*
> ```objc
> #endif
> 
> #endif // nowarning_testu01suite_decl_h
> ```

This whole file should no longer be needed.
___
*[src/NoWarning/testu01suite.def.h, line 42 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCj1dQ1MgFlIub7yIY:-MpCj1dQ1MgFlIub7yIZ:bn7bvc3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01suite.def.h#L42)):*
> ```objc
> #endif
> 
> #endif // nowarning_testu01suite_def_h
> ```

This whole file should no longer be needed.

**Review by adityakpandare — COMMENTED** [review]
Thanks for pointing these out!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-:-MpCuBpwDvCkajctfNZ0:b-rbxu0b)* status: 378 of 388 files reviewed, 11 unresolved discussions (waiting on @jbakosi)

___
*[external, line 1 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8kmglDUSFYClEgoy7:-MpCq57p-kaLB1pZegyb:bgqsvs9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/external#L1)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Pstreams is not removed from <tpl>/.gitmodules. We should, no?
</blockquote></details>

Nice catch. Thanks!
___
*[cmake/CodeCoverage.cmake, line 76 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8lZuH1AYP0lpz1osf:-MpCrmTG1Np3UHFjCxHo:b-yh75cl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/cmake/CodeCoverage.cmake#L76)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

We should not remove sol2.
</blockquote></details>

Hmm, I don't remember why I removed this. Thanks for pointing it out, I replaced it.
___
*[cmake/CodeCoverage.cmake, line 174 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8ldQs7M3BIbQ4ynVe:-MpCrui68S_qUPgkJbq_:bb6un1j) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/cmake/CodeCoverage.cmake#L174)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

We should not remove sol2.
</blockquote></details>

Done
___
*[src/Main/Inciter.cmake, line 54 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCg8fE-7RVqhQ-FrEf:-MpCtHt2Bst9Ezcd0VoW:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/Inciter.cmake#L54)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

ROOT, AEC, OMEGA_H probably not needed anymore.
</blockquote></details>

Done.
___
*[src/Main/QuinoaBuildConfig.hpp.in, line 32 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCgMTrEi0ps4ItarlE:-MpCtesFA3ayFBQEDHNg:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/QuinoaBuildConfig.hpp.in#L32)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Probably no need for ROOT anymore.
</blockquote></details>

Done.
___
*[src/Main/UnitTest.cmake, line 85 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiV5hDrHAIq8_xur3:-MpCu0RO1o4L-3tYMNwj:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/src/Main/UnitTest.cmake#L85)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

OMEGAHMESHIO, OMEGA_H_LIBRARIES, AEC_LIBRARIES should no longer bee needed.
</blockquote></details>

Done.
___
*[src/NoWarning/testu01.decl.h, line 36 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiuD81nGfA4X_Xsdc:-MpCu9_MCyFs7tDBXNYV:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01.decl.h#L36)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This whole file should no longer be needed.
</blockquote></details>

Done.
___
*[src/NoWarning/testu01.def.h, line 45 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCiy_h0Krrrr54ek9h:-MpCuAHz1pqBH_O0pkpX:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01.def.h#L45)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This whole file should no longer be needed.
</blockquote></details>

Done.
___
*[src/NoWarning/testu01suite.decl.h, line 36 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCj-b57N1wj4zzhNZJ:-MpCuAhW8QTJdE5i3WiI:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01suite.decl.h#L36)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This whole file should no longer be needed.
</blockquote></details>

Done.
___
*[src/NoWarning/testu01suite.def.h, line 42 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-MpCj1dQ1MgFlIub7yIY:-MpCuB-D8hu-DLqpNKoU:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b4f0efae0ac9775c99b3085a24884997233b367f/src/NoWarning/testu01suite.def.h#L42)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This whole file should no longer be needed.
</blockquote></details>

Done.
___
*[cmake/ConfigExecutable.cmake, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8m0XX6pPbskEY0Ulc:-MpCsJmf3LxVWl4cJsSo:b-2d8ydl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/cmake/ConfigExecutable.cmake#L46)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Does this now break for unittest? If so, why?
</blockquote></details>

It does not break unittest. But I'm not sure why I put that there either. I'm going to remove this.

**Review by jbakosi — APPROVED** [review]
Nice to see a whole lot of code being removed. Should speed many things up a bit.

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-:-MpCzJrO-9E943p_NWAE:b-d9ut1b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[cmake/ConfigExecutable.cmake, line 46 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-Mp8m0XX6pPbskEY0Ulc:-MpCzEQmBsRnmKRAVks-:b-mlk8c6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/c3b12124d9165a49cb5b8de68d1fad03911b7e74/cmake/ConfigExecutable.cmake#L46)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

It does not break unittest. But I'm not sure why I put that there either. I'm going to remove this.
</blockquote></details>

You were probably debugging something.

**Review by adityakpandare — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/530#-:-MpCzsHA1SgH72k_2gMZ:b-9qdoz3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
