### PR TITLE
P-relaxation update

### PR DESCRIPTION
**Pull request by adityakpandare**
Makes the cleanTraceMaterial and pressureRelaxation functions mutually exclusive, i.e. they now work on separate ranges of material volume fractions. Thank you @airaudofacundo for this suggestion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)

### CODE REVIEW

**Review by airaudofacundo — COMMENTED** [review]
Looks good, great work!

> Reviewed 19 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-:-O2z3Fh2DVvqoGGYro_t:b-dvbht1)* status: 19 of 22 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @g-rydquist)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 267 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O2z2iXn6vHeKDhodSRu:-O2z2iXn6vHeKDhodSRv:bxswxem) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MiscMultiMatFns.cpp#L267)):*
> ```cpp
>     }
> 
>     U(e, volfracDofIdx(nmat, kmax, rdof, 0)) += d_al;
> ```

Do you mind explaining these d_ variables to me? I am sure it's good I just do not understand.

**Review by airaudofacundo — APPROVED** [review]
> Reviewed 3 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @g-rydquist)

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @airaudofacundo and @g-rydquist)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 267 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O2z2iXn6vHeKDhodSRu:-O2zEQpJ7N5eZ6fJ4PXB:bbl6da4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MiscMultiMatFns.cpp#L267)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Do you mind explaining these d_ variables to me? I am sure it's good I just do not understand.
</blockquote></details>

Absolutely. `d_al` and `d_arE` keep track of the amount by which we violate conservation (volume and energy resp.) in the process of cleaning up the thermodynamic state of minority materials. Once we have the total error in volume and energy conservation, that amount is removed from the volume and energy of the majority material, so as to reinstate conservation. The result is a small perturbation (since minor material volfrac is small) in the state of the majority material, for maintaining local (element-wise) conservation. Does that answer your question?

**Review by airaudofacundo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @g-rydquist)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 267 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O2z2iXn6vHeKDhodSRu:-O2zJwQrDbUoRniWpCE2:bxgjnh0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MiscMultiMatFns.cpp#L267)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Absolutely. `d_al` and `d_arE` keep track of the amount by which we violate conservation (volume and energy resp.) in the process of cleaning up the thermodynamic state of minority materials. Once we have the total error in volume and energy conservation, that amount is removed from the volume and energy of the majority material, so as to reinstate conservation. The result is a small perturbation (since minor material volfrac is small) in the state of the majority material, for maintaining local (element-wise) conservation. Does that answer your question?
</blockquote></details>

I see, it makes sense, thanks! And is there no risk that by adding the (negative) d_al from the other materials into this one you will make this one's alpha negative?

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @airaudofacundo and @g-rydquist)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 267 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O2z2iXn6vHeKDhodSRu:-O2zLljBC2crzR_l0if8:b-hb0hkk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MiscMultiMatFns.cpp#L267)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

I see, it makes sense, thanks! And is there no risk that by adding the (negative) d_al from the other materials into this one you will make this one's alpha negative?
</blockquote></details>

No, because the `d_al` is O(1e-12). See where `d_al` is computed above. The majority material volume will definitely be orders-of-magnitude larger than this (otherwise it's not majority).

**Review by airaudofacundo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @g-rydquist)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 267 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O2z2iXn6vHeKDhodSRu:-O2zOOmhBctPj3OZmjAy:bhlojjj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MiscMultiMatFns.cpp#L267)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

No, because the `d_al` is O(1e-12). See where `d_al` is computed above. The majority material volume will definitely be orders-of-magnitude larger than this (otherwise it's not majority).
</blockquote></details>

Oh, got it, I got confused and thought this was inside the 0.0 through 1.0e-10 range, thanks!

**Review by g-rydquist — APPROVED** [review]
Looks good. It makes sense to me to do it this way I think. I tried running the case I sent you last week with these changes, and it did eliminate the negative volume fractions that could pop up.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-:-O33-o9O3P__2MFNsKHP:b-3kpap7)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/MultiMat/MultiMatIndexing.hpp` line 207 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O330PD62RxdTR1M-jOo:-O330PD62RxdTR1M-jOp:b-grc597) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MultiMatIndexing.hpp#L207)):*
> ```cpp
> 
> inline tk::real volfracPRelaxLim()
> { return 1.0e-02; }
> ```

Is there a specific reason 0.01 was chosen, other than it is a small amount of material that is still large enough to not be in danger of  going negative from the pressure relaxation?

**Review by g-rydquist — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/623)* status: all files reviewed, 1 unresolved discussion (waiting on @g-rydquist)

___
*[`src/PDE/MultiMat/MultiMatIndexing.hpp` line 207 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/623#-O330PD62RxdTR1M-jOo:-O33F67P-vsZpgMSEdN7:b256j2m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e304a598262444dcf5ce1de8dbe8206312a6561b/src/PDE/MultiMat/MultiMatIndexing.hpp#L207)):*
<details><summary><i>Previously, g-rydquist wrote…</i></summary><blockquote>

Is there a specific reason 0.01 was chosen, other than it is a small amount of material that is still large enough to not be in danger of  going negative from the pressure relaxation?
</blockquote></details>

That's the only reason. I used the water-air shocktube problem to check what is the minimum value that it can work successfully with. This is what I found that works.

**Pull request merged**
