### PR TITLE
Riemann derivatives update

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
Fix the Riemann derivatives in AUSM flux calculation and update the related regression testcase

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Good job finding the problem!

> Reviewed 4 of 60 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-:-MrNgzq2AC4KHoiWKOJZ:b-c8lxjr)* status: 4 of 60 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrNgmSv9D1aFT3ZcYEe:-MrNgmSv9D1aFT3ZcYEf:b-yx3dyj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L162)):*
> ```cpp
> 
>     // Store Riemann-advected partial pressures
>     l_minus = std::fabs( l_minus );
> ```

Good job finding this problem! Could you test the 4-material gas impact with p0p1 and dgp1 to ensure those don't diverge?

**Review by WeizhaoLi2018 — COMMENTED** [review]
I am currently running the 4-gas impact testcase with dgp1+thinc and p0p1+thinc. I will let you know once I am able to get the final solution. Thanks!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-:-MrTSkYfDafP5gGRJJgY:b-kj5k9b)* status: 4 of 60 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/Riemann/AUSM.hpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrNgmSv9D1aFT3ZcYEe:-MrXrvof7GtPVImusQCf:bv1gz3u) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Good job finding this problem! Could you test the 4-material gas impact with p0p1 and dgp1 to ensure those don't diverge?
</blockquote></details>

I have no issue for obtaining results of DGP1 + THINC and it looks good. But when I tried P0P1 + THINC for the 4-gas impact, it diverges around t = 3 showing a zero density for a minor material.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrNgmSv9D1aFT3ZcYEe:-MrXtEwY57_lyw1cLqOJ:b-eslerd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L162)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I have no issue for obtaining results of DGP1 + THINC and it looks good. But when I tried P0P1 + THINC for the 4-gas impact, it diverges around t = 3 showing a zero density for a minor material.
</blockquote></details>

Okay, let's talk in more detail about this during our meeting today.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 167 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrXtRV39tkRuLpyb9cV:-MrXtRV39tkRuLpyb9cW:b-dkm04i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L167)):*
> ```cpp
> 
>     // Store Riemann velocity
>     flx.push_back( l_plus * vriem + l_minus * vriem );
> ```

Why did this have to change? If I'm not wrong, `l_plus * vriem + l_minus * vriem` is equal to `vriem`; in which case, we should keep it `vriem`.

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 167 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrXtRV39tkRuLpyb9cV:-MrYlfc7DWS-EERZE3fF:bu25hzm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L167)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why did this have to change? If I'm not wrong, `l_plus * vriem + l_minus * vriem` is equal to `vriem`; in which case, we should keep it `vriem`.
</blockquote></details>

Last time when we fixed this in 1D, you mentioned that maybe we need to make the interface velocity the same formula as the pressure. 
I will change this back to `vriem`.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 167 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrXtRV39tkRuLpyb9cV:-MrYsiVx7WZys2E3virE:bdufu39) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L167)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Last time when we fixed this in 1D, you mentioned that maybe we need to make the interface velocity the same formula as the pressure. 
I will change this back to `vriem`.
</blockquote></details>

I probably didn't realize at the time that they are equivalent.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534)* status: 4 of 60 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Riemann/AUSM.hpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrNgmSv9D1aFT3ZcYEe:-MtJdx6SCJ87dJxoV7Iv:bbh4vm2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Okay, let's talk in more detail about this during our meeting today.
</blockquote></details>

I suggest increasing the epsilon in the denominator of `l_plus` and `l_minus` to 1e-12, and see how that affects stability for the 4-gas impact for P0P1+THINC and DGP1+THINC.

**Review by WeizhaoLi2018 — COMMENTED** [review]
Just update with the positive limiting. Will update the baseline and check the results ASAP.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-:-MtjAFAq2hNuJ7N9oYEF:b-ec7tip)* status: 3 of 63 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
Just FYI, the `multimat_waterair_shocktube_p0p1_pe1` test fails on this branch.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-:-Mtn9qvyDokS_Go7dEFK:b-wl7cnh)* status: 3 of 63 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 3 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-:-MuSoPXV3bS0OydYoOfT:bnfp4nl)* status: 7 of 63 files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[src/PDE/Riemann/AUSM.hpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/534#-MrNgmSv9D1aFT3ZcYEe:-MuSoKZ30JDt0AkkykZg:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cd89d62bf7c9cbc539310a59b84bce1ce5ffa575/src/PDE/Riemann/AUSM.hpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I suggest increasing the epsilon in the denominator of `l_plus` and `l_minus` to 1e-12, and see how that affects stability for the 4-gas impact for P0P1+THINC and DGP1+THINC.
</blockquote></details>

Thanks!

**Pull request merged**
