### PR TITLE
Eos parsing

### PR DESCRIPTION
**Pull request by adityakpandare**
EOS parsing commits. Thanks @jbakosi for all your help with this. This set of commits does not add the functional forms of the JWL eos yet, that's coming soon.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks pretty good. I have some ideas, mostly to increase readability.

> Reviewed 2 of 7 files at r2, 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-:-McjbmBkBqkS43gbfzcr:bwptzza)* status: all files reviewed, 6 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/CommonGrammar.hpp, line 271 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjVa8o9VI8oUATvwGa:-McjVa8o9VI8oUATvwGb:b-v82pfp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/CommonGrammar.hpp#L271)):*
> ```cpp
>       "... end' sub-block. The number of components between 'pstiff ... end' "
>       "is incorrect, whose size must equal the number of material-ids set by "
>       "keyword 'id' in that 'material ... end' sub-block." },
> ```

Since we may issue the above error messages for gamma, cv, and pstiff for both single-, and multi-mat, let's make the error messages more generic and not confuse the user with talking about multi-mat only.
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 308 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjWP6zAR78MXkBFGJr:-McjWP6zAR78MXkBFGJs:b-8ch5lu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L308)):*
> ```cpp
>       eosmap[mat_id[0]] = static_cast< std::size_t >(matprop.template get<
>         tag::eos >());
>       idxmap[mat_id[0]] = 0;
> ```

Will this index out if the user chooses arbitrary large (random) integers for material id?
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 530 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjXRsE7_QWy6TxRGNv:-McjXRsE7_QWy6TxRGNw:b-b9fsjv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L530)):*
> ```cpp
>             tag::eos >());
>           idxmap[midx] = i;
>           ++i;
> ```

Same here as above: will this index out if the user picks non-zero- (or-non-one-) based and large material ids?
___
*[src/PDE/ConfigureCompFlow.cpp, line 109 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjY4PD2HWRzIf8vp-i:-McjY4PD2HWRzIf8vp-j:b-wglck7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/ConfigureCompFlow.cpp#L109)):*
> ```cpp
>   const auto& m_id = matprop.get< tag::id >();
>   if (matprop.get< tag::eos >() == ctr::MaterialType::STIFFENEDGAS) {
>     nfo.emplace_back( "Stiffened Gas EoS materials: ",
> ```

Instead of having to do the if test, this is what `tk::Toggle::name()` is for. You can use it to query the _name_ in its keyword. You could write
```c++
  ctr::Material opt;
  nfo.emplace_back( opt.name( matprop.get< tag::eos >() ), ... );
```
___
*[src/PDE/ConfigureMultiMat.cpp, line 123 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZKmf7Qkacx-HXac2:-McjZKmf7Qkacx-HXac3:brnfgu6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/ConfigureMultiMat.cpp#L123)):*
> ```cpp
>       nfo.emplace_back( "Stiffened Gas EoS materials: ",
>         std::to_string(m_id.size()) );
>     }
> ```

Same here as for compflow using the `tk::Toggle` base class.
___
*[src/PDE/Reconstruction.cpp, line 1061 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZgYn1PQOjXipIe9o:-McjZgYn1PQOjXipIe9p:b-q59se) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/Reconstruction.cpp#L1061)):*
> ```cpp
>     for (std::size_t k=0; k<nmat; ++k) {
>       auto Pck = matprop[matidxmap.get< tag::eosidx >()[k]].get<
>         tag::pstiff >()[matidxmap.get< tag::matidx >()[k]];
> ```

Little more (necessarily) verbose, but pretty good-looking client code, I think.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 578 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZyta7pravFcpTMx-:-McjZyta7pravFcpTMx0:b-847755) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/CompFlow/CGCompFlow.hpp#L578)):*
> ```cpp
>       const auto& meos = g_inputdeck.get< tag::param, eq,
>         tag::matidxmap >().get< tag::eosidx >()[0];
>       auto g = matprop[meos].get< tag::gamma >()[0];
> ```

We could also write simple, one-liner, inline free-functions to make this more readable, especially for the single-material case, with the default material id as 0. Maybe something like,
```c++
template< class param, class eq >
auto eosid( std::size_t i=0 ) {
  return g_inputdeck.get< param, eq, tag::matidxmap >().get< tag::eosidx >()[ i ];
}
```
then client code for single-mat compflow would look like
```c++
auto meos = eosid< tag::param, tag::eq >();
```

And if this is the only place `meos` is used after, we could also incorporate
```
auto g = matprop[meos].get< tag::gamma >()[0];
```
into a new free function, called, e.g., `gamma()`.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: all files reviewed, 6 unresolved discussions (waiting on @jbakosi)

___
*[src/Control/CommonGrammar.hpp, line 271 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjVa8o9VI8oUATvwGa:-McnqVNg6WaAagLu1WK4:b-qu6n94) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/CommonGrammar.hpp#L271)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Since we may issue the above error messages for gamma, cv, and pstiff for both single-, and multi-mat, let's make the error messages more generic and not confuse the user with talking about multi-mat only.
</blockquote></details>

Good point. Done.
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 308 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjWP6zAR78MXkBFGJr:-McntafSCatjT0h93wn0:bdx2tpc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L308)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Will this index out if the user chooses arbitrary large (random) integers for material id?
</blockquote></details>

Yes, it will index out. I have re-written some code above that overwrites `mat_id` with 0, so that it will not matter what material-id the user specifies for compflow.
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 530 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjXRsE7_QWy6TxRGNv:-McntnuQ1GcvvDxmgGOq:b-m0vzd0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L530)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same here as above: will this index out if the user picks non-zero- (or-non-one-) based and large material ids?
</blockquote></details>

Yes for multi-mat, it will index out, and the code will not work if the user selects non-contiguous and/or random material ids. Any ideas on how we can error-check that?
___
*[src/PDE/ConfigureCompFlow.cpp, line 109 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjY4PD2HWRzIf8vp-i:-McnwTXp5-1KUFnghgGx:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/ConfigureCompFlow.cpp#L109)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Instead of having to do the if test, this is what `tk::Toggle::name()` is for. You can use it to query the _name_ in its keyword. You could write
```c++
  ctr::Material opt;
  nfo.emplace_back( opt.name( matprop.get< tag::eos >() ), ... );
```
</blockquote></details>

Done.
___
*[src/PDE/ConfigureMultiMat.cpp, line 123 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZKmf7Qkacx-HXac2:-McnxkVlCpNwPeiILKIi:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/ConfigureMultiMat.cpp#L123)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same here as for compflow using the `tk::Toggle` base class.
</blockquote></details>

Done.
___
*[src/PDE/Reconstruction.cpp, line 1061 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZgYn1PQOjXipIe9o:-Mcnwa7z7ntM1gLPk-40:b-pbdqz3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/Reconstruction.cpp#L1061)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Little more (necessarily) verbose, but pretty good-looking client code, I think.
</blockquote></details>

Agreed.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 578 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZyta7pravFcpTMx-:-Mcnye0u2ZORFB3WxvvB:b8ey9it) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/CompFlow/CGCompFlow.hpp#L578)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

We could also write simple, one-liner, inline free-functions to make this more readable, especially for the single-material case, with the default material id as 0. Maybe something like,
```c++
template< class param, class eq >
auto eosid( std::size_t i=0 ) {
  return g_inputdeck.get< param, eq, tag::matidxmap >().get< tag::eosidx >()[ i ];
}
```
then client code for single-mat compflow would look like
```c++
auto meos = eosid< tag::param, tag::eq >();
```

And if this is the only place `meos` is used after, we could also incorporate
```
auto g = matprop[meos].get< tag::gamma >()[0];
```
into a new free function, called, e.g., `gamma()`.
</blockquote></details>

This is a good idea. Let me make sure I understand correctly: these free-functions would allow the client code to directly access gamma, cv, pstiff, and would be templated on `eq`, thereby the client code (for compflow and multimat) would just do something like `gamma<eq>(imat)` to get the gamma. Is that correct?

**Review by jbakosi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 530 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjXRsE7_QWy6TxRGNv:-Mco6r2-BdnAJEOdSAZJ:btq3rdt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L530)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yes for multi-mat, it will index out, and the code will not work if the user selects non-contiguous and/or random material ids. Any ideas on how we can error-check that?
</blockquote></details>

One option is to use `std::map` or `std::unordered_map` as `idxmap` and then do a search in client code. Another one is to process here the ids the user specified and ensure that they are zero based and that there are no gaps in them (since `std::vector` as a map requires those). I vote for the latter, because looking up a material should not involve a search, because that will prevent vectorization.

To ensure zero-based ids, you can use `tk::shiftToZero()` in Mesh/Reorder.[ch]pp and to ensure no gaps, we could error out. You could use `tk::unique()` or `tk::uniquecopy()` in Base/ContainerUtil.[ch]pp (testing on the sizes before and after) to test for uniqueness.
___
*[src/PDE/ConfigureCompFlow.cpp, line 109 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjY4PD2HWRzIf8vp-i:-Mco9nfS823HWD2JoKZi:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/ConfigureCompFlow.cpp#L109)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 578 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZyta7pravFcpTMx-:-McoA2E0BFRy8yi02BMw:bljjxke) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/CompFlow/CGCompFlow.hpp#L578)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is a good idea. Let me make sure I understand correctly: these free-functions would allow the client code to directly access gamma, cv, pstiff, and would be templated on `eq`, thereby the client code (for compflow and multimat) would just do something like `gamma<eq>(imat)` to get the gamma. Is that correct?
</blockquote></details>

Yes, you are right, we could also eliminate `tag::param` from the template argument list to make it even more concise. And, yeah, at first I was suggesting to simplify the lookup of the eosidx only, but then I realized that we could even completely hide the fact from client code that there is a material-id-mapping and just directly return the gamma, cv, etc., and perform the material-id-map lookup internally to these free functions for gamma, cv, etc.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: 13 of 26 files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 530 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjXRsE7_QWy6TxRGNv:-MctLAG4ESTiIhVNHhH-:b38f9qq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/Control/Inciter/InputDeck/Grammar.hpp#L530)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

One option is to use `std::map` or `std::unordered_map` as `idxmap` and then do a search in client code. Another one is to process here the ids the user specified and ensure that they are zero based and that there are no gaps in them (since `std::vector` as a map requires those). I vote for the latter, because looking up a material should not involve a search, because that will prevent vectorization.

To ensure zero-based ids, you can use `tk::shiftToZero()` in Mesh/Reorder.[ch]pp and to ensure no gaps, we could error out. You could use `tk::unique()` or `tk::uniquecopy()` in Base/ContainerUtil.[ch]pp (testing on the sizes before and after) to test for uniqueness.
</blockquote></details>

I agree, those many map-searches will be inefficient. I added the error-checking, albeit in a slightly different manner.
___
*[src/PDE/CompFlow/CGCompFlow.hpp, line 578 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McjZyta7pravFcpTMx-:-Mctac0JAS_b-dXgDWUi:b-t04vyn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bfca000e6c6fb7c9610e71c976ed3c72fa0ac30c/src/PDE/CompFlow/CGCompFlow.hpp#L578)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yes, you are right, we could also eliminate `tag::param` from the template argument list to make it even more concise. And, yeah, at first I was suggesting to simplify the lookup of the eosidx only, but then I realized that we could even completely hide the fact from client code that there is a material-id-mapping and just directly return the gamma, cv, etc., and perform the material-id-map lookup internally to these free functions for gamma, cv, etc.
</blockquote></details>

Code looks very clean after this change. Great suggestion!

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks great! I have one suggestion.

> Reviewed 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-:-McuGQt7BfsmIKFIzQsZ:b-sj9ml2)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/Reconstruction.cpp, line 1056 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McuBs13CwO7km2owPr_:-McuBs13CwO7km2owPra:b-j7qk9t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/904875c18e44c58a73842ed610197fb24aa4b03d/src/PDE/Reconstruction.cpp#L1056)):*
> ```cpp
> 
>     for (std::size_t k=0; k<nmat; ++k) {
>       auto Pck = inciter::pstiff< tag::multimat >(system, k);
> ```

Very nice!
___
*[src/PDE/EoS/EoS.hpp, line 68 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McuDKxx2jS51QW1Pdxp:-McuDKxy9uma27DnOqul:b153kqh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/904875c18e44c58a73842ed610197fb24aa4b03d/src/PDE/EoS/EoS.hpp#L68)):*
> ```cpp
>     tag::matidx >()[imat];
> 
>   return matprop[meos].template get< tag::cv >()[midx];
> ```

How about:
```c++
template< class Eq, class Prop >
tk::real
getmatprop( ncomp_t system, std::size_t imat=0 ) {
  const auto& matprop = g_inputdeck.get< tag::param, Eq, tag::material >()[ system ];
  const auto& map = g_inputdeck.get< tag::param, Eq, tag::matidxmap >();
  const auto& meos = map.template get< tag::eosidx >()[ imat ];
  const auto& midx = map.template get< tag::matidx >()[ imat ];
  return matprop[ meos ].template get< Prop >()[ midx ];
}

template< class Eq > tk::real gamma( ncomp_t system, std::size_t imat=0 ) { return getmatprop< Eq, tag::gamma >( system, imat ); }
...
```

**Review by jbakosi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/EoS/EoS.hpp, line 68 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McuDKxx2jS51QW1Pdxp:-McuGsc0CWDRSlbKg6rq:b-rqf2x8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/904875c18e44c58a73842ed610197fb24aa4b03d/src/PDE/EoS/EoS.hpp#L68)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

How about:
```c++
template< class Eq, class Prop >
tk::real
getmatprop( ncomp_t system, std::size_t imat=0 ) {
  const auto& matprop = g_inputdeck.get< tag::param, Eq, tag::material >()[ system ];
  const auto& map = g_inputdeck.get< tag::param, Eq, tag::matidxmap >();
  const auto& meos = map.template get< tag::eosidx >()[ imat ];
  const auto& midx = map.template get< tag::matidx >()[ imat ];
  return matprop[ meos ].template get< Prop >()[ midx ];
}

template< class Eq > tk::real gamma( ncomp_t system, std::size_t imat=0 ) { return getmatprop< Eq, tag::gamma >( system, imat ); }
...
```
</blockquote></details>

Or better
```c++
template< class Eq, class Prop >
tk::real
getmatprop( ncomp_t system, std::size_t imat=0 ) {
  const auto& matprop = g_inputdeck.get< tag::param, Eq, tag::material >()[ system ];
  const auto& map = g_inputdeck.get< tag::param, Eq, tag::matidxmap >();
  auto meos = map.template get< tag::eosidx >()[ imat ];
  auto midx = map.template get< tag::matidx >()[ imat ];
  return matprop[ meos ].template get< Prop >()[ midx ];
}
```
since `meos` and `midx` are simple types.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/PDE/EoS/EoS.hpp, line 68 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/495#-McuDKxx2jS51QW1Pdxp:-McuPK6N1Q3QjCtxXH-Z:b-skozjq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/904875c18e44c58a73842ed610197fb24aa4b03d/src/PDE/EoS/EoS.hpp#L68)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Or better
```c++
template< class Eq, class Prop >
tk::real
getmatprop( ncomp_t system, std::size_t imat=0 ) {
  const auto& matprop = g_inputdeck.get< tag::param, Eq, tag::material >()[ system ];
  const auto& map = g_inputdeck.get< tag::param, Eq, tag::matidxmap >();
  auto meos = map.template get< tag::eosidx >()[ imat ];
  auto midx = map.template get< tag::matidx >()[ imat ];
  return matprop[ meos ].template get< Prop >()[ midx ];
}
```
since `meos` and `midx` are simple types.
</blockquote></details>

Ah, should've caught the repeating code. Thanks!

**Review by jbakosi — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by jbakosi — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/495)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
