### PR TITLE
Prepare for coupled solvers operating on different meshes

### PR DESCRIPTION
**Pull request by jbakosi**
Let's merge #468 first.

Put in code to configure solvers using different meshes and describe how they are coupled. See 6761c85 for more details.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
A few comments as we discussed offline. Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-:-MUyPu7-7fw3cHguyZCE:b-j999l0)* status: 0 of 35 files reviewed, 4 unresolved discussions (waiting on @jbakosi)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 124 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyDboqCTWV-zMRZe8j:-MUyDbor9jIppUC91Hpp:bzawnfn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/Grammar.hpp#L124)):*
> ```cpp
>           location.push_back( { 0.0, 0.0, 0.0 } );
>         else    // reference was not given, but location was, overwrite
>           location.back() = { 0.0, 0.0, 0.0 };
> ```

Should we generate an error, if user specifies `location`, but no `reference` mesh?
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 570 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyHiL0BKhSpaAXl2zD:-MUyHiL0BKhSpaAXl2zE:b-7icia2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/Grammar.hpp#L570)):*
> ```cpp
>       const auto& bc = m_stack.template get< tag::param, Eq, tag::bc, BC >();
>       for (const auto& eq : bc) {
>         std::unordered_set< int > bcset;
> ```

As we discussed, should we put the `bcset` outside the bc loop?
___
*[src/Control/Inciter/InputDeck/InputDeck.hpp, line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyMo878IAngfpuh-6F:-MUyMo878IAngfpuh-6G:b-erl5s0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/InputDeck.hpp#L463)):*
> ```cpp
>     };
> 
>     //! Function object to extract the mesh filenames assigned to solvers
> ```

Can you correct the comment as we discussed?
___
*[src/Inciter/Transporter.cpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyOaT_5cZ7i8unsiY0:-MUyOaT_5cZ7i8unsiY1:b-ezje5p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Inciter/Transporter.cpp#L162)):*
> ```cpp
>   auto ctrinput = g_inputdeck.mesh();
> 
>   Assert( !cmdinput.empty() || !ctrinput.empty(),
> ```

Should we make this an `err_chk` here instead to catch user-errors?
___
*[src/Inciter/Transporter.cpp, line 166 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyP7qH5tYBcp5XVaCj:-MUyP7qH5tYBcp5XVaCk:b-dv03gx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Inciter/Transporter.cpp#L166)):*
> ```cpp
>     "meshes must be configured in the control file." );
> 
>    // Prepend control file path to mesh filenames in given in control file
> ```

Thats nice! :+1:

**Review by adityakpandare — COMMENTED** [review]
> Reviewed 21 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469)* status: 21 of 35 files reviewed, 4 unresolved discussions (waiting on @jbakosi)

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469)* status: 18 of 35 files reviewed, 4 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 124 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyDboqCTWV-zMRZe8j:-MUzHuY675OShhZleFkP:bhiudaj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/Grammar.hpp#L124)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Should we generate an error, if user specifies `location`, but no `reference` mesh?
</blockquote></details>

Done by a67affd4b.
___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 570 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyHiL0BKhSpaAXl2zD:-MUzOMpA9KBhFY91t6Sg:b-iknwk1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/Grammar.hpp#L570)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

As we discussed, should we put the `bcset` outside the bc loop?
</blockquote></details>

No, this needs to stay, because then the following triggers an error:
```
  compflow
    mesh filename "unitcube_4.5k.exo" end
    bc_dirichlet
      sideset 1 2 3 4 5 6 end
    end
  end
  
  compflow
    mesh
      filename "unitcube_1k.exo"
    end
    bc_dirichlet
      sideset 1 2 3 4 5 6 end
    end
  end
```
which should be allowed.
___
*[src/Control/Inciter/InputDeck/InputDeck.hpp, line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyMo878IAngfpuh-6F:-MUzOjk233kfJ4jE91yJ:b-ejvhvd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/InputDeck.hpp#L463)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Can you correct the comment as we discussed?
</blockquote></details>

Done by 79da0506a.
___
*[src/Inciter/Transporter.cpp, line 162 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyOaT_5cZ7i8unsiY0:-MUzR6Xd6dM_zz3I3eWw:ba3k7jw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Inciter/Transporter.cpp#L162)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Should we make this an `err_chk` here instead to catch user-errors?
</blockquote></details>

Done by 17025bfb3.

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 6 of 35 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-:-MUzUaDH5qc91Sjp8lKj:bnfp4nl)* status: 27 of 35 files reviewed, all discussions resolved

___
*[src/Control/Inciter/InputDeck/Grammar.hpp, line 570 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-MUyHiL0BKhSpaAXl2zD:-MUzU9fl0og0hbCzkfz6:b-te8hjz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6aae1f09acda0a8c1979c924b5e995472bf1e314/src/Control/Inciter/InputDeck/Grammar.hpp#L570)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

No, this needs to stay, because then the following triggers an error:
```
  compflow
    mesh filename "unitcube_4.5k.exo" end
    bc_dirichlet
      sideset 1 2 3 4 5 6 end
    end
  end
  
  compflow
    mesh
      filename "unitcube_1k.exo"
    end
    bc_dirichlet
      sideset 1 2 3 4 5 6 end
    end
  end
```
which should be allowed.
</blockquote></details>

Right, because multiple systems should be allowed to set different BC's on the same side-sets. Thanks!

**Review by jbakosi — COMMENTED** [review]
Thanks for the review.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/469#-:-MUzV7507OQjgnI2KQuh:b-9qdoyq)* status: 27 of 35 files reviewed, all discussions resolved

**Pull request merged**
