### PR TITLE
multimat IC box with energy content and mass specified in input file

### PR DESCRIPTION
**Pull request by adityakpandare**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/494)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Couple of minor comments/suggestions. Good to go.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-:-McjSm7cEnK-QXYRoxxE:bl46up1)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 1131 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjS4Eo8w25SGOyi99A:-McjS4Eo8w25SGOyi99B:b1akp32) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/DGMultiMat.hpp#L1131)):*
> ```cpp
>     //! \param[in] coord Array of nodal coordinates
>     //! \param[in] U Array of unknowns
>     //! \param[in] P Array of primitive quantities
> ```

Can you also comment what is returned using the `\return` doxy command?
___
*[src/PDE/MultiMat/Problem/BoxInitialization.cpp, line 103 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjSRAE5-nHc8AbFZrN:-McjSRAE5-nHc8AbFZrO:boojngf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/Problem/BoxInitialization.cpp#L103)):*
> ```cpp
>         s[volfracIdx(nmat,boxmatid-1)]*rhok[boxmatid-1], u, v, w,
>         s[volfracIdx(nmat,boxmatid-1)]*rhok[boxmatid-1]*spi,
>         s[volfracIdx(nmat,boxmatid-1)], boxmatid-1);
> ```

Would it look shorter and easier to read to store `volfracIdx(nmat,boxmatid-1)` in a temp var?

**Review by adityakpandare — COMMENTED** [review]
Thanks for the quick review!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-:-McjVU2uDMHH5E7TUvNV:b-ncgzc2)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 1131 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjS4Eo8w25SGOyi99A:-McjVPtQ8V6qbmxI0c7A:bbkruso) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/DGMultiMat.hpp#L1131)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Can you also comment what is returned using the `\return` doxy command?
</blockquote></details>

Oops. Missed that. Done.
___
*[src/PDE/MultiMat/Problem/BoxInitialization.cpp, line 103 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjSRAE5-nHc8AbFZrN:-McjVNLG93GixaC9DX0u:b-ho5wpv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/Problem/BoxInitialization.cpp#L103)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Would it look shorter and easier to read to store `volfracIdx(nmat,boxmatid-1)` in a temp var?
</blockquote></details>

Agreed. Done.

**Review by jbakosi — APPROVED** [review]
Oh, I would not call that quick. ;-)

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-:-Mcjc0w3-Yabemfpc9dT:bc7vokw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 1131 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjS4Eo8w25SGOyi99A:-Mcjc8Ke-8fEdwaQjsU-:bgx6jg3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/DGMultiMat.hpp#L1131)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Oops. Missed that. Done.
</blockquote></details>

Excellent, thanks!
___
*[src/PDE/MultiMat/Problem/BoxInitialization.cpp, line 103 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-McjSRAE5-nHc8AbFZrN:-McjcDsf1LGFOBPU_Qzw:b-89q77k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f7f96c1abca382fc8fca1e07979a65552df504ae/src/PDE/MultiMat/Problem/BoxInitialization.cpp#L103)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Agreed. Done.
</blockquote></details>

Cool.

**Review by adityakpandare — COMMENTED** [review]
I meant "quick" in the sense that I didn't need to make too many changes ;-)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/494#-:-MckIZJY4x41xvMpAVEG:b5qzjfm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
