### PR TITLE
Moving Serial Advection-P0 to DGPDE

### PR DESCRIPTION
**Pull request by adityakpandare**
Moving Serial Advection-P0 to DGPDE, so the common Problem definition can be used. Added the 2D Gaussian hump problem for testing. Regression test upcoming in the next PR.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/215)

### CODE REVIEW

**Comment by jbakosi** [comment]
Excellent work! Please see some comments below and pointers for some future work to make this even more general. Thanks.

---

Reviewed 11 of 11 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[regression/inciter/transport/GaussHump/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6Z9amQ1w4IAGyULtUr:-L6Z9amQ1w4IAGyULtUs:bj9c3h8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/regression/inciter/transport/GaussHump/CMakeLists.txt#L6)):*
> ```CMake
> # Virtualization = 0
> 
> add_regression_test(gauss_hump_pe1 ${INCITER_EXECUTABLE}
> ```

`_peX` will be added automatically cmake, no need to add it here, this way it will duplicate it.

---

*[regression/inciter/transport/GaussHump/gauss_hump.q, line 5 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6Z9ugFN2CxTJI7MJKs:-L6Z9ugFN2CxTJI7MJKt:bq5e61s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/regression/inciter/transport/GaussHump/gauss_hump.q#L5)):*
> ```
> # Keywords are case-sensitive
> 
> title "Zalesak's slotted cylinder"
> ```

No big deal, but let's change the title to _GaussHump_ or something like it.

---

*[src/Control/Keywords.h, line 2910 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZArVtY9ggTFaazup9:-L6ZArVtY9ggTFaazupA:b-t3hdxe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Control/Keywords.h#L2910)):*
> ```objc
> 
> struct gauss_hump_info {
>   using code = Code< Z >;
> ```

Why `Z`? Why not code `G`, that does not seem to be taken yet either.

---

*[src/Inciter/DG.C, line 100 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZCaSLfVJh91pis4NP:-L6ZCaSLfVJh91pis4NQ:b-uz0g0b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Inciter/DG.C#L100)):*
> ```
>   // Set initial conditions for all PDEs
>   for (const auto& eq : g_dgpde) eq.initialize( m_geoElem, m_u,  d->T() );
>   for (const auto& eq : g_dgpde) eq.initialize( m_geoElem, m_un, d->T() );
> ```

Why not just `m_un = m_u`? That would be faster and simpler.

---

*[src/Inciter/DG.C, line 259 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZEfzH1m-_ZDYdxGzz:-L6ZEfzH1m-_ZDYdxH--:b-8vpylh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Inciter/DG.C#L259)):*
> ```
>   {
>     m_u(e,0,0) = m_un(e,0,0) + deltat/m_lhs(e,0,0) * m_rhs(e,0,0);
>   }
> ```

Nice! So instead of the loop, would the following also work?
```
m_u = m_un + deltat*m_rhs/m_lhs;
```

---

*[src/PDE/Transport/DGTransport.h, line 88 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZI006P5eKkl6kfG-5:-L6ZI006P5eKkl6kfG-6:b6yng9v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L88)):*
> ```objc
>       for (std::size_t e=0; e<nelem; ++e)
>       {
>         lhs(e,0,0) = geoElem(e,0,0);
> ```

This is the cell volume, correct? Can we put a  comment that this is putting in the cell volumes?

Also this should probably be `lhs(e,c,m_offset)` and within a loop over `m_ncomp`, as in `initialize()`, right? I know this is kind of overkill here (and also somewhat for MatCG and DiagCG as well) because the entries are the same for all components of a system, but this way the size of the lhs and rhs vectors are the same (well for DGP0 and DiagCG anyway) so their solution is simple code and probably more efficient because they just go in lock-step, i.e., vectorizable. However, we should benchmark this in the future because it may be better for storing less and writing a loop for using them instead. This kind of optimization is on our list.

---

*[src/PDE/Transport/DGTransport.h, line 140 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZLZSWaRvJXRqu3U7u:-L6ZLZSWaRvJXRqu3U7v:bja9yfm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L140)):*
> ```objc
>         {
>           R(el,c,0) -= farea * flux[c];
>           R(er,c,0) += farea * flux[c];
> ```

`,m_offset)` instead of `,0)` for both `R`s. This will make it work if this transport eq system is not the only one and it is not the first one among multiple ones.

---

*[src/PDE/Transport/DGTransport.h, line 147 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZMDr7gpmlXv4gtlGT:-L6ZMDr7gpmlXv4gtlGU:b4dprld) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L147)):*
> ```objc
> 
>       // symmetry boundary condition
>       auto bc = bface.find(1);
> ```

Does this hard-code `1` as the side set for the symmetry BC? If so, this will only work with a specific mesh where this is correctly set up for this problem, i.e., side 1 is always the symmetry BC. Same for outflow and inflow below.

We should instead query the _type_ of the boundary and do the different thing here. However, this will need some more work, introducing more keywords for the parser, adding a new `Option` class for selecting among the different types of BCs. Since we only had Dirichlet BCs (for CG) so far, this is not done, but I have an idea how it should be done. So I will help with this. This is need in the parser, because we want to get this info from the user, i.e., which side set id in the mesh file should be associated to what type of BC. After that we can also abstract away the common parts of the different "branches" below, so it does not repeat much of the same code. But let's not worry about this for now. We can get back to it soon - we just have to keep in mind, that this is not very general yet.

---

*[src/PDE/Transport/DGTransport.h, line 176 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZMZqllyomuagNqQHZ:-L6ZMZqllyomuagNqQH_:b-3qnh7r) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L176)):*
> ```objc
>           for (ncomp_t c=0; c<m_ncomp; ++c)
>           {
>             R(el,c,0) -= farea * flux[c];
> ```

`R(el,c,m_offset)`

---

*[src/PDE/Transport/DGTransport.h, line 211 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZMeXQuxZRkJE4jcAj:-L6ZMeXQuxZRkJE4jcAk:b-rq2fec) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L211)):*
> ```objc
>           for (ncomp_t c=0; c<m_ncomp; ++c)
>           {
>             R(el,c,0) -= farea * flux[c];
> ```

`R(el,c_m_offset)`

---

*[src/PDE/Transport/DGTransport.h, line 246 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZMiN26Vv4t-gXUtSK:-L6ZMiN26Vv4t-gXUtSL:b-rq2fec) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L246)):*
> ```objc
>           for (ncomp_t c=0; c<m_ncomp; ++c)
>           {
>             R(el,c,0) -= farea * flux[c];
> ```

`R(el,c_m_offset)`

---

*[src/PDE/Transport/Problem/GaussHump.h, line 4 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZNiuXLe9st9hQ_LJx:-L6ZNiuXLe9st9hQ_LJy:bv5ymcn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L4)):*
> ```objc
> /*!
>   \file      src/PDE/Transport/Problem/GaussHump.h
>   \copyright 2012-2015, J. Bakosi, 2016-2018, Los Alamos National Security, LLC.
> ```

Please take off _2012-2015, J. Bakosi,_ as this file is just created now, so I don't claim a personal copyright on it.

---

*[src/PDE/Transport/Problem/GaussHump.h, line 41 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZOnpIQ3fAJPMm1jQC:-L6ZOnpIQ3fAJPMm1jQD:b-eaqhf5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L41)):*
> ```objc
>     {
>       tk::real ax = 0.1;
>       tk::real ay = 0.1;
> ```

Are `ax`and `ay` the same as the ones assigned by `prescribedVelocity`? If so, we should query that one here so they are given only at a single location.

---

*[src/PDE/Transport/Problem/GaussHump.h, line 53 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZOFcsBT-TcxjHb8g-:-L6ZOFcsBT-TcxjHb8g0:blrj4cr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L53)):*
> ```objc
>         s[c] = 1.0 * exp( -((x-x0)*(x-x0)
>                      + (y-y0)*(y-y0))/(2.0 * 0.005) );
>       }
> ```

This is okay for now, but it would be good to make this different based on different `c`, so that we get a different solution for a different component, so we can test this as a system of transport eqs. See `SlotCyl` for an example, which does rotation and it starts the IC at different angles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-:-L6ZSp9F8y5nMPSnR5RJ:b-s9agt0)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[regression/inciter/transport/GaussHump/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6Z9amQ1w4IAGyULtUr:-L6ae4TVW0gNl-p8sUk6:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/regression/inciter/transport/GaussHump/CMakeLists.txt#L6)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`_peX` will be added automatically cmake, no need to add it here, this way it will duplicate it.
</blockquote></details>

Done.

---

*[regression/inciter/transport/GaussHump/gauss_hump.q, line 5 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6Z9ugFN2CxTJI7MJKs:-L6aeFYA711GC3EVAFM6:b-q4gxl3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/regression/inciter/transport/GaussHump/gauss_hump.q#L5)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

No big deal, but let's change the title to _GaussHump_ or something like it.
</blockquote></details>

Yeah, this slipped by me. Thanks.

---

*[src/Control/Keywords.h, line 2910 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZArVtY9ggTFaazup9:-L6aeUEUUoWaggDnyEMc:bci3fen) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Control/Keywords.h#L2910)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why `Z`? Why not code `G`, that does not seem to be taken yet either.
</blockquote></details>

Done. What does this code do?

---

*[src/Inciter/DG.C, line 100 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZCaSLfVJh91pis4NP:-L6aedEfV2VFopG1cfsr:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Inciter/DG.C#L100)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Why not just `m_un = m_u`? That would be faster and simpler.
</blockquote></details>

Okay.

---

*[src/Inciter/DG.C, line 259 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZEfzH1m-_ZDYdxGzz:-L6aiPCn5uBxMoR4uJ5u:b-3py32y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Inciter/DG.C#L259)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Nice! So instead of the loop, would the following also work?
```
m_u = m_un + deltat*m_rhs/m_lhs;
```
</blockquote></details>

Yes it does. Made the change.

---

*[src/PDE/Transport/DGTransport.h, line 88 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZI006P5eKkl6kfG-5:-L6aiSIYsQzVzs1OX1Gh:b-d2828) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L88)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This is the cell volume, correct? Can we put a  comment that this is putting in the cell volumes?

Also this should probably be `lhs(e,c,m_offset)` and within a loop over `m_ncomp`, as in `initialize()`, right? I know this is kind of overkill here (and also somewhat for MatCG and DiagCG as well) because the entries are the same for all components of a system, but this way the size of the lhs and rhs vectors are the same (well for DGP0 and DiagCG anyway) so their solution is simple code and probably more efficient because they just go in lock-step, i.e., vectorizable. However, we should benchmark this in the future because it may be better for storing less and writing a loop for using them instead. This kind of optimization is on our list.
</blockquote></details>

Okay, made this change. Yes, I think some timing tests should be helpful. I think it might take up too much memory...

---

*[src/PDE/Transport/DGTransport.h, line 140 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZLZSWaRvJXRqu3U7u:-L6aj3BCP-Rs6C6c-mxq:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L140)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`,m_offset)` instead of `,0)` for both `R`s. This will make it work if this transport eq system is not the only one and it is not the first one among multiple ones.
</blockquote></details>

Done.

---

*[src/PDE/Transport/DGTransport.h, line 147 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZMDr7gpmlXv4gtlGT:-L6ajGNq7McU39DbMwVe:b-ykh927) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L147)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Does this hard-code `1` as the side set for the symmetry BC? If so, this will only work with a specific mesh where this is correctly set up for this problem, i.e., side 1 is always the symmetry BC. Same for outflow and inflow below.

We should instead query the _type_ of the boundary and do the different thing here. However, this will need some more work, introducing more keywords for the parser, adding a new `Option` class for selecting among the different types of BCs. Since we only had Dirichlet BCs (for CG) so far, this is not done, but I have an idea how it should be done. So I will help with this. This is need in the parser, because we want to get this info from the user, i.e., which side set id in the mesh file should be associated to what type of BC. After that we can also abstract away the common parts of the different "branches" below, so it does not repeat much of the same code. But let's not worry about this for now. We can get back to it soon - we just have to keep in mind, that this is not very general yet.
</blockquote></details>

Yeah, that's a great idea, and was thinking of asking you about how to eliminate the repetitive loops anyway.

---

*[src/PDE/Transport/Problem/GaussHump.h, line 4 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZNiuXLe9st9hQ_LJx:-L6ajhn2amyPj8e2qDGc:b-4hvi0m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L4)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Please take off _2012-2015, J. Bakosi,_ as this file is just created now, so I don't claim a personal copyright on it.
</blockquote></details>

Got it.

---

*[src/PDE/Transport/Problem/GaussHump.h, line 41 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZOnpIQ3fAJPMm1jQC:-L6al8UlseKBETYeqnVy:b-xqxoz9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L41)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Are `ax`and `ay` the same as the ones assigned by `prescribedVelocity`? If so, we should query that one here so they are given only at a single location.
</blockquote></details>

Yes, that's a better way. Made the change.

---

*[src/PDE/Transport/Problem/GaussHump.h, line 53 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZOFcsBT-TcxjHb8g-:-L6ajlE_CKswjgFV43Mz:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/Problem/GaussHump.h#L53)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This is okay for now, but it would be good to make this different based on different `c`, so that we get a different solution for a different component, so we can test this as a system of transport eqs. See `SlotCyl` for an example, which does rotation and it starts the IC at different angles.
</blockquote></details>

Okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215)*

**Comment by adityakpandare** [comment]
Thanks Jozsef. I've taken care of the comments.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-:-L6alMX4PbZsf6hBZAbr:btwfgco)*

**Comment by jbakosi** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Control/Keywords.h, line 2910 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZArVtY9ggTFaazup9:-L6awQboemjmxnBxSDiZ:b5962ko) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Control/Keywords.h#L2910)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Done. What does this code do?
</blockquote></details>

It shows up as a concise notation on the screen of what is registered in the PDE classes here:
```
131:  * Registered partial differential equations:
131:  --------------------------------------------
131:      Unique equation types          : 2
131:      With all policy combinations   : 14
131:
131:      Legend: equation name : supported policies
131:
131:      Policy codes:
131:       * h: physics configuration:
131:         A - Advection
131:         D - Advection + diffusion
131:         N - Navier-Stokes
131:         E - Euler
131:       * r: problem:
131:         U - User-defined
131:         S - Shear-diffusion
131:         V - Vortical flow
131:         N - Nonlinear energy growth
131:         R - Rayleigh-Taylor
131:         T - Taylor-Green
131:         Z - Zalesak's slotted cylinder
131:
131:      Compressible flow              : h:EN, r:NRTUV
131:      Transport                      : h:AD, r:SZ
```

Now you see why `Z` would be confusing.

---

*[src/PDE/Transport/DGTransport.h, line 88 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZI006P5eKkl6kfG-5:-L6ax7Ned7grHdePxzeg:b-khxgrz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/PDE/Transport/DGTransport.h#L88)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Okay, made this change. Yes, I think some timing tests should be helpful. I think it might take up too much memory...
</blockquote></details>

Yeah, I have been looking into memory usage, esp. on large problems. We have done and will do more memory profiling to find out what, where, and when takes up the most memory and fix if we can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215)*

**Comment by adityakpandare** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Control/Keywords.h, line 2910 at r2](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215#-L6ZArVtY9ggTFaazup9:-L6b5vR52rTk99BKa7zL:b-yc7zq3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/daf666ba03d9fe6683cda64a84d476eee79f8dbf/src/Control/Keywords.h#L2910)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

It shows up as a concise notation on the screen of what is registered in the PDE classes here:
```
131:  * Registered partial differential equations:
131:  --------------------------------------------
131:      Unique equation types          : 2
131:      With all policy combinations   : 14
131:
131:      Legend: equation name : supported policies
131:
131:      Policy codes:
131:       * h: physics configuration:
131:         A - Advection
131:         D - Advection + diffusion
131:         N - Navier-Stokes
131:         E - Euler
131:       * r: problem:
131:         U - User-defined
131:         S - Shear-diffusion
131:         V - Vortical flow
131:         N - Nonlinear energy growth
131:         R - Rayleigh-Taylor
131:         T - Taylor-Green
131:         Z - Zalesak's slotted cylinder
131:
131:      Compressible flow              : h:EN, r:NRTUV
131:      Transport                      : h:AD, r:SZ
```

Now you see why `Z` would be confusing.
</blockquote></details>

Aah! Got it. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quinoacomputing/quinoa/215)*

**Pull request merged**
