### PR TITLE
Add positivity preserving limiter for multi-material DGP1

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
This PR adds positivity-preserving limiter for multi-material DGP1

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536)

### CODE REVIEW

**Review by WeizhaoLi2018 — COMMENTED** [review]
Let's see how it goes if we run the shock-bubble interaction problem on this branch.

Also there is one issue with the current branch. All other multi-material regression tests pass except for the `inciter:multimat_waterair_shocktube_p0p1_pe1`. I am worried about this since binary diff shows a significant different results:

```
Element variables:
   volfrac1_numerical              abs diff:  9.0356073e-01 ~  8.3182294e-01 = 7.17378e-02 (block 1, elmt 322)
   volfrac2_numerical              abs diff:  9.6439273e-02 ~  1.6817706e-01 = 7.17378e-02 (block 1, elmt 322)
   density_numerical               abs diff:  3.9527786e+01 ~  5.2732532e+00 = 3.42545e+01 (block 1, elmt 845)
   x-velocity_numerical            rel diff:  4.8381073e-09 ~ -5.4921863e-09 = 1.88091e+00 (block 1, elmt 209)
   y-velocity_numerical            rel diff:  4.5922828e+04 ~ -4.7622053e+04 = 1.96432e+00 (block 1, elmt 284)
   z-velocity_numerical            rel diff:  1.0941970e+04 ~ -9.4059502e+03 = 1.85962e+00 (block 1, elmt 284)
   pressure_numerical              rel diff:  3.3227348e+05 ~  2.0856665e+08 = 9.98407e-01 (block 1, elmt 593)
   total_energy_density_numerical  rel diff:  8.3068626e+05 ~  5.2149351e+08 = 9.98407e-01 (block 1, elmt 593)
```

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-MsdLE2jCy5x2HmnkmEz:b-uz097q)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
I'll let you know how this goes.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-MsewG3I2GZRiKxikzcE:b-ew5w7c)* status: 0 of 2 files reviewed, all discussions resolved

**Review by adityakpandare — CHANGES_REQUESTED** [review]
I have some comments below. In addition: for the test `inciter:multimat_waterair_shocktube_p0p1_pe1`, have you checked the solution at final flow time (t=2.4e-4)? How does it look?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-MtJcgz6EK2sOrwGCAcB:bz6mvtu)* status: all files reviewed, 4 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 553 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJb-Xl7WFNntcTvI4a:-MtJb-Xl7WFNntcTvI4b:b-cvbzi0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L553)):*
> ```cpp
> // *****************************************************************************
> //  Kuzmin's vertex-based limiter for multi-material DGP1
> //! \param[in] system Equation system index
> ```

Why is this `system` doc added? It's already there.
___
*[src/PDE/Limiter.cpp, line 1598 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJbPZxBQSAnm7uoCjv:-MtJbPZxBQSAnm7uoCjw:b-isau05) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1598)):*
> ```cpp
> }
> 
> void PositivityPreservingLimiting( std::size_t system,
> ```

Since this function seems to be very specific to multimat, let the name convey that. I would call this `PositivityLimitingMultiMat()` (omitting "preserving" since it's too long).
___
*[src/PDE/Limiter.cpp, line 1644 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJbsUk6I0wn7JNCnPs:-MtJbsUk6I0wn7JNCnPt:bz8pl1h) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1644)):*
> ```cpp
>     tk::Jacobian( coordel[0], coordel[1], coordel[2], coordel[3] );
> 
>   std::vector< tk::real > phi_bound(ncomp+nprim, 1.0);
> ```

Why is it needed to have limiter coefficients for `p` and `u` in the same vector? Let's have separate vectors `phiu_bound` and `phip_bound` or something similar.
___
*[src/PDE/Limiter.cpp, line 1717 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJc9ecB2Akyhuomu0H:-MtJc9ecB2Akyhuomu0I:bg9v3ad) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1717)):*
> ```cpp
> 
> tk::real
> PositivityPreservingLimitingFunction( const tk::real min,
> ```

Let's call this `PositivityLimiting()`, consistent with other limiter-function names.

**Review by adityakpandare — COMMENTED** [review]
Also, we checked that the shock-bubble test with dgp1 now computes until final time.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-MtJd4j_7X8ie98LSGwM:b-wuctsx)* status: all files reviewed, 4 unresolved discussions (waiting on @WeizhaoLi2018)

**Review by WeizhaoLi2018 — COMMENTED** [review]
The reason why regression test of water-air shocktube for p0p1 fails is that during the simulation, the pressure of air in a few cells shows negative value (high order solution value) and this does not cause any instability due to constrained_pressure function. For now when it goes negative, PosirivityLimiting will be triggered.

I have checked the updated result of water-air shocktube and it looks good. Therefore, I just updated the baseline of the regression test.

I think this PR are able to be merged. Let me know if we have any issue passing the online tests.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-MtizK82DjJRT0J5yenp:b-chvql2)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/Limiter.cpp, line 553 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJb-Xl7WFNntcTvI4a:-MtixMtO1u0Jvf27TYmd:b-86wqha) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L553)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why is this `system` doc added? It's already there.
</blockquote></details>

Removed! Thank you!
___
*[src/PDE/Limiter.cpp, line 1598 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJbPZxBQSAnm7uoCjv:-MtizI4a0GznXecIduo5:b-tanz96) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1598)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Since this function seems to be very specific to multimat, let the name convey that. I would call this `PositivityLimitingMultiMat()` (omitting "preserving" since it's too long).
</blockquote></details>

Fixed! Thank you!
___
*[src/PDE/Limiter.cpp, line 1644 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJbsUk6I0wn7JNCnPs:-MtizDWR1239WZ6sInYs:b-3ekbxy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1644)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why is it needed to have limiter coefficients for `p` and `u` in the same vector? Let's have separate vectors `phiu_bound` and `phip_bound` or something similar.
</blockquote></details>

Just separate the vector. Thank you!
___
*[src/PDE/Limiter.cpp, line 1717 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJc9ecB2Akyhuomu0H:-MtizBboBD14OV_LuDxL:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1717)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's call this `PositivityLimiting()`, consistent with other limiter-function names.
</blockquote></details>

Done! Thank you!

**Review by adityakpandare — APPROVED** [review]
Thanks @weizhaoli2018, this looks good to be merged.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-Mtj99ld-5nEDRW-rsET:b-c7lsmi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 1644 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-MtJbsUk6I0wn7JNCnPs:-Mtj94CT7eGT4HRbVPTe:bs6xyfs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6e83d6f72865fef2cedb1db906ad5ee4eb53aa3f/src/PDE/Limiter.cpp#L1644)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just separate the vector. Thank you!
</blockquote></details>

Looks good! Thanks.

**Review by adityakpandare — APPROVED** [review]
Tests are passing. Let's merge this.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/536#-:-Mtn2RHn-1qJ5FwuxGwg:b-t60abo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Pull request merged**
