### PR TITLE
Eos sg new framework

### PR DESCRIPTION
**Pull request by TannerNielsen**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/553)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
This new eos required quite a few changes! Thank you for persisting through this @tannernielsen! I have a just a few comments below. In addition to those, another question: Can we remove the functions from `PDE/EoS/EoS.hpp` that are unused after this change?

> Reviewed 83 of 84 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-:-N5quv1n86moQwZxsB-1:b-fjqkkp)* status: all files reviewed, 5 unresolved discussions (waiting on @TannerNielsen)

___
*[`src/PDE/FunctionPrototypes.hpp` line 75 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5kB09Y9Qn_bdZ4156Y:-N5kB09Y9Qn_bdZ4156Z:b-450n17) ([raw file](https://github.com/quinoacomputing/quinoa/blob/72e24e17b612b12f17d28131394806e666a40e16/src/PDE/FunctionPrototypes.hpp#L75)):*
> ```cpp
>   ( ncomp_t, ncomp_t, const std::vector< inciter::EoS_Base* >&,
>     const std::vector< real >&, real, real, real, real,
>     const std::array< tk::real, 3 >& ) >;
> ```

Any particular reason why the arguments of this function-type were rearranged? It looks like the only change here is the rearrangement of the Eos-base vector from the 3rd position to the last position.
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 37 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5qrs512Zbx8No8OiDY:-N5qrs512Zbx8No8OiDZ:b-s38n0d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a4240bfa4ae08a8f73e7187b3aaf0b9875c00e0/src/PDE/EoS/StiffenedGas.hpp#L37)):*
> ```cpp
>     //! \param[in] cv Specific heat at constant volume
>     // *************************************************************************
>     StiffenedGas(tk::real gamma, tk::real pstiff, tk::real cv, std::size_t ) :
> ```

What is the purpose of the last argument for the constructor (the arg with type `std::size_t`)? I see that you're passing the material-id to it, but it's not being used here. Can it be removed? Or will it be needed in the future for some reason?
___
*[`src/PDE/Transport/Problem/CylVortex.hpp` line 25 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5qtPbe731hn4AzhVQm:-N5qtPbe731hn4AzhVQn:b-x3m0wr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a4240bfa4ae08a8f73e7187b3aaf0b9875c00e0/src/PDE/Transport/Problem/CylVortex.hpp#L25)):*
> ```cpp
> #include "Types.hpp"
> #include "SystemComponents.hpp"
> //#include "FunctionPrototypes.hpp"
> ```

Can we remove the commented code above?
___
*[`src/PDE/Transport/Problem/CylVortex.hpp` line 39 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5qtB1r6Jab58cSP0xY:-N5qtB1r6Jab58cSP0xZ:bm8t7e1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a4240bfa4ae08a8f73e7187b3aaf0b9875c00e0/src/PDE/Transport/Problem/CylVortex.hpp#L39)):*
> ```cpp
>   public:
>     //! Evaluate analytical solution at (x,y,t) for all components
> //    static tk::InitializeFn::result_type
> ```

Can we remove the commented code above, or will we be needing it in the future?
___
*[`src/PDE/Transport/Problem/CylVortex.hpp` line 46 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5qtHa35D387yKixB2d:-N5qtHa35D387yKixB2e:b-x3m0wr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a4240bfa4ae08a8f73e7187b3aaf0b9875c00e0/src/PDE/Transport/Problem/CylVortex.hpp#L46)):*
> ```cpp
> 
>     //! Evaluate analytical solution at (x,y,z,t) for all components
> //    static tk::InitializeFn::result_type
> ```

Can we remove the commented code above?

**Review by TannerNielsen — COMMENTED** [review]
I commented out all the old EOS calls, except for eos_pressure (used in CompFlow), and it passed all tests. I had missed one of the eos_totalenergy calls, but that is corrected now.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-:-N6PfZcXDyyE2V5pPJ6r:b-kvwfhl)* status: 80 of 85 files reviewed, 5 unresolved discussions (waiting on @adityakpandare and @TannerNielsen)

**Review by adityakpandare — CHANGES_REQUESTED** [review]
New code got added to `develop` while you were working on this branch, that's why that `eos_totalenergy()` got left out. It might've changed again, so you might want to merge `develop` into this branch and see if any new eos-calls were added. Thanks for the changes! I have just a couple more comments below.

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-:-N6PmINzBk_sYDRslUzN:b-eofxt3)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @TannerNielsen)

___
*[`src/PDE/FunctionPrototypes.hpp` line 75 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5kB09Y9Qn_bdZ4156Y:-N6PlnIqDmthFD-A24LI:bl2u0d6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/72e24e17b612b12f17d28131394806e666a40e16/src/PDE/FunctionPrototypes.hpp#L75)):*
<details><summary><i>Previously, TannerNielsen wrote…</i></summary><blockquote>

I think it was just to be more consistent with where mat_blk is in the other calls. Some of the other calls have variables with default assignments, so they need to be at the end of the function call.
</blockquote></details>

Ah, okay. Thanks for making this consistent!
___
*[`src/PDE/EoS/EoS.hpp` line 124 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N6Pm5Ja8keh8rAYoJnv:-N6Pm5Ja8keh8rAYoJnw:b8wnwsm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/015d5352ff3e68dceed85c10e12f2a226d7682b8/src/PDE/EoS/EoS.hpp#L124)):*
> ```cpp
> //                      tk::real temp,
> //                      std::size_t imat=0 )
> //{
> ```

Should we remove these functions altogether? I don't see them being used otherwise...
___
*[`src/PDE/EoS/StiffenedGas.hpp` line 37 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-N5qrs512Zbx8No8OiDY:-N6Pn240CMtFoLRYIyTz:b-9bi22s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a4240bfa4ae08a8f73e7187b3aaf0b9875c00e0/src/PDE/EoS/StiffenedGas.hpp#L37)):*
<details><summary><i>Previously, TannerNielsen wrote…</i></summary><blockquote>

I think it can be removed. The material-id is used for diagnostics for some of the calls, but it gets passed in when needed.
</blockquote></details>

Yes, I see. Let's remove it then, so that we're not passing unwanted data into these derived objects.

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/553#-:-N8VDbQrCvRgQDY5Cbvz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TannerNielsen)

**Pull request merged**
