### PR TITLE
Fix nodal output

### PR DESCRIPTION
**Pull request by adityakpandare**
This pair of commits fixes the nodal outputs for dg and fv schemes. Previously, an incorrect assumption of distributivity of the division in nodal-averaging caused incorrect nodal field output.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542)

### CODE REVIEW

**Review by WeizhaoLi2018 — COMMENTED** [review]
The results I obtained from both compflow and multi-material solver look good.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-:-MyI8Yk-6OvIxghnL2oq:btjn3f8)* status: 0 of 7 files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Thanks @weizhaoli2018! I checked the 4-mat gas impact problem, using the fv scheme. Nodal and element field output looks good. Let me know if you have questions about the code.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-:-MyIGCTu9_RZ_LPs-Z0R:bvyeki3)* status: 0 of 7 files reviewed, all discussions resolved

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
I think I could understand what you are doing here. But still have one question?

Where do we evaluate the derived variable (pressure and velocity) in the code when it is compflow?

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-:-MyJGXVb80xL-0c-EWPh:bu9thh)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/Inciter/DG.cpp, line 551 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-MyJ2w2SA5ZKuTNCLSbj:-MyJ2w2SA5ZKuTNCLSbk:beq2fpu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7f4db80608d904bbad57d2c498a9e42e153e3987/src/Inciter/DG.cpp#L551)):*
> ```cpp
> //!   cells as wells as in nodes. If the solution is not refined, the solution
> //!   is evaluated in nodes.
> //! \return Solution in cells, primitive variables in cells, solution in nodes,
> ```

I know this function is void. But maybe it's good to have some statement here to demonstrate that `m_uElemfields, m_pElemfields, m_uNodefields, m_pNodefields` are the place where the results are stored in this function.

**Review by adityakpandare — COMMENTED** [review]
The functions that compute derived (and other) vars for compflow are defined in `PDE/ConfigureCompFlow.hpp`, see `pressureOutvar()`, etc. These functions have been appropriately allocated to the `getvar` in `g_inputdeck.get< tag::cmd, tag::io, tag::outvar >()`, based on user-specified fields to be output. `getvar()` is called from `numericFieldOutput()`. Does that answer your question?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-:-MyJhQO0AGi2fOty4Z6R:bhqgntl)* status: all files reviewed, 1 unresolved discussion (waiting on @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 551 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-MyJ2w2SA5ZKuTNCLSbj:-MyJjFfbDpFr8VyPNzOl:bwrf5u4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7f4db80608d904bbad57d2c498a9e42e153e3987/src/Inciter/DG.cpp#L551)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I know this function is void. But maybe it's good to have some statement here to demonstrate that `m_uElemfields, m_pElemfields, m_uNodefields, m_pNodefields` are the place where the results are stored in this function.
</blockquote></details>

Sure. I'll make that comment.

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/Inciter/DG.cpp, line 551 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/542#-MyJ2w2SA5ZKuTNCLSbj:-MyNDJNs0dF3baEBtjKO:b-8a64xx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/7f4db80608d904bbad57d2c498a9e42e153e3987/src/Inciter/DG.cpp#L551)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Sure. I'll make that comment.
</blockquote></details>

Looks good to me. Thanks!

**Review by WeizhaoLi2018 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/542)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
