### PR TITLE
Shock indicator

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
This PR includes:
1. Update on P2 limiting strategy
2. Apply p0p1 to volume fractions in mult-material scheme
3. Add shock indicator based on interface conservation and its related input block.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558)

### CODE REVIEW

**Review by WeizhaoLi2018 — COMMENTED** [review]
Hey @adityakpandare , can you help me to add our flux function call in Limiter.cpp. I tried to pass FluxFn in the function call.  But Limiter.cpp does not recognize it. Which file I might need to include so that Limiter can recognize the flux function type?

The rest of the code should be ready. After fixing the flux call, I will update all the regression tests.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-N9CdsIj2CNk34OS3PfW:b-r579g7)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
Including `FunctionPrototypes.hpp` in `Limiter.cpp` should fix this. Let me know if it doesn't.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-N9ClH4j2aixqodJEyzA:b-cp2j99)* status: 0 of 11 files reviewed, all discussions resolved

**Review by WeizhaoLi2018 — COMMENTED** [review]
I have `FunctionPrototypes.hpp` included in `Limiter.hpp`. But it doesn't help.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-N9Clx6E6Rw1GCwdtkj9:bo0e6kr)* status: 0 of 11 files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Can you share the detailed error message from the compiler?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-N9CmoiA6RsSloJSk2fY:bqah8ba)* status: 0 of 11 files reviewed, all discussions resolved

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558)* status: 9 of 13 files reviewed, 17 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[`src/Control/Inciter/Types.hpp` line 141 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAPlzVAwnOfFbTodig:-NAAPlzW8lWUaZi54vSx:b-waxtxd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/Control/Inciter/Types.hpp#L141)):*
> ```cpp
> using shock_indicator = tk::TaggedTuple< brigand::list<
>     tag::shock_indicator,     bool                //!< Shock indicator on/off
>   , tag::mesh_size,           tk::real            //!< Mesh size
> ```

Wouldn't the mesh size be different for each element? If so, shouldn't it be calculated for each element `e` while evaluating the shock-detector for `e`? We already save the minimum edge-size for each element in `geoElem(e,4,0)` if that's what we would like to use.
___
*[`src/PDE/Limiter.cpp` line 343 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAQwy56VJA9SzS3BEP:-NAAQwy6CqFrqj14nCcV:b-yqswk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L343)):*
> ```cpp
> //! \param[in] inpoel Element connectivity
> //! \param[in] ndofel Vector of local number of degrees of freedom
> //! \param[in] nelem Number of elements
> ```

Let's add documentation for all the new arguments here.
___
*[`src/PDE/Limiter.cpp` line 416 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARBIo4hjZor19hQXd:-NAARBIo4hjZor19hQXe:b-dvf49d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L416)):*
> ```cpp
>   [[maybe_unused]] const std::vector< std::vector<tk::real> >& uNodalExtrm,
>   [[maybe_unused]] const std::vector< std::vector<tk::real> >& mtInv,
>   const tk::FluxFn& flux,
> ```

Let's add documentation for these new arguments.
___
*[`src/PDE/Limiter.cpp` line 474 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARTWPBCprqdr4ossR:-NAARTWQ24C11ddzEGoP:b-yuo638) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L474)):*
> ```cpp
>       std::vector< std::vector<tk::real> > unk;
>       // If DG(P2), first project the P2-polynomial solution to P1 solution
>       // space and then apply the limiting function
> ```

We are removing 3rd order DOFs if a shock is detected, correct? If so, let's modify the above comment to reflect just that: "removing 3rd order DOFs if discontinuity is detected, and applying limiting to the 2nd order/P1 solution"
___
*[`src/PDE/Limiter.cpp` line 509 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARvMA8GIBQs2kIkuF:-NAARvMB35IP2eiX--Hq:bz3pqbe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L509)):*
> ```cpp
>   const tk::Fields& geoElem,
>   const tk::UnsMesh::Coords& coord,
>   const tk::FluxFn& flux,
> ```

Let's add documentation for these new args.
___
*[`src/PDE/Limiter.cpp` line 613 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASKM9CQHn_cz-Kbk6:-NAASKMA5cL41Y4Id6ZA:b-6f0ehq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L613)):*
> ```cpp
>       std::vector< tk::real > phic_p2, phip_p2;
> 
>       if(ndof > 1 && intsharp == 0 && nmat > 1)
> ```

As discussed offline, let's use bound-preserving limiting when an interface is detected (which we do a few lines below)
___
*[`src/PDE/Limiter.cpp` line 675 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASoM02B1SkQRqTDr6:-NAASoM02B1SkQRqTDr7:b-swj1ap) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L675)):*
> ```cpp
>   [[maybe_unused]] const std::vector< std::vector<tk::real> >& uNodalExtrm,
>   [[maybe_unused]] const std::vector< std::vector<tk::real> >& pNodalExtrm,
>   [[maybe_unused]] const std::vector< std::vector<tk::real> >& mtInv,
> ```

Let's add documentation for these arguments.
___
*[`src/PDE/Limiter.cpp` line 742 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAT7co7Qo8k-xioQCt:-NAAT7cp6a_iyIlmo43x:bkbgxq2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L742)):*
> ```cpp
>       // The vector of limiting coefficients for P1
>       std::vector< tk::real > phic_p1(ncomp, 1.0), phic_p2(ncomp, 1.0);
>       std::vector< tk::real > phip_p1(nprim, 1.0), phip_p2(ncomp, 1.0);
> ```

Why is the size of `phip_p2` `ncomp` and not `nprim`?
___
*[`src/PDE/Limiter.cpp` line 747 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASyPT1uPDsddzf3F6:-NAASyPT1uPDsddzf3F7:b-tykdrp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L747)):*
> ```cpp
>       if(shockmarker[e]) {
>         // If DG(P2), first project the P2-polynomial solution to P1 solution
>         // space and then apply the limiting function
> ```

Let's modify this comment as mentioned previously for the Compflow function.
___
*[`src/PDE/Limiter.cpp` line 765 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATSPY4qosCBSdq7oY:-NAATSPZEzmw6L6Xm0Aw:b-2y6mf2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L765)):*
> ```cpp
>         VertexBasedLimiting(prim, P, esup, inpoel, coord, e, rdof, dof_el,
>           offset, nprim, phip_p1, {0, nprim-1});
>       } /* else {
> ```

Is the following code not needed anymore? I thought we need to limit minor material quantities whether a shock is detected or not. Is that not the case anymore?
___
*[`src/PDE/Limiter.cpp` line 792 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATeFQ1NVSsRg8JzbX:-NAATeFQ1NVSsRg8JzbY:bsexwp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L792)):*
> ```cpp
>       }*/
> 
>       if(ndof > 1 && intsharp == 0 && nmat > 1)
> ```

As discussed offline, let's modify this condition so that it only uses `intInd` to check if bound preserving should be used.
___
*[`src/PDE/Limiter.cpp` line 980 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATwydAzcdL8pLgnZr:-NAATwydAzcdL8pLgnZs:b-n5hacu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9a271cd1db179916c6f08526a0779b1361bcb22e/src/PDE/Limiter.cpp#L980)):*
> ```cpp
>           if (matInt[k]) {
>             phic_p1[volfracIdx(nmat,k)] = 1.0;
>             phic_p2[volfracIdx(nmat,k)] = 1.0;
> ```

Why was `phic_p2 = 1.0` removed?
___
*[`src/PDE/Limiter.cpp` line 1196 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAUQS_8BDzPdsHVpYc:-NAAUQS_8BDzPdsHVpYd:bupg3cq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L1196)):*
> ```cpp
> void
> VertexBasedLimiting(
>   [[maybe_unused]] const std::vector< std::vector< tk::real > >& unk,
> ```

should we just remove `unk` if it's not going to be used in the function below?
___
*[`src/PDE/Limiter.cpp` line 2005 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAUJ15123vtMwlsQik:-NAAUJ169dB2mZKde40G:bk9qrpi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L2005)):*
> ```cpp
>                       const std::size_t ndof,
>                       const std::size_t rdof,
>                       const std::vector< inciter::EoS_Base* >& mat_blk,
> ```

Let's add documentation for mat_blk.
___
*[`src/PDE/Limiter.cpp` line 2043 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWxOt19Ni1_px4wLe:-NAAWxOt19Ni1_px4wLf:b-h07mly) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L2043)):*
> ```cpp
> // *****************************************************************************
> {
>   const auto mesh_size = g_inputdeck.get< tag::shock_indicator, tag::mesh_size >();
> ```

I think mesh size will be different  for each element, and can be obtained using `geoElem(e,4,0)` which is the min-edge of element `e`.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 205 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAV2nb0TrYELLWbDdl:-NAAV2nb0TrYELLWbDdm:b-6y46db) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Integrate/MultiMatTerms.cpp#L205)):*
> ```cpp
>         // In summary, high-order discretization for non-conservative terms in
>         // volume fraction equations is avoided for sharp interface problems.
>         if (ndof <= 4 || intsharp == 1) {
> ```

Is this new condition for dgp2 with THINC?
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 432 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWimR74mEvX6vLHsv:-NAAWimS3lFlkFXDE8Ly:bbqy12d) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/MultiMat/DGMultiMat.hpp#L432)):*
> ```cpp
>         is_p0p1 = true;
> 
>       // do reconstruction only if P0P1 or if interface reconstruction is active
> ```

Let's remove the above comment since it's no longer applicable.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 444 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWbb88AI7mLodzsCF:-NAAWbb99_j6SpnE8veH:b-y1hzuc) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/MultiMat/DGMultiMat.hpp#L444)):*
> ```cpp
>       // specify how many variables need to be reconstructed
>       std::array< std::size_t, 2 > varRange {{0, m_ncomp-1}};
>       // If DG is applied
> ```

let's expand on this comment, "If DG is applied, reconstruct only volume fractions"

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558)* status: 6 of 13 files reviewed, 17 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Control/Inciter/Types.hpp` line 141 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAPlzVAwnOfFbTodig:-NABCouJAGqwoIADzTyW:b-e99ab1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/Control/Inciter/Types.hpp#L141)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Wouldn't the mesh size be different for each element? If so, shouldn't it be calculated for each element `e` while evaluating the shock-detector for `e`? We already save the minimum edge-size for each element in `geoElem(e,4,0)` if that's what we would like to use.
</blockquote></details>

Just changed the threshold evaluation.
___
*[`src/PDE/Limiter.cpp` line 343 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAQwy56VJA9SzS3BEP:-NABFGwVEdCzlcOwQ0gV:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L343)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's add documentation for all the new arguments here.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 416 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARBIo4hjZor19hQXd:-NABG-Zd4yCFEmCGcuMM:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L416)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's add documentation for these new arguments.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 474 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARTWPBCprqdr4ossR:-NABGNXVBObFRkfSpr7n:b-j65sc4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L474)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We are removing 3rd order DOFs if a shock is detected, correct? If so, let's modify the above comment to reflect just that: "removing 3rd order DOFs if discontinuity is detected, and applying limiting to the 2nd order/P1 solution"
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 509 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAARvMA8GIBQs2kIkuF:-NABGbMa2a9cvNOTcojY:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L509)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's add documentation for these new args.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 613 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASKM9CQHn_cz-Kbk6:-NABGji-3VKywHLEdmxY:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L613)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

As discussed offline, let's use bound-preserving limiting when an interface is detected (which we do a few lines below)
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 675 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASoM02B1SkQRqTDr6:-NABHB4lDJP4voFLmW3W:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L675)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's add documentation for these arguments.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 742 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAT7co7Qo8k-xioQCt:-NABHIDmChjBtOh8aOhI:bj3p95l) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L742)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why is the size of `phip_p2` `ncomp` and not `nprim`?
</blockquote></details>

Sorry, this is a typo. Just fixed.
___
*[`src/PDE/Limiter.cpp` line 747 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASyPT1uPDsddzf3F6:-NABHVWvBpEGeQs_ogdH:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L747)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's modify this comment as mentioned previously for the Compflow function.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 765 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATSPY4qosCBSdq7oY:-NABI4Ee50QbaILjn3VE:b2mu832) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L765)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is the following code not needed anymore? I thought we need to limit minor material quantities whether a shock is detected or not. Is that not the case anymore?
</blockquote></details>

The volume fraction of minor materials will be limited as we just discussed.
___
*[`src/PDE/Limiter.cpp` line 792 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATeFQ1NVSsRg8JzbX:-NABIIsY-U4gheSlLwjf:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L792)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

As discussed offline, let's modify this condition so that it only uses `intInd` to check if bound preserving should be used.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 980 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATwydAzcdL8pLgnZr:-NABIP0f46FPmOIBh3ge:btutah) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9a271cd1db179916c6f08526a0779b1361bcb22e/src/PDE/Limiter.cpp#L980)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why was `phic_p2 = 1.0` removed?
</blockquote></details>

Volume fraction will only be applied as P0P1 so that I removed it.
___
*[`src/PDE/Limiter.cpp` line 1196 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAUQS_8BDzPdsHVpYc:-NABOKlMDJtDmpL65EyL:bgve7f3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L1196)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

should we just remove `unk` if it's not going to be used in the function below?
</blockquote></details>

Just removed `unk`.
___
*[`src/PDE/Limiter.cpp` line 2005 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAUJ15123vtMwlsQik:-NABP8lhCl45_YnyQqx4:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L2005)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's add documentation for mat_blk.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/Limiter.cpp` line 2043 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWxOt19Ni1_px4wLe:-NABPBtCEcHKzA61UOxQ:b3zbods) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L2043)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I think mesh size will be different  for each element, and can be obtained using `geoElem(e,4,0)` which is the min-edge of element `e`.
</blockquote></details>

Just changed to local threshold using `geoElme(e, 4, 0)`
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 205 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAV2nb0TrYELLWbDdl:-NABPVSb5RmTTUI8Mh1K:bhnl1j8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Integrate/MultiMatTerms.cpp#L205)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is this new condition for dgp2 with THINC?
</blockquote></details>

Yes, with this condition, we can evolve volume fraction using P0P1 for DGP2 with THINC scheme.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 432 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWimR74mEvX6vLHsv:-NABPzVH70KUW2gQ-SWk:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/MultiMat/DGMultiMat.hpp#L432)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's remove the above comment since it's no longer applicable.
</blockquote></details>

Done! Thank you!
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 444 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAAWbb88AI7mLodzsCF:-NABQ7Ua6V1Vh6J9G6k8:bol3kou) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/MultiMat/DGMultiMat.hpp#L444)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

let's expand on this comment, "If DG is applied, reconstruct only volume fractions"
</blockquote></details>

Done! Thank you!

**Review by adityakpandare — CHANGES_REQUESTED** [review]
A few questions:
1. Why did the p0p1 baselines needed to be changed if the shock-detection only affects dgp1/p2?
2. I have modified keywords for shock-detector, so that now shock-detector is triggered **only if shock_detector_coeff > 1e-6**. Is that the intended behavior?

> Reviewed 5 of 72 files at r4, 9 of 10 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-NAUyY6b6gvytFyxE2gx:bsvkfuu)* status: 18 of 76 files reviewed, 4 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[`src/PDE/Limiter.cpp` line 613 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAASKM9CQHn_cz-Kbk6:-NAV-PXECz24Xyz8zS4F:bmlatcq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L613)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done! Thank you!
</blockquote></details>

I have a comment on this below.
___
*[`src/PDE/Limiter.cpp` line 792 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAATeFQ1NVSsRg8JzbX:-NAV-S6B9tYwv1xkRTiZ:bmlatcq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e8bba6f92f22c1d64d3e6434ca734f7c18278661/src/PDE/Limiter.cpp#L792)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done! Thank you!
</blockquote></details>

I have a comment on this below.
___
*[`src/PDE/Limiter.cpp` line 645 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAUxtii9zaz4xdNGfwX:-NAUxtii9zaz4xdNGfwY:b-3iqg2o) ([raw file](https://github.com/quinoacomputing/quinoa/blob/de3ffef63b283d8e7206dd976e949a35781278cc/src/PDE/Limiter.cpp#L645)):*
> ```cpp
>         if(nmat > 1)
>           BoundPreservingLimiting(nmat, offset, ndof, e, inpoel, coord, U, phic,
>             phic_p2);
> ```

This seems incorrect. I thought we decided to use `intInd` to determine when BoundPreserving is supposed to be used. As it is right now, it does not apply BP when `intInd` is true
___
*[`src/PDE/Limiter.cpp` line 829 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAUyFFZAm5thhi50WMv:-NAUyFFZAm5thhi50WMw:brhumzt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/de3ffef63b283d8e7206dd976e949a35781278cc/src/PDE/Limiter.cpp#L829)):*
> ```cpp
>         if(nmat > 1)
>           BoundPreservingLimiting(nmat, offset, ndof, e, inpoel, coord, U,
>             phic_p1, phic_p2);
> ```

Same here.

**Review by WeizhaoLi2018 — COMMENTED** [review]
1. This is a bit tricky. I update the baseline for p0p1 since it failed at the beginning. But after updating the commit, I noticed that previously it failed only because I didn't add `shock_indetection false` in the control file. In other words, both the new baselines and old ones will pass the testcase and I confirmed that by going back to the old commits. But I am not sure what changed between the two binary files.
2. Yes, the `coeff` should be larger than 1e-6. If that's how we trigger shock-detector, we might need to change the default value for `coeff` to be 0. Right now it is 1. Am I correct?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-NAVAJSp2lVYB4rTuTvC:b2qkh70)* status: 17 of 76 files reviewed, 4 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[`src/PDE/Limiter.cpp` line 645 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAUxtii9zaz4xdNGfwX:-NAVB5NT4O8p5A9w17g_:b-5o31om) ([raw file](https://github.com/quinoacomputing/quinoa/blob/de3ffef63b283d8e7206dd976e949a35781278cc/src/PDE/Limiter.cpp#L645)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This seems incorrect. I thought we decided to use `intInd` to determine when BoundPreserving is supposed to be used. As it is right now, it does not apply BP when `intInd` is true
</blockquote></details>

I am confused here. Why do we apply BP when `intInd` is true. When `intInd` is true, the volume fraction will be reconstructed by THINC and it does not matter whether BP is applied. What we want here is to apply BP when `intsharp == 1` and `intInd` is false. Am I right?

**Review by adityakpandare — APPROVED** [review]
1. Okay, I understand. So the original baselines work- you just updated them and they actually don't have any differences. About the baseline-changes that git shows, I don't think git can diff baselines; it only detected that they were changed based on the file-metadata when you committed these files. Let's leave these baselines as they are.
2. Let's not change the `coeff` default, since the default behavior should be to use the shock detector. So, the current default of 1 is correct.
:lgtm: 

> Reviewed 1 of 10 files at r5, 1 of 1 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-:-NAeABLx0DTUOF9f7RKV:bka4ken)* status: 18 of 76 files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[`src/PDE/Limiter.cpp` line 645 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAUxtii9zaz4xdNGfwX:-NAe9CxP-kROeKR3TF-V:b-nliz23) ([raw file](https://github.com/quinoacomputing/quinoa/blob/de3ffef63b283d8e7206dd976e949a35781278cc/src/PDE/Limiter.cpp#L645)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I am confused here. Why do we apply BP when `intInd` is true. When `intInd` is true, the volume fraction will be reconstructed by THINC and it does not matter whether BP is applied. What we want here is to apply BP when `intsharp == 1` and `intInd` is false. Am I right?
</blockquote></details>

Thanks for the explanation. You're right- I got confused.
___
*[`src/PDE/Limiter.cpp` line 786 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/558#-NAe9f6656gAPXrwt0w3:-NAe9f6656gAPXrwt0w4:b-npbs9a) ([raw file](https://github.com/quinoacomputing/quinoa/blob/b52ae6ad884cb45340c0e9db4049a331ba1f68f5/src/PDE/Limiter.cpp#L786)):*
> ```cpp
>         // ensure a stable solution. Since the limiting strategy for third order
>         // solution will downgrade the accuracy to second order, the density,
>         // energy and pressure of minor material will not be limited.
> ```

Perfect! Thanks for adding this explanation!

**Pull request merged**
