### PR TITLE
New discretization scheme for Oversets

### PR DESCRIPTION
**Pull request by adityakpandare**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/593)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
:lgtm:

> Reviewed 25 of 28 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-:-NeFaQ2-AFTB5lfOsXhs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks fine. I only have a couple of minor observations.

> Reviewed 24 of 28 files at r1, 1 of 1 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-:-NeHX9BT4EuBYJ5QzjEM:b-epkkec)* status: all files reviewed, 7 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Inciter/OversetFE.hpp` line 36 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHT_tk07kN-CxvFwwh:-NeHT_tk07kN-CxvFwwi:b-2y0khx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L36)):*
> ```cpp
> #include "NodeDiagnostics.hpp"
> #include "Inciter/InputDeck/InputDeck.hpp"
> #include "Ghosts.hpp"
> ```

Ghosts, FluxCorrector likely unnecessary.
___
*[`src/Inciter/OversetFE.hpp` line 73 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHTqRtC_NGyFcnD5Y-:-NeHTqRtC_NGyFcnD5Y0:b-asoeep) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L73)):*
> ```cpp
>     //! Constructor
>     explicit OversetFE( const CProxy_Discretization& disc,
>       const CProxy_Ghosts& ghostsproxy,
> ```

I guess because of this ghost are needed. A better design might be to pass that into Discretization instead so node-centered schemes do not require it.
___
*[`src/Inciter/OversetFE.hpp` line 171 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHU6fm8qDRKhZJzpm8:-NeHU6fm8qDRKhZJzpm9:bws9zin) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L171)):*
> ```cpp
> 
>     //! Setup node-neighborhood (no-op)
>     void nodeNeighSetup() {}
> ```

Likely unnecessary.
___
*[`src/Inciter/OversetFE.cpp` line 34 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHUO9YErtfMja4dTK4:-NeHUO9YErtfMja4dTK5:bad60e9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L34)):*
> ```cpp
> #include "Around.hpp"
> #include "CGPDE.hpp"
> #include "Integrate/Mass.hpp"
> ```

Is this necessary?
___
*[`src/Inciter/OversetFE.cpp` line 94 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHUWiD4pb7UMXrUGdY:-NeHUWiD4pb7UMXrUGdZ:bbe26c1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L94)):*
> ```cpp
>   m_tp( m_u.nunk(), g_inputdeck.get< tag::discr, tag::t0 >() ),
>   m_finished( 0 ),
>   m_movedmesh( 0 ),
> ```

Probably part of ALE, if so, unnecessary.
___
*[`src/Inciter/OversetFE.cpp` line 1066 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHVMfv5ET-oEy6EzBS:-NeHVMfv5ET-oEy6EzBT:bed95ss) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L1066)):*
> ```cpp
> //! [Refine]
> void
> OversetFE::refine( const std::vector< tk::real >& l2res )
> ```

Leaving this as 'refine' now makes little sense. Did AMR also get removed from here? (Looks like.)
___
*[`tests/unit/Inciter/TestScheme.cpp` line 192 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHWZSp13aWU9B2rDgG:-NeHWZSp13aWU9B2rDgH:bqzchyu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/tests/unit/Inciter/TestScheme.cpp#L192)):*
> ```cpp
>   CProxy_Receiver::ckNew(
>     inciter::Scheme( inciter::ctr::SchemeType::OversetFE ), 3, "OversetFE" );
> }
> ```

Because of this test, https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/UnitTest/TUTSuite.hpp#L73 will also need to be increased to 5.

**Review by adityakpandare — COMMENTED** [review]
Thanks. I cannot get to a couple of your comments in time, but have pushed fixes for others.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-:-NeJI39G9UBAl7QwC-cr:boxgoo9)* status: 27 of 29 files reviewed, 7 unresolved discussions (waiting on @jbakosi)

___
*[`src/Inciter/OversetFE.hpp` line 36 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHT_tk07kN-CxvFwwh:-NeJFVbx47Ei_Tnhwd9E:b-n0ed3m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L36)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Ghosts, FluxCorrector likely unnecessary.
</blockquote></details>

Good point. See below.
___
*[`src/Inciter/OversetFE.hpp` line 73 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHTqRtC_NGyFcnD5Y-:-NeJFO9k1eQolYgihTTf:b-rr6r37) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L73)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I guess because of this ghost are needed. A better design might be to pass that into Discretization instead so node-centered schemes do not require it.
</blockquote></details>

Good point. I will get to this in a future revision, due to the time-crunch.
___
*[`src/Inciter/OversetFE.hpp` line 171 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHU6fm8qDRKhZJzpm8:-NeJFYGCCKgp0SM5AA53:bbdf4py) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.hpp#L171)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Likely unnecessary.
</blockquote></details>

This is needed since it is defined by the `Scheme` variant.
___
*[`src/Inciter/OversetFE.cpp` line 34 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHUO9YErtfMja4dTK4:-NeJGmWlAh2yNl6QuQ1R:b-v6w0vf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L34)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

You're right. Removed it.
___
*[`src/Inciter/OversetFE.cpp` line 94 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHUWiD4pb7UMXrUGdY:-NeJG1bL6W1WoZgMmSyg:b-xjdji) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L94)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Probably part of ALE, if so, unnecessary.
</blockquote></details>

This is for keeping track of whether the overset mesh moved. So it will be used.
___
*[`src/Inciter/OversetFE.cpp` line 1066 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHVMfv5ET-oEy6EzBS:-NeJG8xV-_vbiU5L7Dtm:baa2846) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L1066)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Leaving this as 'refine' now makes little sense. Did AMR also get removed from here? (Looks like.)
</blockquote></details>

Yes, AMR did get removed. Naming this "refine" doesn't make sense because of that, but is required, since the `Scheme` variant declares a `refine` broadcast (just like `nodeNeighSetup`). I can explore renaming it in the future.
___
*[`tests/unit/Inciter/TestScheme.cpp` line 192 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHWZSp13aWU9B2rDgG:-NeJI0To2TmsbQqQuZZL:b187b96) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/tests/unit/Inciter/TestScheme.cpp#L192)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Because of this test, https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/UnitTest/TUTSuite.hpp#L73 will also need to be increased to 5.
</blockquote></details>

Ah, I missed this. Thanks!

**Review by jbakosi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-:-NeJLe8l-XF6icziWDmX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[`src/Inciter/OversetFE.cpp` line 94 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHUWiD4pb7UMXrUGdY:-NeJLm7CAMAnyGtZrMH8:b-8q9pxi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L94)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This is for keeping track of whether the overset mesh moved. So it will be used.
</blockquote></details>

So you are planning to use this to indicate if other meshes have moved? If so, this is premature optimization. I would introduce it yet. But no big deal.
___
*[`src/Inciter/OversetFE.cpp` line 1066 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/593#-NeHVMfv5ET-oEy6EzBS:-NeJLzCy0X_fjbNpfw3d:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/74fd190678817b137dc68f77620b677e3975d951/src/Inciter/OversetFE.cpp#L1066)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yes, AMR did get removed. Naming this "refine" doesn't make sense because of that, but is required, since the `Scheme` variant declares a `refine` broadcast (just like `nodeNeighSetup`). I can explore renaming it in the future.
</blockquote></details>

Okay.

**Pull request merged**
