### PR TITLE
Multiple IC boxes

### PR DESCRIPTION
**Pull request by jbakosi**
This enables multiple IC boxes. Note that only ALECG is tested with IC boxes.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
I have one question: what would it take to get this to work with DG/multimat (other than code in DGMultiMat.hpp that initializes solutions based on the boxes specified by the user)? Other than that looks good!

> Reviewed 18 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-:-MYGM6943kiqjbtXQj3K:b-7i8n5v)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/PDE/ConfigureCompFlow.cpp, line 95 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-MXgcnYqEfDGJE3lJw0M:-MXgcnYqEfDGJE3lJw0N:bfos71i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9e06b63de982ee8c397325780092e9918e4a57c1/src/PDE/ConfigureCompFlow.cpp#L95)):*
> ```cpp
> 
>   auto ncomp = g_inputdeck.get< tag::component >().get< eq >()[c];
>   nfo.emplace_back( "number of components", parameter( ncomp ) );
> ```

Why the change from an ``std`` function to this?
___
*[tests/regression/inciter/compflow/Euler/SodShocktube/sod_shocktube_alecg_userdef.q, line 35 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-MYGLupO75ROwRfnoHRa:-MYGLupO75ROwRfnoHRb:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9e06b63de982ee8c397325780092e9918e4a57c1/tests/regression/inciter/compflow/Euler/SodShocktube/sod_shocktube_alecg_userdef.q#L35)):*
> ```q
>         density 1.0
>         pressure 1.0
>       end
> ```

Nice!

**Review by jbakosi — COMMENTED** [review]
I can't think of anything else, just the client code really. This now parses multiple boxes and it is available for DG too. It would be great if we started using this for any scheme and for any problem whose ICs can be given in terms of, potentially overlapping, boxes. I think we should start by converting Sod and, once it works, getting rid of the Sod problem class. (Maybe Sod is still good to keep, because we a rotated Sod shocktube -- that's probably not too easy to convert/rotate to use this, but perhaps others, like triple-point.)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-:-MYGvGXJ0e9zM1RWWPVA:b-irfgli)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/ConfigureCompFlow.cpp, line 95 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-MXgcnYqEfDGJE3lJw0M:-MYGuj8N0YxcKikIQFBP:b4uvxn6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9e06b63de982ee8c397325780092e9918e4a57c1/src/PDE/ConfigureCompFlow.cpp#L95)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why the change from an ``std`` function to this?
</blockquote></details>

I added a new function for outputting a single scalar, `parameter()`, besides the existing `parameters()` for outputting a vector. Both drive the values through a `std::stringstream`, which ensure uniform floating points formatting. `std::to_string()` wasn't using the same float formatting when the value was output.

**Review by adityakpandare — APPROVED** [review]
Yeah, agreed. I'll look into that soon. Thanks for putting this in!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-:-MYGxNJ-BLBT_RDEHmsN:balmyxc)* status: 18 of 28 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/PDE/ConfigureCompFlow.cpp, line 95 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-MXgcnYqEfDGJE3lJw0M:-MYGxDRs516w5ivl665P:b-fg9btw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9e06b63de982ee8c397325780092e9918e4a57c1/src/PDE/ConfigureCompFlow.cpp#L95)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I added a new function for outputting a single scalar, `parameter()`, besides the existing `parameters()` for outputting a vector. Both drive the values through a `std::stringstream`, which ensure uniform floating points formatting. `std::to_string()` wasn't using the same float formatting when the value was output.
</blockquote></details>

Makes sense. Thanks for the explanation

**Review by adityakpandare — APPROVED** [review]
> Reviewed 10 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Review by jbakosi — COMMENTED** [review]
Thanks for the extra pair of eyes!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/482#-:-MYHOEr81WNfPOgA7jrs:biv02us)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Pull request merged**
