### PR TITLE
Parallel DG nodal field otput

### PR DESCRIPTION
**Pull request by jbakosi**
See commit msgs for details. Only P1 for now.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/454)

### CODE REVIEW

**Review by adityakpandare — APPROVED** [review]
The DG node comm exit condition must've been a hard one to debug. Thanks a lot for putting this in!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/454#-:-MLKYdM_7MJWrJXJK8ow:ba3qk76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
It took 3 tries. The 3rd one was the simplest and the one that worked. ;-0 Thanks for the review.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/454#-:-MLKb2QX0qbFz_6RJAuG:b-bh9z16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by adityakpandare — APPROVED** [review]
Occam's razor... :wink: :lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/454#-:-MLKbRPB2uv6YejtHACW:blcycu1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
Yeah...

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/454#-:-MLKeVCIA5nsgH_DO3zT:b-teu7hm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Pull request merged**
