### PR TITLE
Multi-material DGP2 Implementation

### PR DESCRIPTION
**Pull request by WeizhaoLi2018**
This PR adds the multi-material DGP2 related code.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks for the hard work on this @weizhaoli2018. Test are passing. Could you remind me why the baselines for p0p1 had to be changed? I thought we did not change any discretization for p0p1. Also, I have a few other comments below.

> Reviewed 1 of 3 files at r3, 4 of 8 files at r4, 2 of 3 files at r5, 2 of 3 files at r6, 1 of 80 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzQPCeKEIeIfEjKyvJa:bguko3z)* status: 8 of 87 files reviewed, 11 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 1696 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQXHxb1PMRhKqTy4xN:-MzQXHxb1PMRhKqTy4xO:b-mpd2pn) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1696)):*
> ```cpp
>   const ncomp_t offset,
>   const std::size_t rdof,
>   const std::size_t e,
> ```

We do not need to add these `const`'s, because we're not passing refs, but creating copies (which is okay for these since they are `int`, and not large vectors/arrays). This is just a convention we follow in the rest of the code, so it might be better for uniformity.
___
*[src/PDE/Limiter.cpp, line 1699 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQXkmZ0Xcb0NaBcEJE:-MzQXkmZ0Xcb0NaBcEJF:b-lb53ei) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1699)):*
> ```cpp
>   tk::Fields& U,
>   [[maybe_unused]] tk::Fields& P,
>   std::vector< tk::real >& phic_p1, 
> ```

Could you remove the unnecessary whitespace after `phic_p1,`?
___
*[src/PDE/Limiter.cpp, line 1953 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQfLi69D8ub7Pc1K4W:-MzQfLi69D8ub7Pc1K4X:bbaxk3b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1953)):*
> ```cpp
>   if(ndof > 4)
>     for(std::size_t imat = 0; imat < nmat; imat++)
>       phic_p2[imat] = std::min(phi_bound[imat], phic_p2[imat]);
> ```

Remember that the size of `phic_p1` and `phic_p2` is `ncomp`. As I have pointed out before, whenever we index into a vector with size of `ncomp`, the `Idx()`  functions should be used. So, here `volfracIdx()` should be used to index into `phic_p1` and `phic_p2`. Please remember this for all future code changes.
___
*[src/PDE/Limiter.cpp, line 1976 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQb9L_6QoxQOtHG6-r:-MzQb9L_6QoxQOtHG6-s:brkgtf7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1976)):*
> ```cpp
>     phi = std::fabs( (min - al_avg) / (al_gp - al_avg) );
>   return phi;
> }
> ```

Nice! I like the code reuse because of this!
___
*[src/PDE/Limiter.cpp, line 2142 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQdcw759m8CegIZGIJ:-MzQdcw80plWoUS0YzuC:bin3pkx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L2142)):*
> ```cpp
>   for(std::size_t icomp = nmat; icomp < ncomp; icomp++)
>     phic_p1[icomp] = std::min( phic_bound[icomp], phic_p1[icomp] );
>   for(std::size_t icomp = 0; icomp < nmat; icomp++)
> ```

Why does this loop only go from 0 to `<nmat`? Do you mean to loop only over the material pressures? In that case the loop should go from `pressureIdx(nmat,0)` to `pressureIdx(nmat,nmat)`, right?
___
*[src/PDE/Limiter.cpp, line 2147 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQe2KU9qoPGLL8fBWZ:-MzQe2KU9qoPGLL8fBW_:bnyfwmg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L2147)):*
> ```cpp
>     for(std::size_t icomp = nmat; icomp < ncomp; icomp++)
>       phic_p2[icomp] = std::min( phic_bound[icomp], phic_p2[icomp] );
>     for(std::size_t icomp = 0; icomp < nmat; icomp++)
> ```

Same comment here.
___
*[src/PDE/Integrate/Boundary.cpp, line 267 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQMuCI3ULgRlVvxRco:-MzQMuCI3ULgRlVvxRcp:b-u3iqjt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Integrate/Boundary.cpp#L267)):*
> ```cpp
>     // Divergence of velocity multiples basis fucntion( d(uB) / dx )
>     for(std::size_t idof = 0; idof < ndof; idof++)
>       riemannDeriv[3*nmat+idof][el] += wt * fl[ncomp+nmat] * B_l[idof];
> ```

Just making sure: we're calculating this `riemannDeriv`, but it's not being used anywhere, correct?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-MzQNQ5z74XuK5kptHXA:b-hq1coz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
> ```cpp
>           for(std::size_t idir=0; idir<3; ++idir)
>             ncf[volfracIdx(nmat, k)][idof] += state[volfracIdx(nmat, k)] *
>               vriem[idir] * dBdx[idir][idof];
> ```

If this term is removed, is the discretization consistent, even for constant velocity situations?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 393 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MsauMCq2wWrzBtmPydF:-MsauMCq2wWrzBtmPydG:bflject) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf61e3f886d39b2c096e3658785c036b2616c583/src/PDE/MultiMat/DGMultiMat.hpp#L393)):*
> ```cpp
> 
>       auto neg_density = cleanTraceMultiMat(nielem, m_system, m_offset, geoElem,
>         nmat, unk, prim);
> ```

Will we have to modify `cleanTraceMultiMat()` to reset the P2-DOFs?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 488 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MsatslQ-nTUbhrIWdi7:-MsatslQ-nTUbhrIWdi8:b-e9q4j4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf61e3f886d39b2c096e3658785c036b2616c583/src/PDE/MultiMat/DGMultiMat.hpp#L488)):*
> ```cpp
> //    //! \param[in] uNodalExtrm Chare-boundary nodal extrema for conservative
> //    //!   variables
> //    //! \param[in] pNodalExtrm Chare-boundary nodal extrema for primitive
> ```

Let's uncomment the documentation for arguments that are now used.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 334 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQOHTj0ITHICngxNcw:-MzQOHTj0ITHICngxNcx:b-7o11pu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/MultiMat/DGMultiMat.hpp#L334)):*
> ```cpp
>           {
>             auto mark = k * ndof;
>             R[mark] += w * pri[k];
> ```

why not include `R[mark] += w * pri[k]` in the loop below?  That would eliminate the if-test, and result in cleaner code. Since `ndof` will be 1 for p0p1 and p0, that should do the right thing, correct?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 348 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQOee869vfn9Vx6Klm:-MzQOee999zq-YsGHe18:bcjzgxx) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/MultiMat/DGMultiMat.hpp#L348)):*
> ```cpp
>           auto mark = k * ndof;
>           auto rmark = k * rdof;
>           prim(e, rmark, 0) = R[mark] / L(e, mark, 0);
> ```

Same comment here. Why not include the above line in the loop below?

**Review by WeizhaoLi2018 — COMMENTED** [review]
That's a really good point. The reason that p0p1 tests faill is the changes in consistent limiting. I have included the energy term in consistent limiting. This can be verified by going back to previous commit and comment all the energy coefficients in consistent limiting. Once I tried that, all p0p1 tests will pass.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzRJu1A9I4cKYnOgkUf:bbspr3o)* status: 8 of 87 files reviewed, 11 unresolved discussions (waiting on @adityakpandare)

___
*[src/PDE/Limiter.cpp, line 1696 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQXHxb1PMRhKqTy4xN:-MzRKqk343qw30RQEGfu:bp8ti5w) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1696)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We do not need to add these `const`'s, because we're not passing refs, but creating copies (which is okay for these since they are `int`, and not large vectors/arrays). This is just a convention we follow in the rest of the code, so it might be better for uniformity.
</blockquote></details>

So do I need to remove the `const` here or just keep it here?
___
*[src/PDE/Limiter.cpp, line 1699 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQXkmZ0Xcb0NaBcEJE:-MzRLcOt48GC7bi4XZSb:bkm3y58) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1699)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you remove the unnecessary whitespace after `phic_p1,`?
</blockquote></details>

Done! Thanks for pointing this out.
___
*[src/PDE/Limiter.cpp, line 1953 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQfLi69D8ub7Pc1K4W:-MzRMKjn2v4bXakerKWU:bdxx1kl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1953)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Remember that the size of `phic_p1` and `phic_p2` is `ncomp`. As I have pointed out before, whenever we index into a vector with size of `ncomp`, the `Idx()`  functions should be used. So, here `volfracIdx()` should be used to index into `phic_p1` and `phic_p2`. Please remember this for all future code changes.
</blockquote></details>

Got it! Thanks!
___
*[src/PDE/Limiter.cpp, line 1976 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQb9L_6QoxQOtHG6-r:-MzRNMIm-o1EdxCTCETj:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1976)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice! I like the code reuse because of this!
</blockquote></details>

Thanks!
___
*[src/PDE/Limiter.cpp, line 2142 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQdcw759m8CegIZGIJ:-MzRNW-V5vs-0izniQBA:b-mwjv6x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L2142)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why does this loop only go from 0 to `<nmat`? Do you mean to loop only over the material pressures? In that case the loop should go from `pressureIdx(nmat,0)` to `pressureIdx(nmat,nmat)`, right?
</blockquote></details>

Yes, it only applies to material pressure. Just changed the index.
___
*[src/PDE/Limiter.cpp, line 2147 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQe2KU9qoPGLL8fBWZ:-MzRNyt-0cyWclRCMeRQ:b-896fja) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L2147)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same comment here.
</blockquote></details>

Done!
___
*[src/PDE/Integrate/Boundary.cpp, line 267 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQMuCI3ULgRlVvxRco:-MzRO0tN60_V7JwO4nw7:b1ouev1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Integrate/Boundary.cpp#L267)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Just making sure: we're calculating this `riemannDeriv`, but it's not being used anywhere, correct?
</blockquote></details>

We are using it. The first `3*nmat` terms represents the non-conservative term of partial pressure derivative and the rest `ndof` terms refer to derivatives of Riemann velocity times basis function.

You can check out to the `nonConservativeInt` function in `src/PDE/Integrate/MultiMatTerms.cpp` to see that we do use `riemannDeriv` there.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-MzRPDJy0ASCykuugm1a:b7rrxij) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

If this term is removed, is the discretization consistent, even for constant velocity situations?
</blockquote></details>

We remove this and make assumption that the derivative of Riemann velocity times basis function is constant. Therefore, when it is DGP1 with constant velocity, it will be consistent. While for DGP2 with constant velocity, there will be errors since the derivative of P2 basis is not constant.

Does this answer your question?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 393 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MsauMCq2wWrzBtmPydF:-MzRQQG7DVx2YkygdZe-:b-iroiao) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf61e3f886d39b2c096e3658785c036b2616c583/src/PDE/MultiMat/DGMultiMat.hpp#L393)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Will we have to modify `cleanTraceMultiMat()` to reset the P2-DOFs?
</blockquote></details>

I think we will need to. But I haven't tested it yet.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 488 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MsatslQ-nTUbhrIWdi7:-MzRQfky9Fot3b-sKuXx:b-896fja) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf61e3f886d39b2c096e3658785c036b2616c583/src/PDE/MultiMat/DGMultiMat.hpp#L488)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's uncomment the documentation for arguments that are now used.
</blockquote></details>

Done!
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 334 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQOHTj0ITHICngxNcw:-MzRQ2vj73oW5hcy3MDv:bww7g41) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/MultiMat/DGMultiMat.hpp#L334)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

why not include `R[mark] += w * pri[k]` in the loop below?  That would eliminate the if-test, and result in cleaner code. Since `ndof` will be 1 for p0p1 and p0, that should do the right thing, correct?
</blockquote></details>

Yes, you are right. It will be cleaner.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 348 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQOee869vfn9Vx6Klm:-MzRQNUt-3XepstHkV1n:b-896fja) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/MultiMat/DGMultiMat.hpp#L348)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same comment here. Why not include the above line in the loop below?
</blockquote></details>

Done!

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks @weizhaoli2018. A few minor comments, otherwise looks good to go.

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzVgnAm33aEcRbxHvjQ:b-rmw70r)* status: 8 of 87 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Limiter.cpp, line 1696 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQXHxb1PMRhKqTy4xN:-MzRXTpq9go7AewfsfPb:b-11ncq1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Limiter.cpp#L1696)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

So do I need to remove the `const` here or just keep it here?
</blockquote></details>

Yes, just remove the 4 consts above, so that it's uniform with the convention we follow.
___
*[src/PDE/Integrate/Boundary.cpp, line 267 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQMuCI3ULgRlVvxRco:-MzVf7J01oZkGmIcQqAR:b-3uwd0j) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Integrate/Boundary.cpp#L267)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

We are using it. The first `3*nmat` terms represents the non-conservative term of partial pressure derivative and the rest `ndof` terms refer to derivatives of Riemann velocity times basis function.

You can check out to the `nonConservativeInt` function in `src/PDE/Integrate/MultiMatTerms.cpp` to see that we do use `riemannDeriv` there.
</blockquote></details>

Understood. Thanks! Can we put in what the `riemannDeriv` terms represent as a comment in `DGMultiMat::rhs()` where `riemannDeriv` is declared?
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-MzVfscHC5gH5Wi_rnsK:b-dppf5b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

We remove this and make assumption that the derivative of Riemann velocity times basis function is constant. Therefore, when it is DGP1 with constant velocity, it will be consistent. While for DGP2 with constant velocity, there will be errors since the derivative of P2 basis is not constant.

Does this answer your question?
</blockquote></details>

Yes, that answers my question. Can we put this as a comment here in the code? In addition to what you wrote here, we can mention "this is does not affect high-order accuracy in single material regions for problems with sharp interfaces. This is because, for sharp interface problems high-order in volume fractions does not show any benefits over THINC. Therefore, for such problems, FV is used for volume fractions, and high-order terms do not need to be computed".
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 393 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MsauMCq2wWrzBtmPydF:-MzRYERN-c1GbP4rcu-K:b-837i3v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf61e3f886d39b2c096e3658785c036b2616c583/src/PDE/MultiMat/DGMultiMat.hpp#L393)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

I think we will need to. But I haven't tested it yet.
</blockquote></details>

Okay.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 334 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQOHTj0ITHICngxNcw:-MzRY8NF6oIwpG1tNIwx:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/MultiMat/DGMultiMat.hpp#L334)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Yes, you are right. It will be cleaner.
</blockquote></details>

Thanks!

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535)* status: 7 of 87 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Integrate/Boundary.cpp, line 267 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQMuCI3ULgRlVvxRco:-Mz_pXqT3VVx9CUj6k1H:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/6a1b2519c06dbaf24114060662b4a0ceb6de19a0/src/PDE/Integrate/Boundary.cpp#L267)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Just added the description in `DGMultiMat.hpp`. Thanks!
</blockquote></details>

Thanks!
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-Mz_v6AJDctXiWlD9pvD:b-swuep1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Done! Thanks
</blockquote></details>

I might have misunderstood your comment. I thought that we can get consistent results for DGP2 with constant velocity. This is important to demonstrate design order-of-accuracy, irght? How will we show that P2 is indeed 3rd order, if the discretization is not consistent even for constant velocity problems?

**Review by WeizhaoLi2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535)* status: 7 of 87 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-Mz_w2Ip2bVl1uTp7hcz:b-k2pvi0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I might have misunderstood your comment. I thought that we can get consistent results for DGP2 with constant velocity. This is important to demonstrate design order-of-accuracy, irght? How will we show that P2 is indeed 3rd order, if the discretization is not consistent even for constant velocity problems?
</blockquote></details>

First, if we run a test with volume fraction as constant and density as smooth advected solution. We get 3rd order accuracy even though there are errors appearing in P2-dofs discretization equation. As for volume fraction equation as smooth solution, we need to check it and see whether it's 3rd order or not.

Secondly, to improve it, we can do what Dr. Luo suggested that assume the derivative of Riemann velocity times basis function as high order polynomial (linear polynomial solution for DGP2). If we made it that way, mathematically speaking, the discretization form will be consistent for DGP2 with constant velocity.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535)* status: 7 of 87 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 219 at r7](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzQNQ5z74XuK5kptHX9:-MzpRSvP1tq47RzEP8pE:b817i2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/eb54ff37c274b348a127dc7b7e74a95cb112c839/src/PDE/Integrate/MultiMatTerms.cpp#L219)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

First, if we run a test with volume fraction as constant and density as smooth advected solution. We get 3rd order accuracy even though there are errors appearing in P2-dofs discretization equation. As for volume fraction equation as smooth solution, we need to check it and see whether it's 3rd order or not.

Secondly, to improve it, we can do what Dr. Luo suggested that assume the derivative of Riemann velocity times basis function as high order polynomial (linear polynomial solution for DGP2). If we made it that way, mathematically speaking, the discretization form will be consistent for DGP2 with constant velocity.
</blockquote></details>

Discussed off-line what to do here.
___
*[src/PDE/Integrate/MultiMatTerms.cpp, line 202 at r9](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-MzpPyrf5WA3torXElK6:-MzpPyrg3ym2WXytM3LX:bwusy2i) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9729bdcb29c6a4b20d272932fa7999956603a62d/src/PDE/Integrate/MultiMatTerms.cpp#L202)):*
> ```cpp
>         for(std::size_t idof=0; idof<ndof; ++idof)
>           ncf[volfracIdx(nmat, k)][idof] = state[volfracIdx(nmat, k)]
>                                          * riemannDeriv[3*nmat+idof][e] * B[idof];
> ```

The `B[idof]` should be removed, since the `riemannDeriv` is now `u*B`, not just `u`.

**Review by WeizhaoLi2018 — COMMENTED** [review]
After making the changes we talked in the morning, I have checked the DGP1 results of sod shocktube, water-air shocktube and shock-density wave testcases. They all look fine. And then update the DGP1 solution baseline.

Let me know if there is any question. Thanks!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzqFpv-7tPUZGqpUGio:bktx0k4)* status: 7 of 87 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — COMMENTED** [review]
Thanks @weizhaoli2018 :lgtm:

> Reviewed 1 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzqHx3g0NfVCV33HFxR:b5e3e9t)* status: 8 of 87 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
Updated comment. Please go ahead and merge.

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzqLXuE6kS8CmPSwcJ-:blpn50n)* status: 8 of 87 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/535#-:-MzqOyC90qXgBFwc_HzI:bnfp4nl)* status: 8 of 87 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
