### PR TITLE
Solid approx soundspeed

### PR DESCRIPTION
**Pull request by airaudofacundo**
Implemented approximated elastic speed of sounds contribution. Also changed rel_factor in stiff_rhs

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/622)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
I have one question. And I have also made some other changes that I thought are easier to do by myself.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-:-O1wLtws8tY3t9lG31ff:bknocjc)* status: all files reviewed, 1 unresolved discussion (waiting on @airaudofacundo)

___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 1135 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-O1wKvWh8jq5xj946O0A:-O1wKvWh8jq5xj946O0B:b-6zlo27) ([raw file](https://github.com/quinoacomputing/quinoa/blob/790ca9973e25bb69daeda6135596bac128064f8f/src/PDE/MultiMat/DGMultiMat.hpp#L1135)):*
> ```cpp
>             tk::real rel_factor = 0.0;
>             if (equiv_stress >= yield_stress)
>               rel_factor = 1.0e+07;
> ```

Is this required in the pull request?

**Review by adityakpandare — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/622)* status: all files reviewed, 1 unresolved discussion (waiting on @airaudofacundo)

___
*[`src/PDE/EoS/SmallShearSolid.cpp` line 550 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-O1wQdt00lnEaW4Xbl1F:-O1wQdt00lnEaW4Xbl1G:brtntki) ([raw file](https://github.com/quinoacomputing/quinoa/blob/412015d1a7abcd4333e16b1a1c55cd89ca95fc4b/src/PDE/EoS/SmallShearSolid.cpp#L550)):*
> ```cpp
>   // An interface-capturing Godunov method for the simulation of compressible
>   // solid-fluid problems. Journal of Computational Physics, 390, 25-50
>   tk::real a = (4.0/3.0) * m_mu * alpha / arho;
> ```

I made this change because it is better to multiply by volfrac, than divide the denominator by it. This is because volfrac can be zero, thereby leading to an FPE when dividing by it.

**Review by airaudofacundo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/622)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 1135 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-O1wKvWh8jq5xj946O0A:-O1wvv6m4UJI1lMFg8I3:b7seza2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/790ca9973e25bb69daeda6135596bac128064f8f/src/PDE/MultiMat/DGMultiMat.hpp#L1135)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is this required in the pull request?
</blockquote></details>

I would like to get rid of `rel_factor = yield_stress` because it's not really based on anything. But we can do it in a future change. Changed it back

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-:-O1x-F3U8Rveum2ReLVD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 1135 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/622#-O1wKvWh8jq5xj946O0A:-O1wzAP75_dbcFcS51Us:b-hqd4kg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/790ca9973e25bb69daeda6135596bac128064f8f/src/PDE/MultiMat/DGMultiMat.hpp#L1135)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

I would like to get rid of `rel_factor = yield_stress` because it's not really based on anything. But we can do it in a future change. Changed it back
</blockquote></details>

Makes sense. I just mentioned it because you are changing it in the other pull request https://github.com/quinoacomputing/quinoa/pull/620 too.

**Pull request merged**
