### PR TITLE
Point history output for DG

### PR DESCRIPTION
**Pull request by adityakpandare**
This commit adds point-history output for the DG methods. Let's do this one after https://github.com/quinoacomputing/quinoa/pull/456.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/457)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
We can review this one now that https://github.com/quinoacomputing/quinoa/pull/456 is merged.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/457#-:-MLmXQ626ZwtpXm5m2SV:bs142vj)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jbakosi)

**Review by jbakosi — APPROVED** [review]
Nice work! Good to go.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/457#-:-MLmsnZc4C2ha4s-vfv8:b-8fv5qi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
Thanks for the quick review!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/457#-:-MLmvWoZ7NDqVCIJqO2u:b-ncgzc2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by jbakosi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/457)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
