### PR TITLE
AMR derefinement fixes

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits posts a few fixes to the derefinement algorithm. Thanks @rfbird for your help with this! This does not completely fix derefinement, but is a good point to merge these changes in. After these changes, the following initial-refinement combinations work: `iid`, `iiid`, `iiiid`, `iiiiid`.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Thank you both for doing this incredible debugging! I have only a single comment, mostly because the changes simply blew over my head. I also push one commit in which I believe I fix the tests that fail, because we disconnected the output-based refinement/de-refinement, which is simply reconnecting it back. It should not affect anything else. Good to go!

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-:-MUjZ_qk85NJrrGchCWw:b-nwd93b)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @rfbird)

___
*[src/Inciter/AMR/mesh_adapter.cpp, line 107 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-MUieIx3ERwxZcBlBEid:-MUieIx3ERwxZcBlBEie:bp6bkjw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a05ab354acae8b9bd3f9cbaf2b966ddd7f973508/src/Inciter/AMR/mesh_adapter.cpp#L107)):*
> ```cpp
>          for (const auto& np_node : face) {
>            if (inactive_nodes.count(np_node) || inactive_nodes.count(np_node)
>              || inactive_nodes.count(np_node)) ++icount;
> ```

I don't see how this is not equivalent to
```
           if (inactive_nodes.count(np_node)) ++icount;

```
Also the loop
```
         for (const auto& np_node : face) {
           if (inactive_nodes.count(np_node) || inactive_nodes.count(np_node)
             || inactive_nodes.count(np_node)) ++icount;
```
can likely be exchanged with
```
auto icount = std::count_if( face.cbegin(), face.cend(), [](auto i){ return inactive_nodes.count(np_node); });
```

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @jbakosi and @rfbird)

___
*[src/Inciter/AMR/mesh_adapter.cpp, line 107 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-MUieIx3ERwxZcBlBEid:-MUjsvb5ANnatCv2z3iv:b7xvbtj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a05ab354acae8b9bd3f9cbaf2b966ddd7f973508/src/Inciter/AMR/mesh_adapter.cpp#L107)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I don't see how this is not equivalent to
```
           if (inactive_nodes.count(np_node)) ++icount;

```
Also the loop
```
         for (const auto& np_node : face) {
           if (inactive_nodes.count(np_node) || inactive_nodes.count(np_node)
             || inactive_nodes.count(np_node)) ++icount;
```
can likely be exchanged with
```
auto icount = std::count_if( face.cbegin(), face.cend(), [](auto i){ return inactive_nodes.count(np_node); });
```
</blockquote></details>

That's a funny if-condition! Good catch! I'll change it. I vote for the simpler for-loop though.

**Review by adityakpandare — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-:-MUjwPDP3dJfbMg6Ur8j:b-ucfknh)* status: 11 of 18 files reviewed, 1 unresolved discussion (waiting on @jbakosi and @rfbird)

**Review by jbakosi — APPROVED** [review]
No, thank you. Hopefully this is now not too far from being useful already.

> Reviewed 1 of 1 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-:-MUj_BsTA2z4BAJp49jT:bkedae4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

___
*[src/Inciter/AMR/mesh_adapter.cpp, line 107 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-MUieIx3ERwxZcBlBEid:-MUjxCfl1tkJwMKwefpW:bawmj4q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/a05ab354acae8b9bd3f9cbaf2b966ddd7f973508/src/Inciter/AMR/mesh_adapter.cpp#L107)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

That's a funny if-condition! Good catch! I'll change it. I vote for the simpler for-loop though.
</blockquote></details>

Sounds good. Such things should only make a difference for large containers anyway.

**Review by adityakpandare — COMMENTED** [review]
:crossed_fingers: 

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474#-:-MUjyCZg1Ec1QhGKsyF-:b-kev0sl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

**Review by jbakosi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/474)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

**Pull request merged**
