### PR TITLE
Note on archive www

### PR DESCRIPTION
**Pull request by jbakosi**
Add a note on the main page pointing to the new archival web site, already alive at https://quinoacomputing.org/archive.

Also add couple of minor updates to docs and testing flags.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532)

### CODE REVIEW

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532#-:-MpmkSACCw318-t5Y7wj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Review by adityakpandare — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 38 of 38 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[doc/pages/papers.dox, line 60 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/532#-MpwB_RUAOP0mTtw7Ial:-MpwB_RVAE9b4puVmvYf:bl6776t) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dfc2d0e79fc8e13c728e489d1b678834f526371f/doc/pages/papers.dox#L60)):*
> ```
>   equation whose invariant is beta can be found in walker::Beta,
>   walker::NumberFractionBeta, walker::MassFractionBeta,
>   walker::MixNumberFractionBeta, and walker::MixMassFractionBeta.
> ```

We shouldn't remove the papers. We can say that these papers are related to walker, which is not a part of quinoa anymore. But the papers themselves were published using quinoa (or quinoa inherited from them) at that time.

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532)* status: 41 of 42 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[doc/pages/papers.dox, line 60 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/532#-MpwB_RUAOP0mTtw7Ial:-MpwFZF59BC831pEIWmW:b-6iuaxw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dfc2d0e79fc8e13c728e489d1b678834f526371f/doc/pages/papers.dox#L60)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We shouldn't remove the papers. We can say that these papers are related to walker, which is not a part of quinoa anymore. But the papers themselves were published using quinoa (or quinoa inherited from them) at that time.
</blockquote></details>

Yeah, I agree. Just put it back.

**Review by adityakpandare — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/532)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[doc/pages/papers.dox, line 60 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/532#-MpwB_RUAOP0mTtw7Ial:-MpwGqy-EjkVoQC6omsa:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/dfc2d0e79fc8e13c728e489d1b678834f526371f/doc/pages/papers.dox#L60)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, I agree. Just put it back.
</blockquote></details>

Thanks!

**Pull request merged**
