### PR TITLE
Nodal field output for DG

### PR DESCRIPTION
**Pull request by jbakosi**
Not completely finished, but in good shape and nodal output looks good up to P1 including refined field output meshes. No regression tests yet, because of the lack of a class that will tie user-input and field output. Will do that soon, but first finish the following, in this order:

1. Parallel nodal field output
2. P2 nodal field output (both normal and refined)
3. pDG (for now only saves cell-center averages for nodal output, this should incorporate all higher DOFs)
4. Regression tests (only when user-input field class is in place, otherwise cumbersome as all existing DG regression test baselines would have to be updated)

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 11 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 375 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexWdu9MTsOmi5WxhX:-MKexWdu9MTsOmi5WxhY:b-rm8mh0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.hpp#L375)):*
> ```cpp
>       std::map< int, std::vector< std::size_t > > bface;
>       void pup( PUP::er& p ) { p|chunk; p|coord; p|triinpoel; p|bface; }
>     } m_outmesh;
> ```

Should we add a short comment on what this struct holds?
___
*[src/Inciter/DG.cpp, line 1233 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeaIYm8rNyXZEk6K7Z:-MKeaIYm8rNyXZEk6K7_:b-o9yt0k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1233)):*
> ```cpp
> 
> void
> DG::startout( CkCallback c )
> ```

Could we rename this to something more explanatory, like `startFieldOutput`?
___
*[src/Inciter/DG.cpp, line 1365 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeaRcoBOZS4mGqLWZD:-MKeaRcoBOZS4mGqLWZE:b-t7jom6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1365)):*
> ```cpp
> 
> void
> DG::extract(
> ```

Could we rename this too? It's difficult to guess what `extract` means here. Maybe `calculateFieldOutputVars()`?
___
*[src/Inciter/DG.cpp, line 1442 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKebSLnE050GfdAppgC:-MKebSLoDl5fM5d5J65n:b-3o5vpk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1442)):*
> ```cpp
> 
> std::tuple< tk::Fields, tk::Fields >
> DG::solution( const std::vector< std::size_t >& inpoel,
> ```

Maybe `evalSolution()`?
___
*[src/Inciter/DG.cpp, line 1476 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKecjbZ9U8QAltrcEgA:-MKecjbZ9U8QAltrcEgB:b-vbbp60) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1476)):*
> ```cpp
> 
> //  // Evaluate DG solution on potentially refined mesh
> //  auto eval = ()[]{};
> ```

Any reason why this commented code is still in here?
___
*[src/Inciter/DG.cpp, line 1549 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKejm5k54DjaHkpHJ-n:-MKejm5l282HDfZhXj-O:bykzhrj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1549)):*
> ```cpp
>       std::array< real, 3 > h{{cx-cp[0][0], cy-cp[0][1], cz-cp[0][2] }};
>       auto B = tk::eval_basis( ndof, dot(Jp[0],h), dot(Jp[1],h), dot(Jp[2],h) );
>       auto chu = eval_state( uncomp, 0, rdof, ndof, parent, m_u, B );
> ```

Can we put in a comment before this line of code, explaining that `chu` and `chp` are cell-center solutions for the child?
___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKexAk1EhIBMEGJYSkP:bdttbvu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
> ```cpp
>   const auto& triinpoel = m_outmesh.triinpoel;
>   Disc()->write( inpoel, m_outmesh.coord, m_outmesh.bface, {},
>                  tk::remap( triinpoel, lid ), elemfieldnames, nodefieldnames,
> ```

Is `nodefieldnames` assigned values?
___
*[src/Inciter/DG.cpp, line 2215 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeb7thDpkHO6Tyf5bk:-MKeb7ti5VkySwjShben:b-b0y1y2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2215)):*
> ```cpp
> 
> void
> DG::comnod( int /*fromch*/ )
> ```

For DG, it's hard to guess why nodal solution is required. Could we rename this function to something that indicates it's used for nodal outputs, like `comnodaloutput()`?
___
*[src/PDE/Reconstruction.cpp, line 552 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeYnWSADHlvo1hG---:-MKeYnWSADHlvo1hG--0:beieial) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/Reconstruction.cpp#L552)):*
> ```cpp
> 
> void
> tk::nodeAvg( std::size_t ncomp,
> ```

This function doesn't have anything to do with what we mean by solution reconstruction in this file. Could we place this in a field-output related file?
___
*[src/PDE/Reconstruction.cpp, line 610 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeY2XP8eFMB9drKMKw:-MKeY2XP8eFMB9drKMKx:b-b23l3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/Reconstruction.cpp#L610)):*
> ```cpp
> 
> std::tuple< tk::Fields, tk::Fields >
> tk::nodeEval( std::size_t offset,
> ```

Same with this function.
___
*[src/PDE/MultiMat/Problem/FieldOutput.cpp, line 183 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MK_zcljCffIUH__iOiV:-MK_zcljCffIUH__iOiW:b-parnki) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/MultiMat/Problem/FieldOutput.cpp#L183)):*
> ```cpp
> 
>   //  out[4*nmat+7][i] = geoElem(i,4,0) / (std::fabs(vn) + a);
>   //}
> ```

Just curious, why were these commented out?

**Review by adityakpandare — COMMENTED** [review]
Thanks for adding this functionality @jbakosi. I have a few comments/questions.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-:-MKexcdKBj_3rPqXu7SP:bp0mkq2)* status: all files reviewed, 11 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 11 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 375 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexWdu9MTsOmi5WxhX:-MKjszjl7J7EXnQ7ek4U:b-7yur7y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.hpp#L375)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Should we add a short comment on what this struct holds?
</blockquote></details>

Yep, thanks for the reminder.
___
*[src/Inciter/DG.cpp, line 1233 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeaIYm8rNyXZEk6K7Z:-MKjt2_93sGdoyKojkKs:b-b35qla) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1233)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could we rename this to something more explanatory, like `startFieldOutput`?
</blockquote></details>

Sure, good idea.
___
*[src/Inciter/DG.cpp, line 1365 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeaRcoBOZS4mGqLWZD:-MKjtL0OAOfDrUWoT4Me:b-wh31ee) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1365)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could we rename this too? It's difficult to guess what `extract` means here. Maybe `calculateFieldOutputVars()`?
</blockquote></details>

Sure, but how about `extractFieldOutput()`?
___
*[src/Inciter/DG.cpp, line 1442 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKebSLnE050GfdAppgC:-MKjtQnqDPBzYd7eIZEh:b-ljwy20) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1442)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Maybe `evalSolution()`?
</blockquote></details>

Uh! This was actually an _overload_. Not very good naming...
___
*[src/Inciter/DG.cpp, line 1476 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKecjbZ9U8QAltrcEgA:-MKk0taQ22P3VFzwj_F-:b-dcf7xz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1476)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Any reason why this commented code is still in here?
</blockquote></details>

Yeah, I forgot to remove it. ;-)
___
*[src/Inciter/DG.cpp, line 1549 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKejm5k54DjaHkpHJ-n:-MKk1Ww9Crjk_jl23Aob:b-u4vr3j) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1549)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Can we put in a comment before this line of code, explaining that `chu` and `chp` are cell-center solutions for the child?
</blockquote></details>

Isn't the comment two lines above the same?
```
// Compute solution in child centroid
```
___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKk2Egs81l7aZA36XSA:b-ght83w) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is `nodefieldnames` assigned values?
</blockquote></details>

I'm not sure what you mean...
___
*[src/Inciter/DG.cpp, line 2215 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeb7thDpkHO6Tyf5bk:-MKk2LuSAJn7sM4TUeiW:bdcv6l8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2215)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

For DG, it's hard to guess why nodal solution is required. Could we rename this function to something that indicates it's used for nodal outputs, like `comnodaloutput()`?
</blockquote></details>

Good point.
___
*[src/PDE/Reconstruction.cpp, line 552 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeYnWSADHlvo1hG---:-MKk2zrRAPpwHkOJs8fr:bkmq3mi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/Reconstruction.cpp#L552)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This function doesn't have anything to do with what we mean by solution reconstruction in this file. Could we place this in a field-output related file?
</blockquote></details>

Yeah, you are right and good idea.
___
*[src/PDE/Reconstruction.cpp, line 610 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeY2XP8eFMB9drKMKw:-MKk5YIQ4CT580zFUVnL:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/Reconstruction.cpp#L610)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same with this function.
</blockquote></details>

Done.
___
*[src/PDE/MultiMat/Problem/FieldOutput.cpp, line 183 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MK_zcljCffIUH__iOiV:-MKk5_-X2GTIG0z2E0Jt:b-502tpk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/MultiMat/Problem/FieldOutput.cpp#L183)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Just curious, why were these commented out?
</blockquote></details>

Because I changed the signature of `MultiMatFieldOutput()` to _not_ take `geoElem`, because instead of passing `geoElem` and taking out the cell centers, I wanted to generalize the calling function, `dg::MultiMat::fieldOutput()`, by passing the coordinates at which the output is extracted, so it can be reused for both element and node output. I expect this to go away (take a different form) once the class will be in place that ties user-input and field output.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/DG.hpp, line 375 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexWdu9MTsOmi5WxhX:-MKkBSfO8DzY2dv8uZ-U:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.hpp#L375)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yep, thanks for the reminder.
</blockquote></details>

Thanks!
___
*[src/Inciter/DG.cpp, line 1365 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKeaRcoBOZS4mGqLWZD:-MKkBbSn7vxq5h5QredP:b-fdkldo) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1365)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Sure, but how about `extractFieldOutput()`?
</blockquote></details>

That works too. Thanks!
___
*[src/Inciter/DG.cpp, line 1476 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKecjbZ9U8QAltrcEgA:-MKkBiNF6qUoNkGukdas:bsbjl8v) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1476)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, I forgot to remove it. ;-)
</blockquote></details>

Hah! Thanks!
___
*[src/Inciter/DG.cpp, line 1549 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKejm5k54DjaHkpHJ-n:-MKkBnww6kroCyT2R4vL:b-xuzi09) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L1549)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Isn't the comment two lines above the same?
```
// Compute solution in child centroid
```
</blockquote></details>

My bad, should've read properly ;-)
___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKkBsgb08rhZjDSTZiF:b-h1oomd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

I'm not sure what you mean...
</blockquote></details>

I meant to ask if `nodefieldnames` has been initialized/assigned the correct values. I see the declaration, but I don't see it being assigned values anywhere, like `elemfieldnames` is given values `fieldNames()`. Should we be uncommenting the code (`nodefieldnames.insert( end(nodefieldnames), begin(nn), end(nn) )`)?
___
*[src/PDE/MultiMat/Problem/FieldOutput.cpp, line 183 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MK_zcljCffIUH__iOiV:-MKkFRI93rgw_dK899ms:bu7n0ao) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/MultiMat/Problem/FieldOutput.cpp#L183)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Because I changed the signature of `MultiMatFieldOutput()` to _not_ take `geoElem`, because instead of passing `geoElem` and taking out the cell centers, I wanted to generalize the calling function, `dg::MultiMat::fieldOutput()`, by passing the coordinates at which the output is extracted, so it can be reused for both element and node output. I expect this to go away (take a different form) once the class will be in place that ties user-input and field output.
</blockquote></details>

Ah okay. So we plan to put this back in once the field-output class is established? I ask because the time-step field output is a very useful tool for debugging in multimat.

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKk_AR4EheNbwuoBbru:b-arzbft) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I meant to ask if `nodefieldnames` has been initialized/assigned the correct values. I see the declaration, but I don't see it being assigned values anywhere, like `elemfieldnames` is given values `fieldNames()`. Should we be uncommenting the code (`nodefieldnames.insert( end(nodefieldnames), begin(nn), end(nn) )`)?
</blockquote></details>

Oh, yeah. That is there in a few lines above, but commented because then that goes into the outputfile and all DG regression tests fail because the number of field names will not match that of the baselines. This will be fixed when I add the new class that ties user input and field output because it will be configurable and the existing regression tests will configure elem field output only, and I will also add node field output tests.
___
*[src/PDE/MultiMat/Problem/FieldOutput.cpp, line 183 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MK_zcljCffIUH__iOiV:-MKk_hSwCMzWzTDGcUVR:bor8bh7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/MultiMat/Problem/FieldOutput.cpp#L183)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Ah okay. So we plan to put this back in once the field-output class is established? I ask because the time-step field output is a very useful tool for debugging in multimat.
</blockquote></details>

Yeah, I want to put it back.

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKkagcF34Pvy2J-uNDR:bbp01an) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Oh, yeah. That is there in a few lines above, but commented because then that goes into the outputfile and all DG regression tests fail because the number of field names will not match that of the baselines. This will be fixed when I add the new class that ties user input and field output because it will be configurable and the existing regression tests will configure elem field output only, and I will also add node field output tests.
</blockquote></details>

So currently, when the output file is opened in paraview, how are the nodal-fields named?
___
*[src/PDE/MultiMat/Problem/FieldOutput.cpp, line 183 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MK_zcljCffIUH__iOiV:-MKkap2T3UGYZtOOt5ik:bvr53sf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/PDE/MultiMat/Problem/FieldOutput.cpp#L183)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah, I want to put it back.
</blockquote></details>

Okay. Thanks for the clarification!

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKkbV4g-JAOo5RsTaUr:b-lwg2dh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

So currently, when the output file is opened in paraview, how are the nodal-fields named?
</blockquote></details>

They are the same as the elem-centered ones, but/and exodus/paraview recognizes them as different fields because they are nodal. This is because I simply call the same function, `fieldOutput()` as well as `fieldNames()` from within `nodeFieldOutput()` and `nodalFieldNames()`, respectively. So basically just piggybacking on the existing the element output. This is neither final nor desirable, because it is too restrictive, but okay for now for putting in the nodal output. 

But the regression tests fail because even the number of fields in the output files will not be the same as that of the baselines, so exodiff fails. There is probably a way to make exodiff ignore the extra nodal fields, but that will not be necessary once the new class is in place, which I will do next (after I got the parallel nodal output working - without testing).

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-:-MKkecMNBris-rxHBNXH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 2210 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/452#-MKexAk1EhIBMEGJYSkO:-MKkeTs37fWTzg-aO9qG:b-pw3f9l) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9adbfa330d00abe02e3a69fa51bf217d4c183a2f/src/Inciter/DG.cpp#L2210)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

They are the same as the elem-centered ones, but/and exodus/paraview recognizes them as different fields because they are nodal. This is because I simply call the same function, `fieldOutput()` as well as `fieldNames()` from within `nodeFieldOutput()` and `nodalFieldNames()`, respectively. So basically just piggybacking on the existing the element output. This is neither final nor desirable, because it is too restrictive, but okay for now for putting in the nodal output. 

But the regression tests fail because even the number of fields in the output files will not be the same as that of the baselines, so exodiff fails. There is probably a way to make exodiff ignore the extra nodal fields, but that will not be necessary once the new class is in place, which I will do next (after I got the parallel nodal output working - without testing).
</blockquote></details>

Okay, thanks for explaining this to me. That answers my question.

**Pull request merged**
