### PR TITLE
Improved field output

### PR DESCRIPTION
**Pull request by jbakosi**
This addresses https://quinoacomputing.org/roadmap.html#roadmap_inciter_fieldoutput.

Plan
=====
Current:
----------
```python
plotvar
  filetype exodusii # root
  interval 5
  refined true # false
  sideset 1 2 3 end
end

history
  interval 5
  precision 8   # max
  format scientific     # fixed
  point p1 0.1 0.05 0.025 end
  point p2 0.9 0.05 0.025 end
end
```
Proposed:
--------
```python
field_output
  var
    # variable requests, see below
  end
  filetype exodusii # root
  interval 5
  refined true # false
  sideset 1 2 3 end
end

history_output
  var
    # variable requests, see below
  end
  interval 5
  precision 8   # max
  format scientific     # fixed
  point p1 0.1 0.05 0.025 end
  point p2 0.9 0.05 0.025 end
end

# Example prereququisites for variable requests in all var ... end blocks

compflow
  depvar u
end

multimat
  # still require a depvar for multimat: used, e.g., as refvar, but depvar not
  # used for requesting physics output variables (depvar-based outvars),
  # instead use characters as labels for physics variables augmented by
  # material index:
  #   d - density, e.q., D2 - density of 2nd material (see below why uppercase)
  #   f - volfrac
  #   l,m,n - momentum
  #   e - total specific energy
  #   u,v,w - velocity
  #   p - material pressure
end

transport
  depvar y
  ncomp 5
end

# Variable requests recognized in all var ... end blocks

var
  # simple user requests for (default) node centered quantities
  density
  pressure

  # simple user requests for elem centered quantities
  elem density  # same as 'density', since elem-centered is the default
  elem pressure # same as 'pressure'
  elem density pressure # request density and pressure in elements

  # use aliases (custom names only known to user)
  density "rho"         # 'rho' goes into the output file instead 'density'
  pressure "P0"         # 'P0' goes into the output file instead 'pressure'
  U2 "x-momentum"       # 'x-momentum' goes into the output fiel instead of 'U2'
  elem U5 "E"           # save total specific energy labelled as 'E'

  # advanced user requests for (default) node centered quantities
  U1    # (instantaneous, since capital) density
  U2    # (instantaneous, since capital) velocity
  U3
  U4
  U5    # (instantaneous, since capital) total energy
  internal_energy       # instantaneous by default for built-in aliases
  pressure

  # simple user requests for node centered quantities
  node density  # same as 'denstiy' since node centered output is the default
  node internal_energy

  # advanced user request for elem and node centered quantities
  node u2 node u4  # x velocity in nodes, z velocity in nodes
  node u2 u4       # arbitrary number of variables after 'node' or 'elem'
  elem u2 u5       # x velocity and total energy in elements

  # (future) advanced user request for elem and node centered instantaneous
  # quantities and their statistics (in turbulent flows)
  <u2u2> <u3u3> <u4u4>  # trace of Reynolds stress in nodes (default)
  elem <u2y>    # scalar flux in x direction in elements
  node <y1y3>   # covariance of Y1 and Y3 scalars in nodes
  node <U5y3y1> # triple correlation of (the full, not the fluctuating)
                # total energy, the 3rd and 1st transported scalars in nodes
  elem <U1>     # mean density in elements

  # multimat: material-id-based variable requests
  D1    # (instantaneous) density of material 1
  F3    # (instantaneous) volume fraction of 3rd material
  P2    # (instantaneous) pressure of 2nd material

  # (future) multimat turbulence
  <d1d1>        # density variance of 1st material in nodes
  elem <u2u2> <v2v2> <w2w2> # Reynolds stress of material 2 in elements
end
```

Only field output is hooked up at this point, but that works with all 3 hydro schemes for normal and refined field output as well as elem-, and node-centered outputs. The plan is to use the same/similar configuration machinery for history and diagnostics output as well.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/458)

### CODE REVIEW

**Comment by jbakosi** [comment]
I have addressed all we discussed, except a new doc page on how to use this. Will do that later. Thanks @adityakpandare!

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks for making these improvements in the inputfile parsing, and for taking the time to explain the code to me! Looks good. I just have one question.

> Reviewed 127 of 221 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-:-MMw1eze-AmzxPUQFo-g:b-jnxld8)* status: 127 of 221 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @jbakosi)

___
*[tests/regression/inciter/multimat/InterfaceAdvection/interface_advection_dg.q, line 56 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-MMvs7vtEQN8DgmUFMqT:-MMvs7vtEQN8DgmUFMqU:b-vob8el) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cb8cefe93728eba3c3339ee9ed66c02b49d6d3ad/tests/regression/inciter/multimat/InterfaceAdvection/interface_advection_dg.q#L56)):*
> ```q
> 	pressure "pressure_numerical" # bulk presssure
> 	specific_total_energy "total_energy_density_numerical"  # bulk specific total energy
>     end
> ```

Looks nice!
___
*[tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-MMvr_au5k9tOMvSJXGa:-MMvr_au5k9tOMvSJXGb:b-bua5jd) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cb8cefe93728eba3c3339ee9ed66c02b49d6d3ad/tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q#L24)):*
> ```q
> 
>   field_output
>     interval 1
> ```

What is output in the exo file if the var...end block is not specified?

**Review by jbakosi — COMMENTED** [review]
Sure, it's been fun! ;-)

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-:-MMwUWQT2eHsxikoYJl6:b-tq2hta)* status: 127 of 221 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-MMvr_au5k9tOMvSJXGa:-MMwURoS-K6GCAtndYcv:bj67zml) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cb8cefe93728eba3c3339ee9ed66c02b49d6d3ad/tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q#L24)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

What is output in the exo file if the var...end block is not specified?
</blockquote></details>

Nothing. ;-)

**Review by adityakpandare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/458)* status: 127 of 221 files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/458#-MMvr_au5k9tOMvSJXGa:-MMwVu1Y6STIMFU-8mj1:b-89q77k) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cb8cefe93728eba3c3339ee9ed66c02b49d6d3ad/tests/regression/inciter/transport/SlotCyl/slot_cyl_dgp1.q#L24)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Nothing. ;-)
</blockquote></details>

Cool.

**Pull request merged**
