### PR TITLE
manufactured solution problem

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits adds the following:
1. manufactured solution (MS) problem for multimaterial PDEs.
2. general sized source term, that is required for the MS.
3. keyword to disable consistent limiting and cleanTraceMaterial() so that design order-of-accuracy can be obtained for MS.
4. subsonic outlet BC for multimat.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/545)

### CODE REVIEW

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
Everything looks fine. Just a few questions below.
Thank you!

> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-:-N--kePB790FNQVSPPFb:b-7t0v9l)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[src/Control/Keywords.hpp, line 7133 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kAjmDwqwD8hrxFhB:-N--kAjmDwqwD8hrxFhC:b-8rir7g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/Control/Keywords.hpp#L7133)):*
> ```cpp
> using limiter = keyword< limiter_info, TAOCPP_PEGTL_STRING("limiter") >;
> 
> struct accuracy_test_info {
> ```

So if we want to run accuracy test later, just add one line in the control file as:
`accuracy_test true`.
Is it how it works?
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 526 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kZ6T40mV1kcK_z_Z:-N--kZ6T40mV1kcK_z__:bv700di) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/PDE/MultiMat/DGMultiMat.hpp#L526)):*
> ```cpp
>           pNodalExtrm, U, P, nmat, shockmarker );
>       }
>       else if (limiter != ctr::LimiterType::NOLIMITER)
> ```

Why we add this if here specifically for MultiMat?

**Review by adityakpandare — COMMENTED** [review]
Thanks for the quick review @weizhaoli2018. Let me know if I've answered your questions.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-:-N--m1P31rgEYsEZtV7s:b-yb56q3)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/Control/Keywords.hpp, line 7133 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kAjmDwqwD8hrxFhB:-N--leJXEWqmjAc0cXU9:b8pei5l) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/Control/Keywords.hpp#L7133)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

So if we want to run accuracy test later, just add one line in the control file as:
`accuracy_test true`.
Is it how it works?
</blockquote></details>

Yes, that's right.
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 526 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kZ6T40mV1kcK_z_Z:-N--ll2Q0H_SU0WLPJ08:b-pmf2d2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/PDE/MultiMat/DGMultiMat.hpp#L526)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Why we add this if here specifically for MultiMat?
</blockquote></details>

I wanted to run the MS problem without any limiter, hence had to add this condition, so that the error in the following lines wouldn't throw.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/545)* status: all files reviewed, 2 unresolved discussions (waiting on @WeizhaoLi2018)

___
*[src/Control/Keywords.hpp, line 7133 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kAjmDwqwD8hrxFhB:-N--mBDE0NciCfjGA-2P:bix6fps) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/Control/Keywords.hpp#L7133)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Yes, that's right.
</blockquote></details>

Also, this line should be in the `inciter...end` block, not in the `compflow` or `multimat` blocks.

**Review by WeizhaoLi2018 — APPROVED** [review]
It looks fine. Let's merge this.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-:-N--ncL12i0QR6zXzBHU:b-b9ixmh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[src/Control/Keywords.hpp, line 7133 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kAjmDwqwD8hrxFhB:-N--n4TmBzuByymY67Mj:b-l4yo36) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/Control/Keywords.hpp#L7133)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Also, this line should be in the `inciter...end` block, not in the `compflow` or `multimat` blocks.
</blockquote></details>

Got it. It should be similar to limiter option.
Thanks!
___
*[src/PDE/MultiMat/DGMultiMat.hpp, line 526 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/545#-N--kZ6T40mV1kcK_z_Z:-N--nRs41-cjgF4KxDNl:b-cks33x) ([raw file](https://github.com/quinoacomputing/quinoa/blob/e1d3ec57670677543a87c7ca640bb7ee2070bda2/src/PDE/MultiMat/DGMultiMat.hpp#L526)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I wanted to run the MS problem without any limiter, hence had to add this condition, so that the error in the following lines wouldn't throw.
</blockquote></details>

I see. It seems that Transport and Compflow does not have this error alert. So that's why we need if here for MultiMat.
Thanks!

**Pull request merged**
