### PR TITLE
Cleanup in the multimaterial algorithm

### PR DESCRIPTION
**Pull request by adityakpandare**
Cleans up some of the multimat algorithm:
1. Remove WENO limiter option for multimat, since it is no longer supported;
2. Reconstruction: the DGMultiMat::reconstruct() function no longer uses face-based reconstructions. This is because face-based LS-reconstructions can be unstable due to ill-posed LS problems. They also led to needlessly complicated code, since node-based LS was needed for the THINC reconstruction, leading to a few difficult-to-follow if-tests and such. Uniformly using node-based LS reconstructions leads to a stable algorithm, and cleaner code.
3. Remove primitive-var boundary contribution for LS reco, since it was only used for face-based reconstruction of multimat primitive quantities: this is not used anymore.
4. This code change requires updating the baselines for multimat-p0p1 because of the change in stencil (nodal-stencil) for the LS reconstruction. The solutions change, albeit not visibly enough. Also tested the 4-material gas-impact problem (https://quinoacomputing.org/inciter_example_gasimpact_4mat.html) after this code change, and confirmed correctness of the solution.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/500)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
Alright, thanks for the detailed description of the changes. Removes a bunch of code. Great! Looks good. Sorry for the delay on this.

> Reviewed 52 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/500#-:-Me0n1JbA8QAoHoY45v_:bj13ee0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by WeizhaoLi2018 — APPROVED** [review]
> Reviewed 5 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
No problem; I'll merge this as soon as the tests pass. Thanks!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/500#-:-MdNbYfq8vXmUG18j_7J:bfjedu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Review by jbakosi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
