### PR TITLE
AMR WIP

### PR DESCRIPTION
**Pull request by jbakosi**
Recent WIP towards a working AMR, some derefinement improvements and adding regression tests.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/444)

### CODE REVIEW

**Comment by rfbird** [comment]
Sorry for the delay my end, I'm hoping to at least get started on this tomorrow

**Review by rfbird — APPROVED** [review]
> Reviewed 72 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/444)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/Inciter/AMR/mesh_adapter.cpp, line 125 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/444#-MGJEi0a25nxaLVPmEnV:-MGJEi0a25nxaLVPmEnW:b3o30gs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/03c2f2f3a4d283bff71d30b1d317d46ab3c51df3/src/Inciter/AMR/mesh_adapter.cpp#L125)):*
> ```cpp
>             if (local.lock_case == Edge_Lock_Case::unlocked)
>               local.needs_derefining = 1;
>           }
> ```

Did we decide if we want the logic in mark_derefinment to check if you're trying to mark a "grand parent"?
___
*[src/Inciter/AMR/mesh_adapter.cpp, line 158 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/444#-MGJEvbsEi7nM4Bd1Tjk:-MGJEvbsEi7nM4Bd1Tjl:bl9zukh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/03c2f2f3a4d283bff71d30b1d317d46ab3c51df3/src/Inciter/AMR/mesh_adapter.cpp#L158)):*
> ```cpp
> 
>        mark_refinement();
>        mark_derefinement();
> ```

I don't remember why this is needed, shall we add a note here?

**Review by jbakosi — COMMENTED** [review]
Thanks for the extra set of eyes!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/444#-:-MGO1FopBpXfJl6Y_o3w:b-jmqgas)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @rfbird)

___
*[src/Inciter/AMR/mesh_adapter.cpp, line 125 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/444#-MGJEi0a25nxaLVPmEnV:-MGO0KqeE6YOhlN9K0pR:bvypg31) ([raw file](https://github.com/quinoacomputing/quinoa/blob/03c2f2f3a4d283bff71d30b1d317d46ab3c51df3/src/Inciter/AMR/mesh_adapter.cpp#L125)):*
<details><summary><i>Previously, rfbird (Robert Bird) wrote…</i></summary><blockquote>

Did we decide if we want the logic in mark_derefinment to check if you're trying to mark a "grand parent"?
</blockquote></details>

I'm not sure. But my commit message for adding this code says:
```
    Only derefine active tets when uniform deref
    
    Previously all edges were marked for derefinement when uniform
    derefinement was done. Now only the active tets' edges are marked for
    derefinement, which avoids marking edges of grandparents, so it does the
    right thing if two uniform refinement steps are followed by a uniform
    derefinement step.
    
    Thanks to @rfbird for the help with this.

```
So I'm guessing I just made it work at the time. I'm not sure if/what we decided what logic we ultimately want. I'm okay with only operating on the active mesh - that seems safer than having to deal with grandparents. What do you think?
___
*[src/Inciter/AMR/mesh_adapter.cpp, line 158 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/444#-MGJEvbsEi7nM4Bd1Tjk:-MGO16kM7vIMSrOoTHCM:bfh6rbh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/03c2f2f3a4d283bff71d30b1d317d46ab3c51df3/src/Inciter/AMR/mesh_adapter.cpp#L158)):*
<details><summary><i>Previously, rfbird (Robert Bird) wrote…</i></summary><blockquote>

I don't remember why this is needed, shall we add a note here?
</blockquote></details>

I wish I had a note for that! ;-) I don't remember why we need that. ;-(

**Review by rfbird — APPROVED** [review]

**Review by adityakpandare — APPROVED** [review]
> Reviewed 3 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/444)* status: all files reviewed, 2 unresolved discussions (waiting on @rfbird)

**Pull request merged**
