### PR TITLE
AMR fixes for dtref

### PR DESCRIPTION
**Pull request by adityakpandare**
This set of commits fixes a few issues with AMR during time-stepping, particularly with derefinement/coarsening. Commit messages give more information about specific changes.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505)

### CODE REVIEW

**Review by jbakosi — CHANGES_REQUESTED** [review]
Great progress! Few minor comments as we discussed, then good to go.

> Reviewed 12 of 17 files at r1, 1 of 1 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-:-Mf-kd3k42xI3Lrm7xF_:b7evcyj)* status: all files reviewed, 5 unresolved discussions (waiting on @adityakpandare)

___
*[src/Inciter/ALECG.hpp, line 145 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-iqSXEXZsthIQG_il:-Mf-iqSXEXZsthIQG_im:bg0r6bp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/ALECG.hpp#L145)):*
> ```cpp
>       const std::unordered_map< std::size_t, tk::UnsMesh::Edge >& addedNodes,
>       const std::unordered_map< std::size_t, std::size_t >& addedTets,
>       const std::unordered_map< std::size_t, std::size_t >& removedNodes,
> ```

As we discussed, we could possibly use only a `std::set` instead.
___
*[src/Inciter/ALECG.cpp, line 1329 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-j8163nTYSPxYnBnY:-Mf-j817DjrM3gBFdG7k:bfi9l4b) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/ALECG.cpp#L1329)):*
> ```cpp
>   m_u.resize( npoin );
>   m_un.resize( npoin );
>   m_rhs.resize( npoin );
> ```

Due to the above calls to `rm()`, these `resize`s are probably no longer necessary. Maybe prudent to put in an assert on the sizes, `.nunk()`, equaling to `npoin`?
___
*[src/Inciter/DiagCG.cpp, line 862 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-jWtGAh1yPeDpJOp3:-Mf-jWtGAh1yPeDpJOp4:b-lc92ky) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/DiagCG.cpp#L862)):*
> ```cpp
>   m_ue.resize( nelem );
>   m_lhs.resize( npoin );
>   m_rhs.resize( npoin );
> ```

Same as in `ALECG`.
___
*[src/Inciter/Discretization.cpp, line 48 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-kROY4i8rvRAQvdsZ:-Mf-kROZ3jMGM_URvfed:bvypu0f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Discretization.cpp#L48)):*
> ```cpp
>   const CProxy_Transporter& transporter,
>   const tk::CProxy_MeshWriter& meshwriter,
>   [[maybe_unused]] const std::vector< std::size_t >& ginpoel,
> ```

Where do we call the ctor without passing `ginpoel`? I don't think that happens.
___
*[src/Inciter/Refiner.cpp, line 1585 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-k75Y4k2BzFYDloyW:-Mf-k75Y4k2BzFYDloyX:biiaals) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Refiner.cpp#L1585)):*
> ```cpp
>   //  // find new node taking place of l
>   //  removedNodes[l] = //new-local-id
>   //}
> ```

This could probably go away and just use a `std::set` storing global node ids.
___
*[tests/regression/inciter/mesh_refinement/t0ref/CMakeLists.txt, line 14 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-k0c5CVnhTbO-Hy2i:-Mf-k0c5CVnhTbO-Hy2j:b-83sjoh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/tests/regression/inciter/mesh_refinement/t0ref/CMakeLists.txt#L14)):*
> ```CMake
>                     BIN_BASELINE slot_cyl_diagcg_pe1_u0.0.std.exo
>                     BIN_RESULT out.e-s.0.1.0
>                     BIN_DIFF_PROG_ARGS -m
> ```

Nice!

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505)* status: all files reviewed, 5 unresolved discussions (waiting on @jbakosi)

___
*[src/Inciter/ALECG.hpp, line 145 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-iqSXEXZsthIQG_il:-Mf30fGlESb5tHykfrdJ:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/ALECG.hpp#L145)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

As we discussed, we could possibly use only a `std::set` instead.
</blockquote></details>

Done.
___
*[src/Inciter/ALECG.cpp, line 1329 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-j8163nTYSPxYnBnY:-Mf34kK0BEx_edrskreO:b-vwwoay) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/ALECG.cpp#L1329)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Due to the above calls to `rm()`, these `resize`s are probably no longer necessary. Maybe prudent to put in an assert on the sizes, `.nunk()`, equaling to `npoin`?
</blockquote></details>

The `resize()` is needed to add new nodes resulting from refinement; because the `rm()` only removed derefined nodes.
___
*[src/Inciter/DiagCG.cpp, line 862 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-jWtGAh1yPeDpJOp3:-Mf34n8j3WTLVpG79Sy2:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/DiagCG.cpp#L862)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Same as in `ALECG`.
</blockquote></details>

Done.
___
*[src/Inciter/Discretization.cpp, line 48 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-kROY4i8rvRAQvdsZ:-Mf36wNa6Bl-5oWEI3C8:b-y5xiv9) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Discretization.cpp#L48)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Where do we call the ctor without passing `ginpoel`? I don't think that happens.
</blockquote></details>

`ginpoel` is not used anywhere, except for an Assert in the ctor. This throws an unused warning for release mode, hence the `maybe_unused`.
___
*[src/Inciter/Refiner.cpp, line 1585 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-k75Y4k2BzFYDloyW:-Mf31Ce87rRKVDirppp0:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Refiner.cpp#L1585)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This could probably go away and just use a `std::set` storing global node ids.
</blockquote></details>

Done.
___
*[tests/regression/inciter/mesh_refinement/t0ref/CMakeLists.txt, line 14 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-k0c5CVnhTbO-Hy2i:-Mf31Dbv99WrKDAq_jUP:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/tests/regression/inciter/mesh_refinement/t0ref/CMakeLists.txt#L14)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Thanks!

**Review by jbakosi — CHANGES_REQUESTED** [review]
Looks good. One minor comment left.

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-:-Mf3IMTL13kgixO9HJVp:bc8cdvl)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[src/Inciter/ALECG.cpp, line 1329 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-j8163nTYSPxYnBnY:-Mf3HqxwDJpz_7h9CIU8:bvqapyw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/ALECG.cpp#L1329)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The `resize()` is needed to add new nodes resulting from refinement; because the `rm()` only removed derefined nodes.
</blockquote></details>

Indeed. I forgot.
___
*[src/Inciter/Discretization.cpp, line 48 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-kROY4i8rvRAQvdsZ:-Mf3I863DTb2s1WX3M3Z:bfluidy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Discretization.cpp#L48)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

`ginpoel` is not used anywhere, except for an Assert in the ctor. This throws an unused warning for release mode, hence the `maybe_unused`.
</blockquote></details>

If it is not used at at all, let's not even pass it.

**Review by adityakpandare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505)* status: 22 of 26 files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/Inciter/Discretization.cpp, line 48 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/505#-Mf-kROY4i8rvRAQvdsZ:-Mf3Y0DG70ED2rcpZDKD:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2f415ddd6860b86f0f2b96e48304d44bb80b6b54/src/Inciter/Discretization.cpp#L48)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If it is not used at at all, let's not even pass it.
</blockquote></details>

Done.

**Review by jbakosi — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
