### PR TITLE
Multi-Material problems combining solids and fluids

### PR DESCRIPTION
**Pull request by airaudofacundo**
First iteration of fully multi-material implementation to run cases with solids and fluids. So far P0 runs of advection cases run well. Tested with case 5.1 of [1].

[1] Favrie, Nicolas, Sergey L. Gavrilyuk, and Richard Saurel. "Solid–fluid diffuse interface model in cases of extreme deformations." Journal of computational physics 228.16 (2009): 6037-6077.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/585)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Excellent work @airaudofacundo! I have just a few comments below. Some of the fluids-only multimat tests are failing too- could you take a look at those?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-:-Nbu8p3N6XQZbD89yBIO:b33v35s)* status: all files reviewed, 9 unresolved discussions (waiting on @airaudofacundo)

___
*[`src/PDE/Integrate/Boundary.cpp` line 286 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu6R2iD0YqfzoTUbfe:-Nbu6R2iD0YqfzoTUbff:bxeftbz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/Boundary.cpp#L286)):*
> ```cpp
>               for (std::size_t idir=0; idir<3; ++idir)
>                 riemannDeriv[3*nmat+ndof+3*3*9*k+3*3*(3*i+j)+3*l+idir][el] +=
>                   wt * fl[ncomp+nmat+1+9*3*k+3*(3*i+j)+l] * fn[idir];
> ```

Maybe we should write an accessor-function to make this less error-prone, just like the other state-vars, like `densityDofIdx()`? It will have arguments `(nmat, k, i, j, l)`. The result will be: we can access riemannDeriv as: `riemannDeriv[3*nmat+ndof+newSolidsAccessorFn(nmat,k,i,j,l)]`
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 241 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu7NyI4545tj-IhC60:-Nbu7NyJBL4zOvvC0N2p:b-1ec7ew) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L241)):*
> ```cpp
>                     state[volfracIdx(nmat, k)]*(
>                     riemannDeriv[3*nmat+ndof+3*3*9*k+3*3*(3*i+j)+3*l+l][e]
>                    -riemannDeriv[3*nmat+ndof+3*3*9*k+3*3*(3*i+l)+3*l+j][e]);
> ```

The accessor-fn that I mentioned before will make this simpler too.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 318 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu2HWvE3AVgNZr5eAo:-Nbu2HWvE3AVgNZr5eAp:b-crtuzq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L318)):*
> ```cpp
>           for(std::size_t j=0; j<3; ++j)
>             R(e, deformDofIdx(nmat,solidx[k],i,j,ndof,idof)) +=
>               wt * ncf[deformIdx(nmat,solidx[k],i,j)][idof] * B[idof];
> ```

What happens to this part when there's no solid-eos in the simulation?
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 927 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu83D82OssHhrVTeR5:-Nbu83D82OssHhrVTeR6:bh69gta) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L927)):*
> ```cpp
>     auto u = ugp[ncomp+velocityIdx(nmat,0)];
>     auto v = ugp[ncomp+velocityIdx(nmat,1)];
>     auto w = ugp[ncomp+velocityIdx(nmat,2)];
> ```

The above 6 lines of code are common in this if-branch and the else-branch, correct? If so, let's move that code outside the if-test.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 163 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4Nqw5iTovDt6HQFx:-Nbu4NqxAYIgosdVa-qL:bdulu9s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L163)):*
> ```cpp
> 
>           // ** HARDCODED **
>           // Should be able to store rho_0 for every cell at every Gauss point.
> ```

Let's create a github-issue about storing rho0, so that we don't forget.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 179 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4ClpCddXpGcz9GkX:-Nbu4ClpCddXpGcz9GkY:bzg04qy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L179)):*
> ```cpp
>               {
>                 for (std::size_t l=0; l<deriv.size(); ++l)
> 		  deriv[l] = 0.0;
> ```

Leading tab-spaces.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 202 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4Tw54OMZj3w7hfij:-Nbu4Tw54OMZj3w7hfik:bzg04qy) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L202)):*
> ```cpp
>                   + D*((alpha*dBdx[(j+1)%3][idof]+B[idof]*deriv[4])
>                        *(deriv[0]-deriv[1])
> 		      -(alpha*dBdx[(j+2)%3][idof]+B[idof]*deriv[5])
> ```

Leading tab-spaces.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 413 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu3Kcx0OwV3vSq2ARd:-Nbu3Kcx0OwV3vSq2ARe:b-2l068m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/MultiMat/MiscMultiMatFns.cpp#L413)):*
> ```cpp
>           ugp[densityIdx(nmat, k)], u, v, w, ugp[energyIdx(nmat, k)],
>           ugp[volfracIdx(nmat, k)], k, gk );
>         gk = tk::rotateTensor(gk, fn);
> ```

Why was this moved down? Does the Cauchy stress not have to be computed in the face-normal coordinate system?
___
*[`src/PDE/MultiMat/Problem/BoxInitialization.hpp` line 189 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu3j18BI4lQfbIz_V4:-Nbu3j18BI4lQfbIz_V5:b-npwfyj) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/MultiMat/Problem/BoxInitialization.hpp#L189)):*
> ```cpp
>       }
>       else {
> 	gk = {{}};
> ```

Leading tab-space. Could you please replace with regular spaces?

**Review by airaudofacundo — COMMENTED** [review]
Implemented changes and fixes.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-:-NbzLd4o6S_uXZngnvLr:bnjwyt0)* status: 4 of 13 files reviewed, 9 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/Integrate/Boundary.cpp` line 286 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu6R2iD0YqfzoTUbfe:-NbzLFw263f7EsjfcrDi:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/Boundary.cpp#L286)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Maybe we should write an accessor-function to make this less error-prone, just like the other state-vars, like `densityDofIdx()`? It will have arguments `(nmat, k, i, j, l)`. The result will be: we can access riemannDeriv as: `riemannDeriv[3*nmat+ndof+newSolidsAccessorFn(nmat,k,i,j,l)]`
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 241 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu7NyI4545tj-IhC60:-NbzLJ9s2yV62RwVA4ZO:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L241)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The accessor-fn that I mentioned before will make this simpler too.
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 318 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu2HWvE3AVgNZr5eAo:-NbzLKCs58B4S0GYmvdg:blxl651) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L318)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

What happens to this part when there's no solid-eos in the simulation?
</blockquote></details>

Added if (solidx[k]) check here
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 927 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu83D82OssHhrVTeR5:-NbzLP7RCUj1LIODPgbH:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L927)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

The above 6 lines of code are common in this if-branch and the else-branch, correct? If so, let's move that code outside the if-test.
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 163 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4Nqw5iTovDt6HQFx:-NbzLQHj1IrJXf8rMU_1:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L163)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's create a github-issue about storing rho0, so that we don't forget.
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 179 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4ClpCddXpGcz9GkX:-NbzLQpXBsW8gge4g12B:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L179)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Leading tab-spaces.
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 202 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4Tw54OMZj3w7hfij:-NbzLRGJ1pWbtm77qCu1:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L202)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Leading tab-spaces.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 413 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu3Kcx0OwV3vSq2ARd:-NbzLTO82A6C3MJyeCbc:bb6giay) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/MultiMat/MiscMultiMatFns.cpp#L413)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why was this moved down? Does the Cauchy stress not have to be computed in the face-normal coordinate system?
</blockquote></details>

It doesn't matter as sk is not used by soundspeed. You will deal with this as we discussed.
___
*[`src/PDE/MultiMat/Problem/BoxInitialization.hpp` line 189 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu3j18BI4lQfbIz_V4:-NbzLbwtACwrV6SRChmT:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/MultiMat/Problem/BoxInitialization.hpp#L189)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Leading tab-space. Could you please replace with regular spaces?
</blockquote></details>

Done.

**Review by adityakpandare — COMMENTED** [review]
Thanks!

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-:-NbzhIrGCiLBDXYrpkdY:b-ucfknh)* status: 7 of 13 files reviewed, all discussions resolved (waiting on @airaudofacundo)

___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 241 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu7NyI4545tj-IhC60:-NbzeDu7COni81S2OQW9:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/MultiMatTerms.cpp#L241)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 163 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu4Nqw5iTovDt6HQFx:-NbzehHk-l9o82exVFKC:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/Integrate/SolidTerms.cpp#L163)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 413 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-Nbu3Kcx0OwV3vSq2ARd:-Nbzh4f5Am1oPqamELwL:b8bbmi2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/32715bcdf60dbb39d0ff1c6f306a659fad66c53c/src/PDE/MultiMat/MiscMultiMatFns.cpp#L413)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

It doesn't matter as sk is not used by soundspeed. You will deal with this as we discussed.
</blockquote></details>

Ah, cool. I created an issue (https://github.com/quinoacomputing/quinoa/issues/587) to remove the stress from `EOS::soundspeed`'s args.

**Review by adityakpandare — APPROVED** [review]
:lgtm: Will merge this as soon as the CI passes it

> Reviewed 4 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/585#-:-Nc-1T5B6MbWRto986-B:bzduakd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

**Pull request merged**
