### PR TITLE
Init sdy (Solid Dynamics solver)

### PR DESCRIPTION
**Pull request by airaudofacundo**
Elastic Multi-Material solver implemented.

Includes:

- Solves for the inverse deformation gradient tensor g, every component of g adds one equation to the PDE.
- A new Riemann solver LaxFriedrichsSolid which implements the Lax-Friedrichs solver which considers these added degrees of freedom.
- A new equation of state SmallShearSolid.
- Added to Base/Vector.hpp routines for the computation of Cauchy-Green tensors, and tensor rotations and reflections.
- Changes to several routines in MiscMultiMaterial to account for the inverse deformation gradient.

References:

[1] Gavrilyuk, Sergey L., Nicolas Favrie, and Richard Saurel. "Modelling wave dynamics of compressible elastic materials." Journal of computational physics 227.5 (2008): 2941-2969.
[2] Plohr, Jeeyeon N., and Bradley J. Plohr. "Linearized analysis of Richtmyer–Meshkov flow for elastic materials." Journal of Fluid Mechanics 537 (2005): 55-89.
[3] Hill, David J., et al. "An Eulerian hybrid WENO centered-difference solver for elastic–plastic solids." Journal of Computational Physics 229.24 (2010): 9053-9072.
[4] Ortega, A. López, et al. "Numerical simulation of elastic–plastic solid mechanics using an Eulerian stretch tensor approach and HLLD Riemann solver." Journal of Computational Physics 257 (2014): 414-441.
[5] Miller, G. H., and P. Colella. "A high-order Eulerian Godunov method for elastic–plastic flow in solids." Journal of computational physics 167.1 (2001): 131-176.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Great job @airaudofacundo! I have a few comments below. Thanks!

> Reviewed 11 of 29 files at r1, 3 of 5 files at r2, 13 of 14 files at r3, 5 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-:-NXqy0pjEI445dqK66g6:b6y5yzk)* status: all files reviewed, 9 unresolved discussions (waiting on @airaudofacundo)

___
*[`src/Base/Vector.hpp` line 502 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzcb0mDOlspYm_eqBR:-NXzcb0mDOlspYm_eqBS:blesjrs) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L502)):*
> ```cpp
> //! \param[in] mat matrix to be rotated.
> //! \param[in] r Coordinates of the first basis vector r = (rx,ry,rz).
> //! \return Left Cauchy-Green tensor
> ```

Since this is for a general matrix, lets update this comment to reflect that it returns the rotated matrix.
___
*[`src/Base/Vector.hpp` line 548 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzd1uc9kS5LXVa3bu-:-NXzd1uc9kS5LXVa3bu0:b8ttxu7) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L548)):*
> ```cpp
>       for (std::size_t j=0; j<3; ++j)
>         matAuxIn[i*3+j] = mat[i][j];
>     }
> ```

Let's eliminate the excess indentation int the for-loop.
___
*[`src/Base/Vector.hpp` line 559 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzd4m68bkHHliyqLEC:-NXzd4m68bkHHliyqLED:brhumzt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L559)):*
> ```cpp
>       matAuxIn[i]  = matAuxOut[i];
>       matAuxOut[i] = 0.0;
>     }
> ```

Same here.
___
*[`src/Base/Vector.hpp` line 574 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzdc6lBXyjbUjLqxdD:-NXzdc6lBXyjbUjLqxdE:b-f1ba0f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L574)):*
> ```cpp
> //! \param[in] mat matrix to be rotated.
> //! \param[in] reflectMat Reflection matrix
> //! \return Left Cauchy-Green tensor
> ```

Let's update this comment to indicate that the function returns the reflected matrix.
___
*[`src/Base/Vector.hpp` line 579 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzdjd73fVk3DYxCjje:-NXzdjd73fVk3DYxCjjf:bbdd18z) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L579)):*
> ```cpp
>               const std::array< std::array< tk::real, 3 >, 3 >& reflectMat)
> {
>   // define rotation matrix
> ```

define "reflection" matrix?
___
*[`src/Base/Vector.hpp` line 597 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXze8ta9_ptWlnuIF2t:-NXze8ta9_ptWlnuIF2u:byy8e1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L597)):*
> ```cpp
>       matAuxIn[i*3+j] = mat[i][j];
>   }
>   
> ```

Could you remove these trailing whitespaces?
___
*[`src/PDE/EoS/SmallShearSolid.cpp` line 543 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqveQGDPJTy0FLOHrg:-NXqveQGDPJTy0FLOHrh:b-9ov1y8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/EoS/SmallShearSolid.cpp#L543)):*
> ```cpp
> 
>   // compute elastic energy
>   //auto rhoEe = rho * m_mu * eps2; // I think rho doesn't belong here
> ```

Let's remove this comment line, now that we know it was a bug.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 415 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqvplO74W3GBkEvgSe:-NXqvplO74W3GBkEvgSf:b-nr63ag) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L415)):*
> ```cpp
>           ugp[densityIdx(nmat, k)],
>           pgp[pressureIdx(nmat, k)], ugp[volfracIdx(nmat, k)], k,
>           gnn, gk ) );
> ```

I'm not sure about this `soundspeed` call. Shouldn't we be passing the Cauchy stress tensor dotted with the face-normal, and not `gnn`?
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 452 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqw32aATxRErPfZMrs:-NXqw32aATxRErPfZMrt:b-5mcobi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L452)):*
> ```cpp
>             ugp[densityIdx(nmat, k)],
>             pgp[pressureIdx(nmat, k)], ugp[volfracIdx(nmat, k)], k,
>             gnn, gk ) );
> ```

Same comment here about `gnn`.

**Review by airaudofacundo — COMMENTED** [review]
Implemented all changes and pushed into init_sdy. Also added a bug fix in LaxFriedrichsSolids.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-:-NY-5642DTA060HWENg2:brhg4io)* status: 25 of 29 files reviewed, 9 unresolved discussions (waiting on @adityakpandare)

___
*[`src/Base/Vector.hpp` line 502 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzcb0mDOlspYm_eqBR:-NY--r7s-pdmKUQGjXWR:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L502)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Since this is for a general matrix, lets update this comment to reflect that it returns the rotated matrix.
</blockquote></details>

Done.
___
*[`src/Base/Vector.hpp` line 548 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzd1uc9kS5LXVa3bu-:-NY--wJB4Zdotfo2Iiv1:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L548)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's eliminate the excess indentation int the for-loop.
</blockquote></details>

Done.
___
*[`src/Base/Vector.hpp` line 559 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzd4m68bkHHliyqLEC:-NY--yQ60Q-LRa9mLK8y:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L559)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`src/Base/Vector.hpp` line 574 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzdc6lBXyjbUjLqxdD:-NY-0AlqE5AiyRySwOeM:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L574)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's update this comment to indicate that the function returns the reflected matrix.
</blockquote></details>

Done.
___
*[`src/Base/Vector.hpp` line 579 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXzdjd73fVk3DYxCjje:-NY-0CQrAXSiYjBZq68H:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L579)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

define "reflection" matrix?
</blockquote></details>

Done.
___
*[`src/Base/Vector.hpp` line 597 at r5](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXze8ta9_ptWlnuIF2t:-NY-0DpoDrwxj0Jw1T6z:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/41101b6bfed267f3000ddd0e6d16186f7b5ab806/src/Base/Vector.hpp#L597)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you remove these trailing whitespaces?
</blockquote></details>

Done.
___
*[`src/PDE/EoS/SmallShearSolid.cpp` line 543 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqveQGDPJTy0FLOHrg:-NY-0GvL3v5FnL_npOcn:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/EoS/SmallShearSolid.cpp#L543)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's remove this comment line, now that we know it was a bug.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 415 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqvplO74W3GBkEvgSe:-NXzvLiT6aAW12w98MFw:b4frqy8) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L415)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I'm not sure about this `soundspeed` call. Shouldn't we be passing the Cauchy stress tensor dotted with the face-normal, and not `gnn`?
</blockquote></details>

Yes! My mistake. Added not to retrieve the stress and pass 'snn' instead of 'gnn'. This was the source of the oscillations.
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 452 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqw32aATxRErPfZMrs:-NY--hTQ3DBwXK53XdyT:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L452)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same comment here about `gnn`.
</blockquote></details>

Done.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks!  A minor comment about styling as we'd discussed, but otherwise looks good.

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-:-NY-8FoA8hlpr3TgEnoM:b-bbxxr)* status: all files reviewed, 2 unresolved discussions (waiting on @airaudofacundo)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 415 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqvplO74W3GBkEvgSe:-NY-7v9nCy6iuAAyU3qV:bjcuzni) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L415)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Yes! My mistake. Added not to retrieve the stress and pass 'snn' instead of 'gnn'. This was the source of the oscillations.
</blockquote></details>

Thanks! However, you've replaced spaces with tabs. Would you go back to normal spaces with the correct indentation please?
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 452 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqw32aATxRErPfZMrs:-NY-7c0f09B3oU6Cqa1V:b-q7tzvk) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L452)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same comment about tab-spaces and indentation.
___
*[`src/PDE/Riemann/LaxFriedrichsSolids.hpp` line 111 at r6](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NY-7RCc9LX6NXUh2lK4:-NY-7RCc9LX6NXUh2lK5:b-73m6vw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f9810d13499a4b9b7ef3fe59c6696d3888292481/src/PDE/Riemann/LaxFriedrichsSolids.hpp#L111)):*
> ```cpp
>       asign_r.push_back(tk::matvec(asig_r[k], fn));
>       for (std::size_t i=0; i<3; ++i)
>         sign_r[i] += asign_r[k][i];
> ```

Nice catch!

**Review by airaudofacundo — COMMENTED** [review]
Fixed tabs.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-:-NY-cns83c-pv3oJnqIj:b1b2pvj)* status: 28 of 29 files reviewed, 2 unresolved discussions (waiting on @adityakpandare)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 415 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqvplO74W3GBkEvgSe:-NY-cBSM6XK1-GuaCIPk:b-2x55ev) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L415)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Thanks! However, you've replaced spaces with tabs. Would you go back to normal spaces with the correct indentation please?
</blockquote></details>

Ok, my bad! Now I learned how to see that in emacs!
___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 452 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqw32aATxRErPfZMrs:-NY-cfpE-O5wPfisJyop:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L452)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Same comment about tab-spaces and indentation.
</blockquote></details>

Done.

**Review by adityakpandare — APPROVED** [review]
Great work @airaudofacundo! I am trying to fix certain clang warnings for the code in Vector.hpp. Once that's done, we can go ahead and merge this.

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-:-NY02qc717xl9G5MgXXZ:bptf5py)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

___
*[`src/PDE/MultiMat/MiscMultiMatFns.cpp` line 415 at r4](https://reviewable.io/reviews/quinoacomputing/quinoa/581#-NXqvplO74W3GBkEvgSe:-NY02dRU9qnfLMit3b75:bdti6k4) ([raw file](https://github.com/quinoacomputing/quinoa/blob/37ebdbecac2b119ed704dab42f7cee9dc44f4e98/src/PDE/MultiMat/MiscMultiMatFns.cpp#L415)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Ok, my bad! Now I learned how to see that in emacs!
</blockquote></details>

No worries! Thanks!

**Pull request merged**
