### PR TITLE
Conjugate gradients linear solver

### PR DESCRIPTION
**Pull request by jbakosi**
Using a new compressed sparse row storage matrix, with optionally multiple scalars (DOFs) per nonzero matrix entry, distributed across PEs. Tested in serial and parallel. We should still add diagonal scaling at the very least as a preconditioner, otherwise, this should be good to go for simple Laplacian smoother and for a Helmholtz-decomposition-based mesh velocity.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: all files reviewed, 9 unresolved discussions (waiting on @jbakosi)

___
*[src/Inciter/Discretization.hpp, line 94 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT1qLxiEixecOKOFXj1:-MT1qLxiEixecOKOFXj2:bwnys3q) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.hpp#L94)):*
> ```cpp
> 
>     //! Initialize Conjugrate Gradients linear solver
>     void cginit();
> ```

We should try to differentiate between the CG abbreviation for Conjugate Gradient and Continuous Galerkin. It would be better to be verbose and call such functions ConjugateGradientInit() for example. Same thing applies to the next two function names.
___
*[src/Inciter/Discretization.cpp, line 148 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT1rTuvBfTgSFNscehh:-MT1r2rP1pCWE-c-XdjD:bxq1it5) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.cpp#L148)):*
> ```cpp
>   if (ALE()) {
>     const auto& [A,x,b] = LaplacianSmoother();
>     m_cg[ thisIndex ].insert( A, x, b, 10, 1.0e-3,
> ```

Could you point me to where `cgproxy.insert()` is defined?
___
*[src/Inciter/Discretization.cpp, line 240 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT21dp45SGMHuz7H4a1:-MT21dp45SGMHuz7H4a2:bw9nbpm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.cpp#L240)):*
> ```cpp
> // *****************************************************************************
> // Generate {A,x,b} for Laplacian mesh velocity smoother
> //! \return {A,x,b} for Laplacian mesh velocity smoother
> ```

Can we cite the paper here too, so that it's easier to compare code to the math?
___
*[src/Inciter/Transporter.cpp, line 470 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT22S8qBCVGR0s3xjix:-MT22S8qBCVGR0s3xjiy:bpao408) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Transporter.cpp#L470)):*
> ```cpp
>   for ([[maybe_unused]] const auto& filename : inputs)
>     m_scheme.emplace_back( g_inputdeck.get< tag::discr, tag::scheme >(),
> 			   linearsolver );
> ```

Replace tabs with spaces? :wink:
___
*[src/LinearSolver/ConjugateGradients.cpp, line 12 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTg-TWG2gl6_qzQtazm:-MTg-TWG2gl6_qzQtazn:btr33zi) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/ConjugateGradients.cpp#L12)):*
> ```cpp
>     conjugate gradients linear solver.
>   \see Y. Saad, Iterative Methods for Sparse Linear Systems: Second Edition,
>     ISBN 9780898718003, 2003, Algorithm 6.18
> ```

Could you repeat the algorithm 6.18 here?
___
*[src/LinearSolver/CSR.cpp, line 21 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8FyeECV6fqUIJSsdl:-MT8FyeECV6fqUIJSsdm:b-bagr7m) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L21)):*
> ```cpp
>           const std::pair< std::vector< std::size_t >,
>                            std::vector< std::size_t > >& psup )
> try :
> ```

Could you explain what `try` does? I can see that it is followed by an initializer-list, but I'm not familiar with this particular keyword.
___
*[src/LinearSolver/CSR.cpp, line 22 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GRZK9UYfTaG2bmYx:-MT8GRZK9UYfTaG2bmYy:b-q03mhr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L22)):*
> ```cpp
>                            std::vector< std::size_t > >& psup )
> try :
>   dof( DOF ),
> ```

Is `dof` basically the number of unknowns i.e. number of entries in `x` in the `A*x=b` system?
___
*[src/LinearSolver/CSR.cpp, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GoIbAXcb7c_lbT1u:-MT8GoIbAXcb7c_lbT1v:bpybzx1) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L24)):*
> ```cpp
>   dof( DOF ),
>   rnz( psup.second.size()-1 ),
>   ia( rnz.size()*DOF+1 )
> ```

If `ia` is a vector (and `rnz.size()` is a single value), does this initialize all entries in `ia` to the value `rnz.size()*DOF+1`? Also, what's the size of `ia`?
___
*[src/LinearSolver/CSR.cpp, line 155 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTfud9CBkh1ePvWHJpc:-MTfud9CBkh1ePvWHJpd:b-418dj2) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L155)):*
> ```cpp
> //  Multiply CSR matrix with vector from the right: r = A * x
> //! \param[in] x Vector to multiply matrix with from the right
> //! \param[in] r Result vector of product r = A * x
> ```

Can we put in a comment that this is not a complete mat-vec product in parallel?

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: all files reviewed, 8 unresolved discussions (waiting on @adityakpandare)

___
*[src/Inciter/Discretization.hpp, line 94 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT1qLxiEixecOKOFXj1:-MTgLflc24dV9_8xniL2:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.hpp#L94)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

We should try to differentiate between the CG abbreviation for Conjugate Gradient and Continuous Galerkin. It would be better to be verbose and call such functions ConjugateGradientInit() for example. Same thing applies to the next two function names.
</blockquote></details>

Done.
___
*[src/Inciter/Discretization.cpp, line 148 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT1rTuvBfTgSFNscehh:-MTgLjSeEORFbMGZPMMx:b-y2dngl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.cpp#L148)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you point me to where `cgproxy.insert()` is defined?
</blockquote></details>

This is a Charm++ chare array proxy member function.
___
*[src/Inciter/Discretization.cpp, line 240 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT21dp45SGMHuz7H4a1:-MTgMdId0rwbW1DBv9Jc:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.cpp#L240)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Can we cite the paper here too, so that it's easier to compare code to the math?
</blockquote></details>

Done.
___
*[src/LinearSolver/ConjugateGradients.cpp, line 12 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTg-TWG2gl6_qzQtazm:-MTgNGX35odKUuKqNDgr:bnx7dlf) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/ConjugateGradients.cpp#L12)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you repeat the algorithm 6.18 here?
</blockquote></details>

Will do this tomorrow.
___
*[src/LinearSolver/CSR.cpp, line 21 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8FyeECV6fqUIJSsdl:-MTgNcxr9ctiNvwHq1eX:b3xv2pm) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L21)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Could you explain what `try` does? I can see that it is followed by an initializer-list, but I'm not familiar with this particular keyword.
</blockquote></details>

This is how one can catch exceptions from constructors and their initialization lists. See also https://en.cppreference.com/w/cpp/language/function-try-block
___
*[src/LinearSolver/CSR.cpp, line 22 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GRZK9UYfTaG2bmYx:-MTgNfEPDNbxn-xABH59:b-13vqs6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L22)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Is `dof` basically the number of unknowns i.e. number of entries in `x` in the `A*x=b` system?
</blockquote></details>

It is the number of scalars per nonzero matrix entry. This way the sparse matrix is block-compressed-row storage. Every single nonzero entry consists of a diagonal-only sub-matrix, not storing the zeros.
___
*[src/LinearSolver/CSR.cpp, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GoIbAXcb7c_lbT1u:-MTgO6Yh5Q80eJ6_86Hg:bl1a4je) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L24)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

If `ia` is a vector (and `rnz.size()` is a single value), does this initialize all entries in `ia` to the value `rnz.size()*DOF+1`? Also, what's the size of `ia`?
</blockquote></details>

These do not initialize the vectors, only size them (i.e., allocate memory for them). We fill them below in the constructor's body.
___
*[src/LinearSolver/CSR.cpp, line 155 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTfud9CBkh1ePvWHJpc:-MTgOgDBE4CLPWA_I9Ke:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L155)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Can we put in a comment that this is not a complete mat-vec product in parallel?
</blockquote></details>

Done.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

___
*[src/Inciter/Discretization.cpp, line 148 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT1rTuvBfTgSFNscehh:-MTgW0oGBPvxOUzR1PVl:b5zomst) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/Inciter/Discretization.cpp#L148)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This is a Charm++ chare array proxy member function.
</blockquote></details>

Oh, I need to refresh my charm++ basics... Thanks!
___
*[src/LinearSolver/CSR.cpp, line 21 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8FyeECV6fqUIJSsdl:-MTgWM79DIrCqd_klmzx:bxsktxb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L21)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

This is how one can catch exceptions from constructors and their initialization lists. See also https://en.cppreference.com/w/cpp/language/function-try-block
</blockquote></details>

Ah, so that pairs with `catch`. Thanks!
___
*[src/LinearSolver/CSR.cpp, line 22 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GRZK9UYfTaG2bmYx:-MTgWS4Z-iPxE_BnjZh1:brkqnhz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L22)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

It is the number of scalars per nonzero matrix entry. This way the sparse matrix is block-compressed-row storage. Every single nonzero entry consists of a diagonal-only sub-matrix, not storing the zeros.
</blockquote></details>

Makes sense. `ndof` might be misleading, since it usually means the number of finite-element DOFs per element or in the domain. Do you think we should rename this to `ncomp` like in Inciter?
___
*[src/LinearSolver/CSR.cpp, line 24 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GoIbAXcb7c_lbT1u:-MTgWo6KDXeIDArmoEyn:b2nw2bh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L24)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

These do not initialize the vectors, only size them (i.e., allocate memory for them). We fill them below in the constructor's body.
</blockquote></details>

My bad, I got confused. Thanks for the explanation!

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: all files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[src/LinearSolver/CSR.cpp, line 21 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8FyeECV6fqUIJSsdl:-MTgYL4QBuBluynt5fAN:bb77uf3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L21)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Ah, so that pairs with `catch`. Thanks!
</blockquote></details>

Yes!
___
*[src/LinearSolver/CSR.cpp, line 22 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GRZK9UYfTaG2bmYx:-MTgYRDu3MpL4vdFyEa5:b4tae62) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L22)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Makes sense. `ndof` might be misleading, since it usually means the number of finite-element DOFs per element or in the domain. Do you think we should rename this to `ncomp` like in Inciter?
</blockquote></details>

Sure. I agree, think I like `ncomp` better.

**Review by adityakpandare — APPROVED** [review]
Good to go! :lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-:-MTgo_u-4UYQ9jz-vhTS:b-pqdhye)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/LinearSolver/CSR.hpp, line 95 at r3](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTgoKtA3cqF-aPekVDn:-MTgoKtA3cqF-aPekVDo:b6bxz7f) ([raw file](https://github.com/quinoacomputing/quinoa/blob/bf004132b0e1265277417605891d215200d692b1/src/LinearSolver/CSR.hpp#L95)):*
> ```cpp
> 
>   private:
>     std::size_t ncomp;                  //!< Number of scalars per non-zero
> ```

Awesome! Thanks!
___
*[src/LinearSolver/CSR.cpp, line 22 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MT8GRZK9UYfTaG2bmYx:-MTgoNot6YPseiiYCcRn:b-4zjg48) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/CSR.cpp#L22)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Sure. I agree, think I like `ncomp` better.
</blockquote></details>

Didn't realize that many places used this. Thanks!

**Review by jbakosi — COMMENTED** [review]
Thanks for the extra pair of eyes!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-:-MTgrtyW9ZDVJB_gKzCB:biv02us)* status: all files reviewed, 1 unresolved discussion (waiting on @jbakosi)

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: 38 of 40 files reviewed, all discussions resolved (waiting on @adityakpandare)

___
*[src/LinearSolver/ConjugateGradients.cpp, line 12 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/468#-MTg-TWG2gl6_qzQtazm:-MTkSROfDPUbP1xoGoO9:bdjk2ta) ([raw file](https://github.com/quinoacomputing/quinoa/blob/f21f99c5a15c368eeb0dcf6b68ec2499dbd7f2e5/src/LinearSolver/ConjugateGradients.cpp#L12)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Will do this tomorrow.
</blockquote></details>

Done in https://github.com/quinoacomputing/quinoa/commit/b9a6c245b5b3911efb484d06599ad4bfdffc116c.

**Review by adityakpandare — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/468)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
