### PR TITLE
Refined field output for p-adaptive DG

### PR DESCRIPTION
**Pull request by jbakosi**
Doing only uniform refinement/derefinement for field output, instead of local ref/deref.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
Looks good. Just one question: where is the decision to refine the output-mesh based on `m_ndof` made in the code?

> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ3qqS2CRg4qS7Ho-mD:b7h2dbm)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @adityakpandare, @jbakosi, and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1412 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-MJ3psLzEBdaBqHRXuos:-MJ3psLzEBdaBqHRXuot:bp0dmk6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ad97ddc8f4f12f22b52ab024ec41fcb51b9089e9/src/Inciter/DG.cpp#L1412)):*
> ```cpp
> 
>   // Add adaptive indicator array to element-centered field output
>   std::vector< tk::real > ndof( begin(m_ndof), end(m_ndof) );;
> ```

Two semi-colons a typo?

**Review by jbakosi — COMMENTED** [review]
The decision to refine is done in the input file, e.g.,
```
  plotvar
    refined true
    interval 5
  end
```

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ3uWcl5NYgpYdOYtm4:byvacvi)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1412 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-MJ3psLzEBdaBqHRXuos:-MJ3upep8-SITmt3dLYQ:b-73m6vw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ad97ddc8f4f12f22b52ab024ec41fcb51b9089e9/src/Inciter/DG.cpp#L1412)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Two semi-colons a typo?
</blockquote></details>

Nice catch!

**Review by adityakpandare — COMMENTED** [review]
So even if I have first order DG (`DG`) selected, I can have `refined true` in the `plotvar` block, and I will get output refinement, right? Is that what we want to do? I thought output-refinement will happen only if both are true:
1. A high-order element is detected (i.e. `DGP1` or `DGP2` is selected in the input file, or `PDG` is selected in the input file and a high-order element is found because of the p-refinement)
2. `refined true` is given in the input file

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ3vwReEmabpxUdQ-kF:b2owwar)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
Yeah, I missed/forgot that and so this is only partially done then. Yeah, I think if `refined true` is in the input, this will do refined output if pDG is selected. I will push fix shortly that detects the existence of at least one high order cell.

Or  should I just make the code ignore `refined true` for DG(P0)? Is that simpler? (We could still print out a warning in that case.) What is the best way?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ3zGRo3NYGwdi60IJj:bp383o4)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — APPROVED** [review]
Yes, we can just ignore `refined true` for DGP0. That will be simpler. Thanks for doing this! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ4-D5QEBu9KR7oGNiF:b-ibm8qv)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by jbakosi — COMMENTED** [review]
Sounds good, see 620f5e3b6.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ41CLv1KoFiFp6ieH4:b-nzuwhu)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @WeizhaoLi2018)

**Review by adityakpandare — APPROVED** [review]
Thanks!

> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-:-MJ44Gi938ynzrJAs2rU:b-ucfknh)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @adityakpandare and @WeizhaoLi2018)

___
*[src/Inciter/DG.cpp, line 1412 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/451#-MJ3psLzEBdaBqHRXuos:-MJ442Ky8DKT4uLz7KFj:bnls0nq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/ad97ddc8f4f12f22b52ab024ec41fcb51b9089e9/src/Inciter/DG.cpp#L1412)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Nice catch!
</blockquote></details>

:wink:

**Pull request merged**
