### PR TITLE
ChareAMR

### PR DESCRIPTION
**Pull request by jbakosi**
This is another huge change set. Just do your best and please ask questions if something is unclear. 

This (almost) finishes #236 (see also #235) and significantly revamps inciter's setup.

__High level overview__

* `Partitioner` now only does mesh partitioning and mesh reshuffling after partitioning.
* Once partitioning is done, the chunks of the mesh are handed over to a new `Refiner` object, which is a Charm++ chare array, whose job is to perform initial mesh refinement. This is optional and multiple steps can be configured using uniform or non-uniform (IC-based) refinement steps.
* Once refinement is done, the mesh chunks are handed over to a new `Sorter` object, which is also a Charm++ chare array, which performs PE-locality mesh node reordering, which yields consecutive unique global node IDs with increasing PE ID. This reordering is now also optional, off by default, and only required for MatCG. After reordering, the mesh chunks are handed over to the worker objects, which are also Charm++ chare arrays, depending on the discretization scheme configured by the user, MatCG, DiagCG, or DG.

As fb09022 discusses, all combinations of (1) a single step of uniform initial refinement (on/off), (2) reordering (on/off), (3) serial/parallel, (4) zero/nonzero virtualization, and (5) MatCG, DiagCG, or DG, should all work. Not all of these have regression tests, though existing tests should pass.

__Next steps__

* Enable non-uniform (IC-based) initial mesh refinement
* Enable multiple steps of initial mesh refinement
  (4823112 enables multiple uniform refinement steps yielding correct boundary data structures after refinement)
* Add regression tests covering all combinations of
  - serial, parallel, parallel + virtualization
  - reorder, no reorder
  - no ref, uniform ref, IC-ref, arbitrary multiple ref steps
  - `DiagCG`, `MatCG`, `DG`.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)

### CODE REVIEW

**Comment by jbakosi** [comment]
https://github.com/quinoacomputing/quinoa/pull/251/commits/60f84f8e36c10b1756e0747f30ada8f33f866efd appears to fix the random deadlock.

**Comment by adityakpandare** [comment]
Reviewed 23 of 57 files at r1, 1 of 15 files at r2.
Review status: 24 of 60 files reviewed, 1 unresolved discussion (waiting on @jbakosi, @rfbird, and @adityakpandare)

---

*[src/Inciter/DG.C, line 85 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGKwRPg7Jsdu8O0DMX8:-LGKwRPg7Jsdu8O0DMX9:b-gz3yuw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf02ff8317ec4689e29f863b3ab1e51f8eb013ed/src/Inciter/DG.C#L85)):*
> ```
>   // Perform leak test on mesh partition
>   Assert( !tk::leakyPartition( m_esuelTet, inpoel, d->Coord()),
>           "Mesh partition leaky" );
> ```

Nice! This is now abstracted to DerivedData? Thanks for putting this in!

---

*[src/PDE/Transport/DGTransport.h, line 329 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGKv_nM6vkVEtc1-5xP:-LGKv_nN-Mp7XnWhc3qg:bp7cbza) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf02ff8317ec4689e29f863b3ab1e51f8eb013ed/src/PDE/Transport/DGTransport.h#L329)):*
> ```objc
>     void
>     bndIntegral( const std::vector< bcconf_t >& bcconfig,
>                  const std::map< int, std::vector< std::size_t > >& bface,
> ```

Just making sure I understand: this is so that the key (which is the chareID) can be looked up faster in an unordered fashion. Correct?

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Comment by jbakosi** [comment]
Review status: 24 of 60 files reviewed, 1 unresolved discussion (waiting on @jbakosi, @rfbird, and @adityakpandare)

---

*[src/Inciter/DG.C, line 85 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGKwRPg7Jsdu8O0DMX8:-LGQB_XqD1TubWj9uuGl:b-hn7dah) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf02ff8317ec4689e29f863b3ab1e51f8eb013ed/src/Inciter/DG.C#L85)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Nice! This is now abstracted to DerivedData? Thanks for putting this in!
</blockquote></details>

Yes. There might also be some more of such mesh quality metrics in the near future, as we work on AMR and put in more tests, in which case we will probably move these into their own file/class.

---

*[src/PDE/Transport/DGTransport.h, line 329 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGKv_nM6vkVEtc1-5xP:-LGQCDKwDTkzK3ZKWD8u:bb77ufg) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf02ff8317ec4689e29f863b3ab1e51f8eb013ed/src/PDE/Transport/DGTransport.h#L329)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Just making sure I understand: this is so that the key (which is the chareID) can be looked up faster in an unordered fashion. Correct?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Comment by adityakpandare** [comment]
Reviewed 23 of 57 files at r1, 14 of 15 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi and @rfbird)

---

*[src/Inciter/Transporter.C, line 446 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGS1RBc3XV6rt-CYQ2I:-LGS1RBd8SNY3S3awmqf:bhoihvv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/cf02ff8317ec4689e29f863b3ab1e51f8eb013ed/src/Inciter/Transporter.C#L446)):*
> ```
> Transporter::workinserted()
> // *****************************************************************************
> // Reduction target: all worker (drevied discretization) chares have been
> ```

Minor typo?

---

*[src/Mesh/UnsMesh.h, line 90 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGS2MWs-3y0gv8_uD7w:-LGS2MWs-3y0gv8_uD7x:bq0a5tb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/907d48f5eea7f8ef2880d02b154503740b63dc12/src/Mesh/UnsMesh.h#L90)):*
> ```objc
>                (l[2] == r[0] || l[2] == r[1] || l[2] == r[2]);
>       }
>     };
> ```

Is this replaced by the ```struct Eq```?

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Comment by jbakosi** [comment]
Hey @rfbird ! Any comment on this? I have two new PRs (based on branches [quiescence](https://github.com/quinoacomputing/quinoa/tree/quiescence) and [osh](https://github.com/quinoacomputing/quinoa/tree/osh)) to be created once I can merge this. Thx.

**Comment by adityakpandare** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

---

*[src/Mesh/UnsMesh.h, line 90 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGS2MWs-3y0gv8_uD7w:-LGVIOjz-6UnUvTAG8Hz:b-59lf5s) ([raw file](https://github.com/quinoacomputing/quinoa/blob/907d48f5eea7f8ef2880d02b154503740b63dc12/src/Mesh/UnsMesh.h#L90)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

`Eq<N>` is now used for equality for when either edges, faces, or tets are used as a key in an unordered container.
</blockquote></details>

Okay. So this equality (comparing the 3 nodes in case of a face/triangle) in all these combinations. is now done with ```Eq<N>```?

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Comment by jbakosi** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

---

*[src/Mesh/UnsMesh.h, line 90 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGS2MWs-3y0gv8_uD7w:-LGVJHVM8yHG66goolsM:b-440bni) ([raw file](https://github.com/quinoacomputing/quinoa/blob/907d48f5eea7f8ef2880d02b154503740b63dc12/src/Mesh/UnsMesh.h#L90)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Okay. So this equality (comparing the 3 nodes in case of a face/triangle) in all these combinations. is now done with ```Eq<N>```?
</blockquote></details>

Yeah. `Eq<N>` is the `KeyEqual` template argument to [unordered_set](https://en.cppreference.com/w/cpp/container/unordered_set) and [unordered_map](https://en.cppreference.com/w/cpp/container/unordered_map) and `Hash<N>` is the hash. They are both parameterized by `N`, because otherwise they do the same:
 * `Eq<N>` performs an equality comparison between two primitives (edge: 2 nodes, face: 3 nodes, or tet: 4 nodes). Two of these must have the same `N` otherwise it is a compiler error and the left and right hand sides are equal if and only if they contain the same exact list of nodes in arbitrary order (hence the call to `std::sort` in the implementation).
 * `Hash<N>` generates a hash for any primitive by calling `HighwayHash`'s `SipHash` function, and it also has a sort because nodes in a different order produces different hashes and want them to be the same for arbitrary order.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Comment by adityakpandare** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rfbird)

---

*[src/Mesh/UnsMesh.h, line 90 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/251#-LGS2MWs-3y0gv8_uD7w:-LGVNuoe2v5ayScOy9UD:b-ab5r2a) ([raw file](https://github.com/quinoacomputing/quinoa/blob/907d48f5eea7f8ef2880d02b154503740b63dc12/src/Mesh/UnsMesh.h#L90)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Yeah. `Eq<N>` is the `KeyEqual` template argument to [unordered_set](https://en.cppreference.com/w/cpp/container/unordered_set) and [unordered_map](https://en.cppreference.com/w/cpp/container/unordered_map) and `Hash<N>` is the hash. They are both parameterized by `N`, because otherwise they do the same:
 * `Eq<N>` performs an equality comparison between two primitives (edge: 2 nodes, face: 3 nodes, or tet: 4 nodes). Two of these must have the same `N` otherwise it is a compiler error and the left and right hand sides are equal if and only if they contain the same exact list of nodes in arbitrary order (hence the call to `std::sort` in the implementation).
 * `Hash<N>` generates a hash for any primitive by calling `HighwayHash`'s `SipHash` function, and it also has a sort because nodes in a different order produces different hashes and want them to be the same for arbitrary order.
</blockquote></details>

Great! Thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/251)*

**Pull request merged**
