### PR TITLE
Added: Solid Terms for stability and more complete speed of sound

### PR DESCRIPTION
**Pull request by airaudofacundo**
Implemented discretized terms from Eq. (17) of Hill et al. (2009).
Implemented speed of sound as the maximum eigenvalue of the complete acoustic propagator in SmallShearSolids.
Fixed bug where variables allocated with "malloc" were never being freed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Excellent work! I have a few comments below. Also, regression tests are failing for `compflow` and `transport` with seg-faults, I think because the vector `solidx` is not allocated for those PDEs (since solids problems can only be solved in multimat). Can you run the regression tests and see if you can fix that?

> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-:-N_f0YqjAr6Rn7x_JYc1:b-g3hnl)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @airaudofacundo)

___
*[`src/Base/Vector.hpp` line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_euK7u-7eyAyZz3jUn:-N_euK7u-7eyAyZz3jUo:b-dtcv15) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L463)):*
> ```cpp
>   free(G);
>   free(C);
>   free(ipiv);
> ```

Great debugging here!
___
*[`src/PDE/EoS/SmallShearSolid.cpp` line 555 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ewKu057viTrN-nvsm:-N_ewKu057viTrN-nvsn:b-5z3m6l) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/EoS/SmallShearSolid.cpp#L555)):*
> ```cpp
>       for (std::size_t k=0; k<3; ++k)
>       {
> 	amat[i*3+j] -= adefgrad[k][j]*dsigdg[i][k];
> ```

Leading tab-space in line above.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 910 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ez4iv25Xru8vdBElH:-N_ez4iv25Xru8vdBElI:b-zcfl27) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/MultiMatTerms.cpp#L910)):*
> ```cpp
>       {
>         fl[deformIdx(nmat,solidx[k],i,0)][0] =
>           u*g[i][0] + v*g[i][1] + w*g[i][2];
> ```

This contribution (dot product of g_ij with u_j) is same for all equations. Let's compute it only once and add it to each `fl` as needed.
___
*[`src/PDE/Integrate/SolidTerms.hpp` line 25 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_eulus6c6Bner-i6kH:-N_eulus6c6Bner-i6kI:bll1uxq) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.hpp#L25)):*
> ```cpp
> #include "UnsMesh.hpp"
> #include "MultiMatTerms.hpp"
> #include "FunctionPrototypes.hpp"
> ```

I believe you can get rid of the `FunctionPrototypes.hpp` include here. The general guidance is, only include stuff in the place that actually needs it. So here, only include stuff that's needed in this hpp file. More includes that are needed only in the cpp, to the cpp. One such example is `Basis.hpp`, which I think will only be needed in the cpp, and not here in the hpp.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 128 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ezqEO1YtZjstwKYb_:-N_ezqEO1YtZjstwKYba:b-oobbck) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.cpp#L128)):*
> ```cpp
>       dBdx[0].resize( ndof, 0 );
>       dBdx[1].resize( ndof, 0 );
>       dBdx[2].resize( ndof, 0 );
> ```

Why are you explicitly declaring and resizing `dBdx`? It is done by `eval_dBdx_p1()`, so we shouldn't have to do it explicitly. Just `auto dBdx = eval_dBdx_p1()` should suffice, right?
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 336 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_f-ugu4J1soAxpeX6U:-N_f-ugu4J1soAxpeX6V:b-iigekw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.cpp#L336)):*
> ```cpp
>     for (std::size_t j=0; j<3; ++j)
>     {
>       auto mark = inciter::deformIdx(nmat,solidx,i,j) * ndof;
> ```

Let's just call `deformDofIdx()`? That basically does `deformIdx()*ndof + idof`.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 772 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_evsu98lhcEa5GgKoW:-N_evsu98lhcEa5GgKoX:b-amc1s0) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/MultiMat/DGMultiMat.hpp#L772)):*
> ```cpp
>       bool haveSolid = false;
>       for (std::size_t k=0; k<nmat; ++k)
>         if (solidx[k] > 0) haveSolid = true;
> ```

I am inclined to suggest that the above piece of code be put into a separate function, since it has been used a few times, for code reuse. That function can return a `bool haveSolid`.

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @airaudofacundo)

___
*[`src/Base/Vector.hpp` line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_euK7u-7eyAyZz3jUn:-N_f3QH00tLA7Az3obw1:b-ydh3dt) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L463)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Great debugging here!
</blockquote></details>

If the sizes of G, C, and ipiv are fixed and known at compile-time, while not just use that fact and write it simpler and less error-prone?
```
double G[9], C[9];
lapack_int ipiv[9];
```
The compiler will automatically allocate this on the stack, making access a lot faster than having to load it from the heap (if you dynamically allocate them with malloc), and there is no need to free them.
___
*[`src/Base/Vector.hpp` line 516 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_f4OAI8_WlR5LBYMWH:-N_f4OAI8_WlR5LBYMWI:b2nreh6) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L516)):*
> ```cpp
>   free(G);
>   free(b);
>   free(ipiv);
> ```

Same as above.
___
*[`src/Base/Vector.hpp` line 604 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_f4fFs4ZKllmYc6QXH:-N_f4fFs4ZKllmYc6QXI:bp6i478) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L604)):*
> ```cpp
>   free(rotMat);
>   free(matAuxIn);
>   free(matAuxOut);
> ```

Same here. Or if you really want to keep it as std::array, I would not make it nested, and can pass pointers to blass with .data().

**Review by adityakpandare — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @airaudofacundo and @jbakosi)

___
*[`src/PDE/Integrate/SolidTerms.hpp` line 25 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_eulus6c6Bner-i6kH:-N_ipp0_0ddHJdsUol1B:b-sfxrwv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.hpp#L25)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I believe you can get rid of the `FunctionPrototypes.hpp` include here. The general guidance is, only include stuff in the place that actually needs it. So here, only include stuff that's needed in this hpp file. More includes that are needed only in the cpp, to the cpp. One such example is `Basis.hpp`, which I think will only be needed in the cpp, and not here in the hpp.
</blockquote></details>

I meant "*move* includes that are needed only in the cpp, to the cpp"

**Review by airaudofacundo — COMMENTED** [review]
Implemented suggestions. In addition I dealt with the DGTransport and DGCompflow cases crashing because they didn't know what solidx was. To do that I added solidx as an argument of surfInt, as we discussed.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-:-N_jZ8QS8H401cK1PrKW:bje9jin)* status: 3 of 13 files reviewed, 6 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[`src/Base/Vector.hpp` line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_euK7u-7eyAyZz3jUn:-N_jWnXVDHE0Ia3iU49q:bqtmn7g) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L463)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

If the sizes of G, C, and ipiv are fixed and known at compile-time, while not just use that fact and write it simpler and less error-prone?
```
double G[9], C[9];
lapack_int ipiv[9];
```
The compiler will automatically allocate this on the stack, making access a lot faster than having to load it from the heap (if you dynamically allocate them with malloc), and there is no need to free them.
</blockquote></details>

Thank you Jozsef for the suggestion. You are right, it is much better. I implemented it.
___
*[`src/PDE/EoS/SmallShearSolid.cpp` line 555 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ewKu057viTrN-nvsm:-N_jX9Rk8W9PHRnf-vu1:b-grfeqr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/EoS/SmallShearSolid.cpp#L555)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Leading tab-space in line above.
</blockquote></details>

Removed the tab-space, and also implemented Joszef's suggestion for the Lapacke calls.
___
*[`src/PDE/Integrate/MultiMatTerms.cpp` line 910 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ez4iv25Xru8vdBElH:-N_jXsKn-IuCSkYldt8s:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/MultiMatTerms.cpp#L910)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This contribution (dot product of g_ij with u_j) is same for all equations. Let's compute it only once and add it to each `fl` as needed.
</blockquote></details>

Done.
___
*[`src/PDE/Integrate/SolidTerms.hpp` line 25 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_eulus6c6Bner-i6kH:-N_jXu0eD3h5M7LEmiCZ:b-k0r44u) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.hpp#L25)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I meant "*move* includes that are needed only in the cpp, to the cpp"
</blockquote></details>

I understand, I believe I removed all unnecessary includes.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 128 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ezqEO1YtZjstwKYb_:-N_jXzEd0Dz8EORHFqqe:b-wm7aeu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.cpp#L128)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Why are you explicitly declaring and resizing `dBdx`? It is done by `eval_dBdx_p1()`, so we shouldn't have to do it explicitly. Just `auto dBdx = eval_dBdx_p1()` should suffice, right?
</blockquote></details>

In the case that rdof=1 (p0), we want a dBdx of size 1 by 3 filled with zeros, and should never call eval_dBdx_p1 in that case.
I did copy that initialization from eval_dBdx_p1, let me know if you want me to write it differently.
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 336 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_f-ugu4J1soAxpeX6U:-N_jYK5aCBZ2oVnPCyL8:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.cpp#L336)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Let's just call `deformDofIdx()`? That basically does `deformIdx()*ndof + idof`.
</blockquote></details>

Done.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 772 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_evsu98lhcEa5GgKoW:-N_jYe5f0IKT3SQhV7-6:btvk4vv) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/MultiMat/DGMultiMat.hpp#L772)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I am inclined to suggest that the above piece of code be put into a separate function, since it has been used a few times, for code reuse. That function can return a `bool haveSolid`.
</blockquote></details>

Made that function. I decided to put it into Base/Vector.hpp because if it was inside of a MultiMat file like MiscMultiMat I would have to add the includes into all the files are not part of MultiMat, like DGCompFlow and DGTransport.

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Thanks @airaudofacundo. A couple of minor suggestions, and good to merge after that.

> Reviewed 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-:-N_jmEFn1pDkkL-SNZJ4:b5ohr7)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @airaudofacundo and @jbakosi)

___
*[`src/Base/Vector.hpp` line 463 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_euK7u-7eyAyZz3jUn:-N_jgOQDBqewwz7Ff-7n:byz4xtl) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/Base/Vector.hpp#L463)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Thank you Jozsef for the suggestion. You are right, it is much better. I implemented it.
</blockquote></details>

Thanks for taking a look @jbakosi, and thanks for fixing this @airaudofacundo.
___
*[`src/PDE/Integrate/SolidTerms.hpp` line 25 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_eulus6c6Bner-i6kH:-N_jiBFS-BpSVjix9Ql2:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.hpp#L25)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

I understand, I believe I removed all unnecessary includes.
</blockquote></details>

Thanks!
___
*[`src/PDE/Integrate/SolidTerms.cpp` line 128 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_ezqEO1YtZjstwKYb_:-N_jjKbvEqapDWI53x6l:bhr9u4y) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/Integrate/SolidTerms.cpp#L128)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

In the case that rdof=1 (p0), we want a dBdx of size 1 by 3 filled with zeros, and should never call eval_dBdx_p1 in that case.
I did copy that initialization from eval_dBdx_p1, let me know if you want me to write it differently.
</blockquote></details>

Ah, I understand, thanks. This is necessary since the functions `eval_dBdx...()` are not able distinguish between `rdof` and `ndof`.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 772 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_evsu98lhcEa5GgKoW:-N_jh2etALU6-jfzkayY:baicblz) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/MultiMat/DGMultiMat.hpp#L772)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Made that function. I decided to put it into Base/Vector.hpp because if it was inside of a MultiMat file like MiscMultiMat I would have to add the includes into all the files are not part of MultiMat, like DGCompFlow and DGTransport.
</blockquote></details>

In that case, let's place the function in `PDE/EoS/GetMatProp.hpp`. Vector.hpp only has vector-related operations, and we shouldn't put PDE-related stuff under `src/Base/` anyway.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 731 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_jgrjdDKCIrnCWf4Or:-N_jgrjdDKCIrnCWf4Os:b-tbk66p) ([raw file](https://github.com/quinoacomputing/quinoa/blob/73f0572239395a47a104c828304d3a7b7f311caf/src/PDE/MultiMat/DGMultiMat.hpp#L731)):*
> ```cpp
>       // compute optional source term
>       tk::srcInt( m_system, m_mat_blk, t, ndof, fd.Esuel().size()/4, inpoel,
> 		  coord, geoElem, Problem::src, ndofel, R, nmat );
> ```

Leading tab-spaces in the line above.

**Review by adityakpandare — COMMENTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583)* status: all files reviewed, 2 unresolved discussions (waiting on @airaudofacundo)

**Review by airaudofacundo — COMMENTED** [review]
Implemented fixes.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-:-N_jy8_01sJHLbBblkGq:b-hxk4du)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @adityakpandare and @jbakosi)

___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 772 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_evsu98lhcEa5GgKoW:-N_jxz9GCS_cy-dTp5EH:bkej9kb) ([raw file](https://github.com/quinoacomputing/quinoa/blob/2d91125ea79b8b042a93f5200463ac598730d56b/src/PDE/MultiMat/DGMultiMat.hpp#L772)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

In that case, let's place the function in `PDE/EoS/GetMatProp.hpp`. Vector.hpp only has vector-related operations, and we shouldn't put PDE-related stuff under `src/Base/` anyway.
</blockquote></details>

I put it in MiscMultiMat as we discussed, I was wrong about needing to include it in CompFlow and Transport.
___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 731 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_jgrjdDKCIrnCWf4Or:-N_jy64H6K2CRTAQUvcR:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/73f0572239395a47a104c828304d3a7b7f311caf/src/PDE/MultiMat/DGMultiMat.hpp#L731)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

Leading tab-spaces in the line above.
</blockquote></details>

Done.

**Review by adityakpandare — APPROVED** [review]
Looks good to merge.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-:-N_oCCq79cDIGt_Xn_Hm:bb3w6qx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @airaudofacundo)

___
*[`src/PDE/MultiMat/DGMultiMat.hpp` line 731 at r2](https://reviewable.io/reviews/quinoacomputing/quinoa/583#-N_jgrjdDKCIrnCWf4Or:-N_oC-JzBzlqRMxElzYV:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/73f0572239395a47a104c828304d3a7b7f311caf/src/PDE/MultiMat/DGMultiMat.hpp#L731)):*
<details><summary><i>Previously, airaudofacundo (Facundo Nicolás Airaudo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Pull request merged**
