### PR TITLE
modified hierarchical limiting to transform to Taylor on reference elements

### PR DESCRIPTION
**Pull request by adityakpandare**
*Removed test for dgp2 limiting since its going to change soon.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/551)

### CODE REVIEW

**Review by adityakpandare — COMMENTED** [review]
@weizhaoli2018: you don't have to check the calculations, matrix-elements, etc. Just take a look at the code changes. I have removed the Sedov P2 test since the limiter is going to change again soon; once we finalize the limiter, we can include the test again.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/551#-:-N2XihGn0AQ6EAgng05J:b-u51zj9)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @WeizhaoLi2018)

**Review by WeizhaoLi2018 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/551)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[`src/PDE/Integrate/Basis.cpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/551#-N2Xokrk7Zzic7d-Aqqc:-N2Xokrk7Zzic7d-Aqqd:b-bnqfpe) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9ea698515a9b3a527f4c64e2a03238d7c2b34008/src/PDE/Integrate/Basis.cpp#L84)):*
> ```cpp
> }
> 
> std::array< std::vector<tk::real>, 3 >
> ```

Here we can reuse this in our calculation of derivatives in physical domain. It might require some changes for the eval_dBdx function.

It's not that important and we don't need to do this right now. I just put a reminder here.

**Review by WeizhaoLi2018 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/551#-:-N2Xq2pC94mMoF_ZHD_b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

**Review by adityakpandare — COMMENTED** [review]
Thanks for the quick review.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/551#-:-N2XqeTZDHzbijqmuN_V:b-ncgzbp)* status: all files reviewed, 1 unresolved discussion (waiting on @WeizhaoLi2018)

___
*[`src/PDE/Integrate/Basis.cpp` line 84 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/551#-N2Xokrk7Zzic7d-Aqqc:-N2XqV6gAHl-zWqIQIE9:b-jrzoyu) ([raw file](https://github.com/quinoacomputing/quinoa/blob/9ea698515a9b3a527f4c64e2a03238d7c2b34008/src/PDE/Integrate/Basis.cpp#L84)):*
<details><summary><i>Previously, WeizhaoLi2018 (Weizhao Li) wrote…</i></summary><blockquote>

Here we can reuse this in our calculation of derivatives in physical domain. It might require some changes for the eval_dBdx function.

It's not that important and we don't need to do this right now. I just put a reminder here.
</blockquote></details>

Yeah, I noticed this, but thought that it's not as important for now. Let's leave this for next time.

**Pull request merged**
