### PR TITLE
ALE moving sidesets

### PR DESCRIPTION
**Pull request by jbakosi**
This puts in moving side sets to ALE. Now the user can prescribe a discrete function that is used to move a list of side sets. See `cyl_move.q` for an example. Forked from #510.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/511)

### CODE REVIEW

**Review by adityakpandare — CHANGES_REQUESTED** [review]
Looks good, just a minor comment. Thanks for the explanation.

> Reviewed 25 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-:-Mk3Gjq82zn5XwIvglCq:b-w4sflv)* status: 25 of 67 files reviewed, 1 unresolved discussion (waiting on @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 1049 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-Mk3Ar593cnYk4JbmcsM:-Mk3Ar593cnYk4JbmcsN:b-bxzuzr) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5492f0095b6aff2f5c787124517faee7572753d1/src/Inciter/ALECG.cpp#L1049)):*
> ```cpp
>         if (std::get<0>(m) == tk::ctr::UserTableType::VELOCITY) {
>           auto meshvel = tk::sample( d->T(), std::get<1>(m) );
>           for (const auto& i : std::get<2>(m))
> ```

This could be just `auto i` since `i` is just a node-id.
___
*[src/Inciter/ALECG.cpp, line 1059 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-Mk3Byn8A2dpdV7Ptvl_:-Mk3Byn8A2dpdV7Ptvla:b-z9cbe3) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5492f0095b6aff2f5c787124517faee7572753d1/src/Inciter/ALECG.cpp#L1059)):*
> ```cpp
>             for (const auto& i : std::get<2>(m))
>               for (auto j : g_inputdeck.get< tag::ale, tag::mesh_motion >())
>                 m_w(i,j,0) = (m_coord0[j][i] + pos[j] - m_coordn[j][i]) / adt;
> ```

+1 for the user-def position being relative from the initial position!

**Review by adityakpandare — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/511)* status: 25 of 67 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 1049 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-Mk3Ar593cnYk4JbmcsM:-Mk3Wnsd9xfQsOenG9TN:b-ucfknh) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5492f0095b6aff2f5c787124517faee7572753d1/src/Inciter/ALECG.cpp#L1049)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This could be just `auto i` since `i` is just a node-id.
</blockquote></details>

Thanks!

**Review by jbakosi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/511)* status: 25 of 67 files reviewed, all discussions resolved (waiting on @jbakosi)

___
*[src/Inciter/ALECG.cpp, line 1049 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-Mk3Ar593cnYk4JbmcsM:-Mk3IjQr0gUWxQeWFpAS:b-896fix) ([raw file](https://github.com/quinoacomputing/quinoa/blob/5492f0095b6aff2f5c787124517faee7572753d1/src/Inciter/ALECG.cpp#L1049)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

This could be just `auto i` since `i` is just a node-id.
</blockquote></details>

Done.

**Review by adityakpandare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/511#-:-Mk7sKzC2Ga2GK470aSw:bnfp4nl)* status: 25 of 67 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Pull request merged**
