### PR TITLE
Make Lua/Sol2 optional

### PR DESCRIPTION
**Pull request by jbakosi**
If we build our own Lua (if not found on the system), Cmake's built-in FindLua.cmake does not find `Lua.h`. As a workaround this makes Lua/Sol2 optional. Relevant commits in the cmake and tpl repos are 85a071e and d8d55e1, respectively.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/447)

### CODE REVIEW

**Comment by jbakosi** [comment]
@adityakpandare : I did partial testing of this locally for when there is no Lua system-wide, but since all our CI does have Lua/Sol2, can you coordinate with @WeizhaoLi2018 to test this in the absence of Lua?

**Review by adityakpandare — CHANGES_REQUESTED** [review]
I've asked @weizhaoli2018 to test if this branch compiles for him. I'll keep you updated on that.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-:-MHRJiqw-E884EUoKfWw:b-2d1ktr)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @adityakpandare and @jbakosi)

___
*[cmake/FindExaM2M.cmake, line 3 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-MHRJM9x7tL4RMLiYn1e:-MHRJM9x7tL4RMLiYn1f:b-xhdciw) ([raw file](https://github.com/quinoacomputing/quinoa/blob/1cf212e8ccce88c0e7d18814e1dec5ce4c8d6a32/cmake/FindExaM2M.cmake#L3)):*
> ```CMake
> ################################################################################
> #
> # \file      FindExaM2M.cmake
> ```

I'm curious why this ExaM2M cmake file is present in this commit. Is this related to the Lua change?

**Review by jbakosi — COMMENTED** [review]
Thanks.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-:-MHRKE9K9LX3m0T87rPM:b-ucfkn4)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @adityakpandare)

___
*[cmake/FindExaM2M.cmake, line 3 at r1](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-MHRJM9x7tL4RMLiYn1e:-MHRKFDa9_WUqTTVLGtK:batzdzp) ([raw file](https://github.com/quinoacomputing/quinoa/blob/1cf212e8ccce88c0e7d18814e1dec5ce4c8d6a32/cmake/FindExaM2M.cmake#L3)):*
<details><summary><i>Previously, adityakpandare (Aditya Pandare) wrote…</i></summary><blockquote>

I'm curious why this ExaM2M cmake file is present in this commit. Is this related to the Lua change?
</blockquote></details>

Because I have been working on integrating the mesh-to-mesh transfer, made some commits to the TPL repo, and had to pull in the latest here.

**Review by adityakpandare — APPROVED** [review]
:lgtm: Approving it. Will keep you updated as @weizhaoli2018 gets back to me.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-:-MHRSHJk6nTU2Kn2MCcu:bwsgjlh)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @adityakpandare)

**Comment by jbakosi** [comment]
Note that now if you want Lua/Sol2, you have to enable it by passing `-DENABLE_SOL2=true` to the TPL build.

**Review by WeizhaoLi2018 — COMMENTED** [review]
Hi guys, I just tested this branch and it could compile and run well on ARC.
Thanks!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/447#-:-MHSAFfm79MQ9vC0aJN8:b-gzsdf9)* status: 6 of 7 files reviewed, all discussions resolved

**Comment by jbakosi** [comment]
Great! Thanks @WeizhaoLi2018 for trying it out. Once the testing finishes, I will merge to develop.

**Pull request merged**
