### PR TITLE
Total energy monitor for dg

### PR DESCRIPTION
**Pull request by adityakpandare**
Implemented a total energy monitor in the diagnostic file for dg; changed the ndiff config files to skip this total energy column while testing the diagnostic files.

---
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/460)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
Looks good. Thanks for this. Yeah, I suspect `std::cout` was failing in SMP because, that is not thread-safe in general. Good to go!

> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/460#-:-MN-JSnq0vBFby2EaiQ6:b-9qosl9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Yeah, I missed that. Thanks for the quick review!

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/460#-:-MN-Nif86WRN_BjtgKk2:b-yu1n64)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jbakosi — APPROVED** [review]
Sure. Can you please also merge branch _output_clang_? Thanks.

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/460#-:-MN-OZex33dSq0L9ycfz:b10i1i9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by adityakpandare — COMMENTED** [review]
Sure. I just have to wait for Azure to pass the branch correct? No other requirements to merge?

> *[Reviewable](https://reviewable.io/reviews/quinoacomputing/quinoa/460#-:-MN-Rm9p7GvfpEoAY22z:b6gbj3k)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
